# Generated by Django 3.2.6 on 2021-11-14 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo dokumentu')),
                ('datum', models.DateField(verbose_name='Dátum')),
                ('odosielatel', models.CharField(max_length=200, verbose_name='Odosielateľ')),
                ('adresat', models.CharField(max_length=200, verbose_name='Adresát')),
                ('vec', models.CharField(max_length=200, verbose_name='Vec')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Prijaté a odoslané dokumenty',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDokument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo dokumentu')),
                ('datum', models.DateField(verbose_name='Dátum')),
                ('odosielatel', models.CharField(max_length=200, verbose_name='Odosielateľ')),
                ('adresat', models.CharField(max_length=200, verbose_name='Adresát')),
                ('vec', models.CharField(max_length=200, verbose_name='Vec')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='Poznámka')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dokument',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
