# Generated by Django 3.2.6 on 2021-11-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='url',
            field=models.URLField(blank=True, help_text='Zadajte URL.', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='url',
            field=models.URLField(blank=True, help_text='Zadajte URL.', verbose_name='URL'),
        ),
    ]
