# Generated by Django 3.2.6 on 2021-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0002_auto_20211114_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='sposob',
            field=models.CharField(blank=True, choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('mail', 'E-mail'), ('osobne', 'Osobne')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='sposob',
            field=models.CharField(blank=True, choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('mail', 'E-mail'), ('osobne', 'Osobne')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
    ]
