# Generated by Django 3.2.6 on 2021-11-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0003_auto_20211116_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='prijalodoslal',
            field=models.CharField(blank=True, help_text='Uveďte meno osoby, ktorá zásielku prijala / odoslala.', max_length=50, verbose_name='Prijal/odoslal'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='prijalodoslal',
            field=models.CharField(blank=True, help_text='Uveďte meno osoby, ktorá zásielku prijala / odoslala.', max_length=50, verbose_name='Prijal/odoslal'),
        ),
    ]
