# Generated by Django 3.2.6 on 2022-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0004_auto_20211122_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='cislopolozky',
            field=models.CharField(help_text='Ak je to relevantné, uveďte číslo súvisiacej položky (zmluvy, dohody, faktúry). Pokiaľ položka ešte nie je v Djagu vytvorená (napr. ešte v prípade faktúry), najskôr ju vytvorte a záznam spravte potom)', max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='datumvytvorenia',
            field=models.DateField(help_text='Dátum vytvorenia záznamu (vypĺňané automaticky)', null=True, verbose_name='Dátum vytvorenia záznamu'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Prijatý / odoslaný'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(choices=[('autorskazmluva', 'Autorská zmluva'), ('faktura', 'Faktúra'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='zaznamvytvoril',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý záznam v denníku vytvoril (vypĺňané automaticky)', max_length=50, verbose_name='Záznam vytvoril'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='cislopolozky',
            field=models.CharField(help_text='Ak je to relevantné, uveďte číslo súvisiacej položky (zmluvy, dohody, faktúry). Pokiaľ položka ešte nie je v Djagu vytvorená (napr. ešte v prípade faktúry), najskôr ju vytvorte a záznam spravte potom)', max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='datumvytvorenia',
            field=models.DateField(help_text='Dátum vytvorenia záznamu (vypĺňané automaticky)', null=True, verbose_name='Dátum vytvorenia záznamu'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Prijatý / odoslaný'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(choices=[('autorskazmluva', 'Autorská zmluva'), ('faktura', 'Faktúra'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='zaznamvytvoril',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý záznam v denníku vytvoril (vypĺňané automaticky)', max_length=50, verbose_name='Záznam vytvoril'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='adresat',
            field=models.CharField(help_text='Uveďte adresáta', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='cislo',
            field=models.CharField(max_length=50, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='datum',
            field=models.DateField(help_text='Dátum prijatia / odoslania dokumentu', verbose_name='Dátum prijatia / odoslania'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='odosielatel',
            field=models.CharField(blank=True, max_length=200, verbose_name='xTyp dokumentu'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='prijalodoslal',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý zaznamenal prijatie / odoslanie zásielky (vypĺňané automaticky).', max_length=50, verbose_name='Prijal/odoslal'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Zmluva A-2022-007'", max_length=200, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='adresat',
            field=models.CharField(help_text='Uveďte adresáta', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='cislo',
            field=models.CharField(max_length=50, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='datum',
            field=models.DateField(help_text='Dátum prijatia / odoslania dokumentu', verbose_name='Dátum prijatia / odoslania'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='odosielatel',
            field=models.CharField(blank=True, max_length=200, verbose_name='xTyp dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='prijalodoslal',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý zaznamenal prijatie / odoslanie zásielky (vypĺňané automaticky).', max_length=50, verbose_name='Prijal/odoslal'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Zmluva A-2022-007'", max_length=200, verbose_name='Popis'),
        ),
    ]
