# Generated by Django 3.2.6 on 2022-01-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0004_auto_20211122_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='inout',
            field=models.CharField(blank=True, choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Prijatý / odoslaný'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='inout',
            field=models.CharField(blank=True, choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Prijatý / odoslaný'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='odosielatel',
            field=models.CharField(max_length=200, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='odosielatel',
            field=models.CharField(max_length=200, verbose_name='Typ dokumentu'),
        ),
    ]
