# Generated by Django 3.2.6 on 2022-01-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0005_auto_20220117_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='naspracovanie',
            field=models.CharField(blank=True, help_text='Uveďte meno osoby, ktorej bol dokument daný na spracovanie', max_length=50, verbose_name='Na spracovanie'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='naspracovanie',
            field=models.CharField(blank=True, help_text='Uveďte meno osoby, ktorej bol dokument daný na spracovanie', max_length=50, verbose_name='Na spracovanie'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <strong>Netreba vypĺňať, ak je vyplnené pole Súvisiaca položka</strong>.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky (zmluvy, dohody, faktúry), inak vložte pomlčku '-'. Pokiaľ položka ešte nie je v Djangu vytvorená (napr. v prípade faktúry), najskôr ju vytvorte a záznam spravte potom).", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='prijalodoslal',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý záznam v denníku vytvoril (vypĺňané automaticky)', max_length=50, verbose_name='Záznam vytvoril'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='sposob',
            field=models.CharField(choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('mail', 'E-mail'), ('osobne', 'Osobne')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('faktura', 'Faktúra'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je vyplnené pole Súvisiaca položka</strong>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Podpísaná zmluva'", max_length=200, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='zaznamvytvoril',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý zaznamenal prijatie / odoslanie zásielky (vypĺňané automaticky).', max_length=50, verbose_name='Prijal/odoslal'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <strong>Netreba vypĺňať, ak je vyplnené pole Súvisiaca položka</strong>.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky (zmluvy, dohody, faktúry), inak vložte pomlčku '-'. Pokiaľ položka ešte nie je v Djangu vytvorená (napr. v prípade faktúry), najskôr ju vytvorte a záznam spravte potom).", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='prijalodoslal',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý záznam v denníku vytvoril (vypĺňané automaticky)', max_length=50, verbose_name='Záznam vytvoril'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='sposob',
            field=models.CharField(choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('mail', 'E-mail'), ('osobne', 'Osobne')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('faktura', 'Faktúra'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je vyplnené pole Súvisiaca položka</strong>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Podpísaná zmluva'", max_length=200, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='zaznamvytvoril',
            field=models.CharField(blank=True, help_text='Meno používateľa, ktorý zaznamenal prijatie / odoslanie zásielky (vypĺňané automaticky).', max_length=50, verbose_name='Prijal/odoslal'),
        ),
    ]
