# Generated by Django 3.2.6 on 2022-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0005_auto_20220117_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Prijatý / odoslaný'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Prijatý / odoslaný'),
        ),
    ]
