# Generated by Django 3.2.6 on 2022-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0006_auto_20220117_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='cislopolozky',
            field=models.CharField(help_text='Ak je to relevantné, uveďte číslo súvisiacej položky (zmluvy, dohody, faktúry). Pokiaľ položka ešte nie je v Djagu vyrvorená (napr. ešte v prípade faktúry), najskôr ju vytvorte a záznam spravte potom)', max_length=200, null=True, verbose_name='Číslo položky'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='cislopolozky',
            field=models.CharField(help_text='Ak je to relevantné, uveďte číslo súvisiacej položky (zmluvy, dohody, faktúry). Pokiaľ položka ešte nie je v Djagu vyrvorená (napr. ešte v prípade faktúry), najskôr ju vytvorte a záznam spravte potom)', max_length=200, null=True, verbose_name='Číslo položky'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(choices=[('prijaty', 'Prijatý'), ('odoslany', 'Odoslaný')], max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='adresat',
            field=models.CharField(help_text='Uveďte adresáta', max_length=200, verbose_name='Adresát'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='cislo',
            field=models.CharField(max_length=50, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='datum',
            field=models.DateField(help_text='Dátum prijatia / odoslania dokumentu', verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='odosielatel',
            field=models.CharField(max_length=200, verbose_name='xTyp dokumentu'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Zmluva A-2022-007'", max_length=200, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='adresat',
            field=models.CharField(help_text='Uveďte adresáta', max_length=200, verbose_name='Adresát'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='cislo',
            field=models.CharField(max_length=50, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='datum',
            field=models.DateField(help_text='Dátum prijatia / odoslania dokumentu', verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='odosielatel',
            field=models.CharField(max_length=200, verbose_name='xTyp dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Zmluva A-2022-007'", max_length=200, verbose_name='Popis'),
        ),
    ]
