# Generated by Django 3.2.6 on 2022-01-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0006_auto_20220117_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='datum',
            field=models.DateField(blank=True, help_text='Dátum prijatia / odoslania dokumentu', verbose_name='Dátum prijatia / odoslania'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='naspracovanie',
            field=models.CharField(help_text="Uveďte meno osoby, ktorej bol prijatý dokument daný na spracovanie. Pri odosielanom dokumente vložte pomlčku '-'.", max_length=50, null=True, verbose_name='Na spracovanie'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='datum',
            field=models.DateField(blank=True, help_text='Dátum prijatia / odoslania dokumentu', verbose_name='Dátum prijatia / odoslania'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='naspracovanie',
            field=models.CharField(help_text="Uveďte meno osoby, ktorej bol prijatý dokument daný na spracovanie. Pri odosielanom dokumente vložte pomlčku '-'.", max_length=50, null=True, verbose_name='Na spracovanie'),
        ),
    ]
