# Generated by Django 3.2.6 on 2022-01-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0007_auto_20220117_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='datum',
            field=models.DateField(help_text='Dátum prijatia / odoslania dokumentu', null=True, verbose_name='Dátum prijatia / odoslania'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='datum',
            field=models.DateField(help_text='Dátum prijatia / odoslania dokumentu', null=True, verbose_name='Dátum prijatia / odoslania'),
        ),
    ]
