# Generated by Django 3.2.6 on 2022-01-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0007_auto_20220117_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(choices=[('autorskazmluva', 'Autorská zmluva'), ('faktura', 'Faktúra'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(choices=[('autorskazmluva', 'Autorská zmluva'), ('faktura', 'Faktúra'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
    ]
