# Generated by Django 3.2.6 on 2022-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0008_auto_20220117_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky v databáze (zmluvy, dohody, faktúry) v tvare X-RRRR-NNN, inak vložte pomlčku '-'.<br />Pokiaľ položka ešte nie je v databáze vytvorená (napr. v prípade faktúry), najskôr ju vytvorte a tento záznam spravte potom).", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='naspracovanie',
            field=models.CharField(blank=True, help_text='<strong>Ak ide o prijatý dokument</strong>, uveďte meno osoby, ktorej bol daný na vybavenie. Pri odosielanom dokumente vypĺňať netreba.', max_length=50, null=True, verbose_name='Na spracovanie'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky v databáze (zmluvy, dohody, faktúry) v tvare X-RRRR-NNN, inak vložte pomlčku '-'.<br />Pokiaľ položka ešte nie je v databáze vytvorená (napr. v prípade faktúry), najskôr ju vytvorte a tento záznam spravte potom).", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='naspracovanie',
            field=models.CharField(blank=True, help_text='<strong>Ak ide o prijatý dokument</strong>, uveďte meno osoby, ktorej bol daný na vybavenie. Pri odosielanom dokumente vypĺňať netreba.', max_length=50, null=True, verbose_name='Na spracovanie'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
    ]
