# Generated by Django 3.2.6 on 2022-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0009_auto_20220120_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <br />Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN.<br />Ak už je pole v prípade odosielania dokumentu vopred vyplnené, adresáta ponechajte.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='datum',
            field=models.DateField(help_text='Dátum príjmu / odoslania dokumentu', null=True, verbose_name='Dátum príjmu / odoslania'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Príjem'), ('odoslany', 'Odosielanie')], max_length=20, null=True, verbose_name='Príjem / odosielanie'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <br />Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN.<br />Ak už je pole v prípade odosielania dokumentu vopred vyplnené, adresáta ponechajte.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='datum',
            field=models.DateField(help_text='Dátum príjmu / odoslania dokumentu', null=True, verbose_name='Dátum príjmu / odoslania'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Príjem'), ('odoslany', 'Odosielanie')], max_length=20, null=True, verbose_name='Príjem / odosielanie'),
        ),
    ]
