# Generated by Django 3.2.6 on 2022-01-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0010_auto_20220121_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name': 'Prijatá alebo odoslaná pošta', 'verbose_name_plural': 'Denník prijatej a odoslanej pošty'},
        ),
        migrations.AlterModelOptions(
            name='historicaldokument',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prijatá alebo odoslaná pošta'},
        ),
    ]
