# Generated by Django 3.2.6 on 2022-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0011_auto_20220124_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky v Djangu (autorskej zmluvy, dohody) v tvare X-RRRR-NNN, inak vložte pomlčku '-'.<br />V prípade <strong>prijatej faktúry</strong> najskôr vytvorte novú prijatú faktúru a následne len upravte záznam pošty, ktorý sa tým vytvorí.<br />V prípade <strong>odosielaných dokumentov</strong>, ktoré sa vytvárajú v Djangu, už pre ne môže v tomto denníku existovať záznam. Skontrolujte to, a ak záznam existuje, použite ten.", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Príjem'), ('odoslany', 'Odoslanie')], max_length=20, null=True, verbose_name='Príjem / odoslanie'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky v Djangu (autorskej zmluvy, dohody) v tvare X-RRRR-NNN, inak vložte pomlčku '-'.<br />V prípade <strong>prijatej faktúry</strong> najskôr vytvorte novú prijatú faktúru a následne len upravte záznam pošty, ktorý sa tým vytvorí.<br />V prípade <strong>odosielaných dokumentov</strong>, ktoré sa vytvárajú v Djangu, už pre ne môže v tomto denníku existovať záznam. Skontrolujte to, a ak záznam existuje, použite ten.", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='inout',
            field=models.CharField(choices=[('prijaty', 'Príjem'), ('odoslany', 'Odoslanie')], max_length=20, null=True, verbose_name='Príjem / odoslanie'),
        ),
    ]
