# Generated by Django 3.2.6 on 2022-01-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0012_auto_20220124_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='odosielatel',
        ),
        migrations.RemoveField(
            model_name='dokument',
            name='url',
        ),
        migrations.RemoveField(
            model_name='historicaldokument',
            name='odosielatel',
        ),
        migrations.RemoveField(
            model_name='historicaldokument',
            name='url',
        ),
    ]
