# Generated by Django 3.2.6 on 2022-01-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0013_auto_20220124_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='poznamka',
        ),
        migrations.RemoveField(
            model_name='historicaldokument',
            name='poznamka',
        ),
    ]
