# Generated by Django 3.2.6 on 2022-02-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0015_formular_historicalformular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formular',
            options={'verbose_name': 'Hromadný dokument', 'verbose_name_plural': 'Hromadné dokumenty'},
        ),
    ]
