# Generated by Django 3.2.6 on 2022-02-07 12:24

import dennik.models
import django.core.validators
from django.db import migrations, models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0016_alter_formular_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='data_komentar',
            field=models.FileField(blank=True, help_text="Upravený XLSX súbor z poľa 'Vyplnené dáta' s prípadnými zmenami, ktoré boli ručne spravené v rozposlanom dokumente a komentárom.", null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Vyplnené dáta'),
        ),
        migrations.AddField(
            model_name='formular',
            name='rozposlany',
            field=models.FileField(blank=True, help_text='Pdf vytlačeného a rozposlaného dokumentu. Ak bol hromadný dokument rozdelený, priložiť zip archív so všetkými pdf súbormi.', null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip'])], verbose_name='Rozposlaný dokument'),
        ),
        migrations.AddField(
            model_name='historicalformular',
            name='data_komentar',
            field=models.TextField(blank=True, help_text="Upravený XLSX súbor z poľa 'Vyplnené dáta' s prípadnými zmenami, ktoré boli ručne spravené v rozposlanom dokumente a komentárom.", max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Vyplnené dáta'),
        ),
        migrations.AddField(
            model_name='historicalformular',
            name='rozposlany',
            field=models.TextField(blank=True, help_text='Pdf vytlačeného a rozposlaného dokumentu. Ak bol hromadný dokument rozdelený, priložiť zip archív so všetkými pdf súbormi.', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip'])], verbose_name='Rozposlaný dokument'),
        ),
    ]
