# Generated by Django 3.2.6 on 2022-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0017_auto_20220207_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formular',
            name='typformulara',
            field=models.CharField(choices=[('vseobecny', 'Všeobecný dokument')], help_text='Uveďte typ šablóny. Určuje, aké tokeny možno použiť:\n                <ul>\n                <li><em>Všeobecný dokument</em>: ľubovoľné tokeny, bez väzby na databázu</li>\n                </ul>\n                Ako dátum vytvorenia dokumentu možno použiť token <em>dat_vytv</em>. Ak sa v dátovom súbore neuvedie, vloží sa aktuálny dátum.', max_length=20, null=True, verbose_name='Typ šablóny'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='typformulara',
            field=models.CharField(choices=[('vseobecny', 'Všeobecný dokument')], help_text='Uveďte typ šablóny. Určuje, aké tokeny možno použiť:\n                <ul>\n                <li><em>Všeobecný dokument</em>: ľubovoľné tokeny, bez väzby na databázu</li>\n                </ul>\n                Ako dátum vytvorenia dokumentu možno použiť token <em>dat_vytv</em>. Ak sa v dátovom súbore neuvedie, vloží sa aktuálny dátum.', max_length=20, null=True, verbose_name='Typ šablóny'),
        ),
    ]
