# Generated by Django 3.2.6 on 2022-02-11 11:28

import dennik.models
import django.core.validators
from django.db import migrations, models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0018_auto_20220209_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='cislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AddField(
            model_name='historicalformular',
            name='cislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='formular',
            name='data',
            field=models.FileField(help_text="XLSX súbor s dátami na generovanie. <br />Názvy stĺpcov sa musia presne zhodovať s tokenmi v šablóne (bez zátvoriek).<br />Názvy stĺpcov, ktoré majú byť formátované s dvomi desatinnými miestami, musia začínať 'n_'.", null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Dáta'),
        ),
        migrations.AlterField(
            model_name='formular',
            name='subor_nazov',
            field=models.CharField(help_text='Krátky názov dokumentu (použije sa ako názov vytvorených súborov)', max_length=40, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='formular',
            name='typformulara',
            field=models.CharField(choices=[('vseobecny', 'Všeobecný dokument'), ('ah_zrazena', 'Potvrdenie o zrazení dane z autorských honorárov')], help_text='Uveďte typ šablóny. Určuje, aké tokeny možno použiť:\n                <ul>\n                <li style="list-style-type:square"><em>Všeobecný dokument</em>: ľubovoľné tokeny, bez väzby na databázu</li>\n                <li style="list-style-type:square"><em>Potvrdenie o zrazení dane z autorských honorárov</em>: v dátovom súbore zadajte len stĺpec \'za_rok\' s jedným riadkom, v ktorom je uvedený rok, za ktorý sa má potvrdenie vytvoriť.<br />Povolené tokeny:</li>\n                <li style="list-style-type:square"> Ako dátum vytvorenia dokumentu možno použiť token <em>dat_vytv</em>. Ak sa v dátovom súbore neuvedie, vloží sa aktuálny dátum.</li>\n                </ul>', max_length=20, null=True, verbose_name='Typ šablóny'),
        ),
        migrations.AlterField(
            model_name='formular',
            name='vyplnene',
            field=models.FileField(blank=True, help_text="Vytvorený súbor hromadného dokumentu vo formáte FODT (vytvorený akciou 'Vytvoriť súbor hromadného dokumentu').", null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, verbose_name='Vytvorený súbor'),
        ),
        migrations.AlterField(
            model_name='formular',
            name='vyplnene_data',
            field=models.FileField(blank=True, help_text="XLSX súbor s dátami použitými na vytvorenie hromadného dokumentu (vytvorený akciou 'Vyplniť formulár').", null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, verbose_name='Vyplnené dáta'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='data',
            field=models.TextField(help_text="XLSX súbor s dátami na generovanie. <br />Názvy stĺpcov sa musia presne zhodovať s tokenmi v šablóne (bez zátvoriek).<br />Názvy stĺpcov, ktoré majú byť formátované s dvomi desatinnými miestami, musia začínať 'n_'.", max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Dáta'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='subor_nazov',
            field=models.CharField(help_text='Krátky názov dokumentu (použije sa ako názov vytvorených súborov)', max_length=40, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='typformulara',
            field=models.CharField(choices=[('vseobecny', 'Všeobecný dokument'), ('ah_zrazena', 'Potvrdenie o zrazení dane z autorských honorárov')], help_text='Uveďte typ šablóny. Určuje, aké tokeny možno použiť:\n                <ul>\n                <li style="list-style-type:square"><em>Všeobecný dokument</em>: ľubovoľné tokeny, bez väzby na databázu</li>\n                <li style="list-style-type:square"><em>Potvrdenie o zrazení dane z autorských honorárov</em>: v dátovom súbore zadajte len stĺpec \'za_rok\' s jedným riadkom, v ktorom je uvedený rok, za ktorý sa má potvrdenie vytvoriť.<br />Povolené tokeny:</li>\n                <li style="list-style-type:square"> Ako dátum vytvorenia dokumentu možno použiť token <em>dat_vytv</em>. Ak sa v dátovom súbore neuvedie, vloží sa aktuálny dátum.</li>\n                </ul>', max_length=20, null=True, verbose_name='Typ šablóny'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='vyplnene',
            field=models.TextField(blank=True, help_text="Vytvorený súbor hromadného dokumentu vo formáte FODT (vytvorený akciou 'Vytvoriť súbor hromadného dokumentu').", max_length=100, null=True, verbose_name='Vytvorený súbor'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='vyplnene_data',
            field=models.TextField(blank=True, help_text="XLSX súbor s dátami použitými na vytvorenie hromadného dokumentu (vytvorený akciou 'Vyplniť formulár').", max_length=100, null=True, verbose_name='Vyplnené dáta'),
        ),
    ]
