# Generated by Django 3.2.6 on 2022-02-12 11:22

import dennik.models
import django.core.validators
from django.db import migrations, models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0019_auto_20220211_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formular',
            name='data_komentar',
            field=models.FileField(blank=True, help_text="Upravený XLSX súbor z poľa 'Vyplnené dáta' s prípadnými zmenami, ktoré boli ručne spravené v rozposlanom dokumente a komentárom.", null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Upravené vyplnené dáta'),
        ),
        migrations.AlterField(
            model_name='formular',
            name='subor_popis',
            field=models.TextField(blank=True, help_text='Dlhší popis k dokumentu: účel, poznámky a pod.', max_length=600, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='data_komentar',
            field=models.TextField(blank=True, help_text="Upravený XLSX súbor z poľa 'Vyplnené dáta' s prípadnými zmenami, ktoré boli ručne spravené v rozposlanom dokumente a komentárom.", max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Upravené vyplnené dáta'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='subor_popis',
            field=models.TextField(blank=True, help_text='Dlhší popis k dokumentu: účel, poznámky a pod.', max_length=600, verbose_name='Popis'),
        ),
    ]
