# Generated by Django 3.2.6 on 2022-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0020_auto_20220212_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='sposob',
            field=models.CharField(choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('mail', 'E-mail'), ('osobne', 'Osobne'), ('web', 'Web rozhranie')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='sposob',
            field=models.CharField(choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('mail', 'E-mail'), ('osobne', 'Osobne'), ('web', 'Web rozhranie')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
    ]
