# Generated by Django 3.2.6 on 2022-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0022_auto_20220219_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <br /><strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001<em>.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky v Djangu (zmluvy, dohody), inak vložte pomlčku '-'.<br />\n            V prípade \n            <ul>\n            <li>  ‣  <strong>prijatej faktúry</strong> najskôr vytvorte novú prijatú faktúru a</li>\n            <li>  ‣  <strong>prijatej podpísanej autorskej zmluvy</strong> od autora najskôr vrátenie zaznamenajte v poli <em>Vrátená\npodpísaná</em> v zmluve</li>\n            </ol>\n            a následne len upravte záznam pošty, ktorý sa tým vytvorí.<br />\n            V prípade <strong>odosielaných dokumentov</strong>, ktoré sa vytvárajú v Djangu, už pre ne môže v tomto denníku existovať záznam. Skontrolujte to, a ak záznam existuje, použite ten.", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001<em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='adresat',
            field=models.CharField(blank=True, help_text='Uveďte adresáta. <br /><strong>Netreba vypĺňať, ak je v poli Súvisiaca položka uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001<em>.', max_length=200, verbose_name='Odosielateľ / Adresát'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='cislopolozky',
            field=models.CharField(help_text="Ak je to relevantné, uveďte číslo súvisiacej položky v Djangu (zmluvy, dohody), inak vložte pomlčku '-'.<br />\n            V prípade \n            <ul>\n            <li>  ‣  <strong>prijatej faktúry</strong> najskôr vytvorte novú prijatú faktúru a</li>\n            <li>  ‣  <strong>prijatej podpísanej autorskej zmluvy</strong> od autora najskôr vrátenie zaznamenajte v poli <em>Vrátená\npodpísaná</em> v zmluve</li>\n            </ol>\n            a následne len upravte záznam pošty, ktorý sa tým vytvorí.<br />\n            V prípade <strong>odosielaných dokumentov</strong>, ktoré sa vytvárajú v Djangu, už pre ne môže v tomto denníku existovať záznam. Skontrolujte to, a ak záznam existuje, použite ten.", max_length=200, null=True, verbose_name='Súvisiaca položka'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001<em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
    ]
