# Generated by Django 3.2.6 on 2022-03-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0041_auto_20220310_1355'),
        ('dennik', '0023_auto_20220311_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerpanieRozpoctu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('unikatny', models.CharField(help_text="Zadajte rok, za ktorý sa má vygenerovať prehľad čerpania rozpočtu. Potom použite akciu 'Generovať prehľad čerpania rozpočtu'", max_length=80, null=True, verbose_name='Položka')),
                ('polozka', models.CharField(max_length=80, null=True, verbose_name='Položka')),
                ('mesiac', models.DateField(null=True, verbose_name='Mesiac')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma v EUR')),
                ('ekoklas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cerpanierozpoctu_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='cerpanierozpoctu_klasifikacia', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cerpanierozpoctu_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cerpanierozpoctu_klasifikacia', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'Čerpanie rozpočtu',
                'verbose_name_plural': 'Čerpanie rozpočtu',
            },
        ),
    ]
