# Generated by Django 3.2.6 on 2022-03-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0041_auto_20220310_1355'),
        ('dennik', '0024_cerpanierozpoctu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerpanierozpoctu',
            name='poznamka',
        ),
        migrations.RemoveField(
            model_name='cerpanierozpoctu',
            name='program',
        ),
        migrations.AlterField(
            model_name='cerpanierozpoctu',
            name='ekoklas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cerpanierozpoctu_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia'),
        ),
        migrations.AlterField(
            model_name='cerpanierozpoctu',
            name='mesiac',
            field=models.DateField(blank=True, null=True, verbose_name='Mesiac'),
        ),
        migrations.AlterField(
            model_name='cerpanierozpoctu',
            name='suma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Suma v EUR'),
        ),
        migrations.AlterField(
            model_name='cerpanierozpoctu',
            name='unikatny',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Unikátny identifikátor'),
        ),
        migrations.AlterField(
            model_name='cerpanierozpoctu',
            name='zakazka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cerpanierozpoctu_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky'),
        ),
        migrations.AlterField(
            model_name='cerpanierozpoctu',
            name='zdroj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cerpanierozpoctu_klasifikacia', to='uctovnictvo.zdroj'),
        ),
    ]
