# Generated by Django 3.2.6 on 2022-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0031_auto_20220623_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pplatba', 'Pravidelná platba'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('najomne', 'Nájomné'), ('pravidelnaplatba', 'Pravidelná platba'), ('internyprevod', 'Interný prevod'), ('pokladnicnakniha', 'Pokladničná kniha'), ('rekreacia', 'Príspevok na rekreáciu'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001</em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Podpísaná zmluva'. Ak je pole predvyplnené, netreba ho meniť.", max_length=200, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pplatba', 'Pravidelná platba'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('najomne', 'Nájomné'), ('pravidelnaplatba', 'Pravidelná platba'), ('internyprevod', 'Interný prevod'), ('pokladnicnakniha', 'Pokladničná kniha'), ('rekreacia', 'Príspevok na rekreáciu'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001</em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='vec',
            field=models.CharField(help_text="Stručne popíšte obsah, napr. 'Podpísaná zmluva'. Ak je pole predvyplnené, netreba ho meniť.", max_length=200, verbose_name='Popis'),
        ),
    ]
