# Generated by Django 3.2.6 on 2022-09-20 10:39

import dennik.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dennik', '0032_auto_20220817_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatovaRekapitulacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifikator', models.CharField(blank=True, help_text='Identifikátor v tvare RRRR-MM. Doplní sa automaticky, ak názov súboru obsahuje údaje o období v tvare MMRRRR.', max_length=50, null=True, verbose_name='Identifikátor')),
                ('subor', models.FileField(help_text='Vložte súbor s platovou rekapituláciou. Ak názov obsahuje údaje o období v tvare MMRRRR, tak sa automaticky vyplní polia Identifikátor.', storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.pr_file_path, verbose_name='Súbor s platovou rekapituláciou')),
            ],
            options={
                'verbose_name': 'Platová rekapitulácia',
                'verbose_name_plural': 'Platová rekapitulácia',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlatovaRekapitulacia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identifikator', models.CharField(blank=True, help_text='Identifikátor v tvare RRRR-MM. Doplní sa automaticky, ak názov súboru obsahuje údaje o období v tvare MMRRRR.', max_length=50, null=True, verbose_name='Identifikátor')),
                ('subor', models.TextField(help_text='Vložte súbor s platovou rekapituláciou. Ak názov obsahuje údaje o období v tvare MMRRRR, tak sa automaticky vyplní polia Identifikátor.', max_length=100, verbose_name='Súbor s platovou rekapituláciou')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Platová rekapitulácia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
