# Generated by Django 3.2.6 on 2022-09-20 15:10

import dennik.models
from django.db import migrations, models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0033_historicalplatovarekapitulacia_platovarekapitulacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatovarekapitulacia',
            name='identifikator',
            field=models.CharField(blank=True, help_text='Identifikátor v tvare RRRR-MM. Doplní sa automaticky, ak názov súboru obsahuje údaje o období.', max_length=50, null=True, verbose_name='Identifikátor'),
        ),
        migrations.AlterField(
            model_name='historicalplatovarekapitulacia',
            name='subor',
            field=models.TextField(help_text='Vložte súbor s platovou rekapituláciou.<br />Ak názov obsahuje údaje o období v tvare MM.RRRR alebo RRRR.MM (na mieste . môže byť hocijaký znak), tak sa automaticky vyplní pole Identifikátor.', max_length=100, verbose_name='Súbor s platovou rekapituláciou'),
        ),
        migrations.AlterField(
            model_name='platovarekapitulacia',
            name='identifikator',
            field=models.CharField(blank=True, help_text='Identifikátor v tvare RRRR-MM. Doplní sa automaticky, ak názov súboru obsahuje údaje o období.', max_length=50, null=True, verbose_name='Identifikátor'),
        ),
        migrations.AlterField(
            model_name='platovarekapitulacia',
            name='subor',
            field=models.FileField(help_text='Vložte súbor s platovou rekapituláciou.<br />Ak názov obsahuje údaje o období v tvare MM.RRRR alebo RRRR.MM (na mieste . môže byť hocijaký znak), tak sa automaticky vyplní pole Identifikátor.', storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.pr_file_path, verbose_name='Súbor s platovou rekapituláciou'),
        ),
    ]
