# Generated by Django 3.2.6 on 2022-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0036_auto_20221127_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='poznamka',
            field=models.CharField(blank=True, help_text='Poznámka. Povinné len v prípade, ak ide o zrušenie záznamu.', max_length=60, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='zrusene',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Zvoľté 'Áno', ak záznam treba označit ako zrušený. V tom prípade v poli 'Poznámka' uveďte príčinu", max_length=10, null=True, verbose_name='Zrušené'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='poznamka',
            field=models.CharField(blank=True, help_text='Poznámka. Povinné len v prípade, ak ide o zrušenie záznamu.', max_length=60, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='historicaldokument',
            name='zrusene',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Zvoľté 'Áno', ak záznam treba označit ako zrušený. V tom prípade v poli 'Poznámka' uveďte príčinu", max_length=10, null=True, verbose_name='Zrušené'),
        ),
    ]
