# Generated by Django 3.2.6 on 2023-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0037_auto_20221212_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatovarekapitulacia',
            name='rozdiel_minus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vypočíta sa akciou 'Porovnať mzdové údaje s platovou rekapituláciou'", max_digits=8, null=True, verbose_name='Max. záporný rozdiel'),
        ),
        migrations.AddField(
            model_name='historicalplatovarekapitulacia',
            name='rozdiel_plus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vypočíta sa akciou 'Porovnať mzdové údaje s platovou rekapituláciou'", max_digits=8, null=True, verbose_name='Max. kladný rozdiel'),
        ),
        migrations.AddField(
            model_name='platovarekapitulacia',
            name='rozdiel_minus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vypočíta sa akciou 'Porovnať mzdové údaje s platovou rekapituláciou'", max_digits=8, null=True, verbose_name='Max. záporný rozdiel'),
        ),
        migrations.AddField(
            model_name='platovarekapitulacia',
            name='rozdiel_plus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vypočíta sa akciou 'Porovnať mzdové údaje s platovou rekapituláciou'", max_digits=8, null=True, verbose_name='Max. kladný rozdiel'),
        ),
    ]
