# Generated by Django 3.2.6 on 2023-01-18 14:39

import dennik.models
import django.core.validators
from django.db import migrations, models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0038_auto_20230111_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formular',
            name='sablona',
            field=models.FileField(help_text='FODT súbor šablóny na generovanie dokumentu. <br />Polia na vyplnenie musia byť definované ako [[tokeny]] s dvojitými hranatými zátvorkami.<br />Za posledným riadkom strany musí byť vložené <em>zalomenie strany</em>.<br />Tokeny sa musia presne zhodovať s názvami stĺpcov v dátovom súbore.', null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fodt'])], verbose_name='Šablóna dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='sablona',
            field=models.TextField(help_text='FODT súbor šablóny na generovanie dokumentu. <br />Polia na vyplnenie musia byť definované ako [[tokeny]] s dvojitými hranatými zátvorkami.<br />Za posledným riadkom strany musí byť vložené <em>zalomenie strany</em>.<br />Tokeny sa musia presne zhodovať s názvami stĺpcov v dátovom súbore.', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fodt'])], verbose_name='Šablóna dokumentu'),
        ),
    ]
