# Generated by Django 3.2.4 on 2023-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0043_auto_20231214_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pplatba', 'Pravidelná platba'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('vyplacanie_vh', 'Vyplácanie výtvarných honorárov'), ('najomne', 'Nájomné'), ('pravidelnaplatba', 'Pravidelná platba'), ('internyprevod', 'Interný prevod'), ('pokladnicnakniha', 'Pokladničná kniha'), ('rekreacia', 'Príspevok na rekreáciu'), ('posta', 'Pošta'), ('nepritomnost', 'Neprítomnosť'), ('odmena_oprava', 'Odmena/Oprava'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001</em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('vobjednavka', 'Výtvarná objednávka'), ('objednavka', 'Objednávka'), ('faktura', 'Faktúra'), ('pplatba', 'Pravidelná platba'), ('pstravne', 'Príspevok na stravné'), ('zmluva', 'Zmluva'), ('dovp', 'DoVP'), ('dopc', 'DoPC'), ('dobps', 'DoBPS'), ('hromadny', 'Hromadný dokument'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('vyplacanie_vh', 'Vyplácanie výtvarných honorárov'), ('najomne', 'Nájomné'), ('pravidelnaplatba', 'Pravidelná platba'), ('internyprevod', 'Interný prevod'), ('pokladnicnakniha', 'Pokladničná kniha'), ('rekreacia', 'Príspevok na rekreáciu'), ('posta', 'Pošta'), ('nepritomnost', 'Neprítomnosť'), ('odmena_oprava', 'Odmena/Oprava'), ('iny', 'Iný')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001</em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
    ]
