# Generated by Django 3.2.4 on 2024-01-22 11:04

import dennik.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dennik', '0045_auto_20240112_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemovySubor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subor_nazov', models.CharField(max_length=100, verbose_name='Názov')),
                ('subor_popis', models.TextField(max_length=250, verbose_name='Popis/účel')),
                ('subor', models.FileField(blank=True, null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.system_file_path)),
            ],
            options={
                'verbose_name': 'Systémový súbor',
                'verbose_name_plural': 'Systémové súbory',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSystemovySubor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subor_nazov', models.CharField(max_length=100, verbose_name='Názov')),
                ('subor_popis', models.TextField(max_length=250, verbose_name='Popis/účel')),
                ('subor', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Systémový súbor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
