# Generated by Django 3.2.4 on 2024-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0046_historicalsystemovysubor_systemovysubor'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='triedalistu',
            field=models.IntegerField(help_text='Uveďte triedu listu (1 alebo 2)', null=True, verbose_name='Trieda'),
        ),
        migrations.AddField(
            model_name='formular',
            name='typlistu',
            field=models.CharField(choices=[('doporucene', 'Doporučene'), ('obycajne', 'Obyčajne')], help_text='Zvoľté typ listu', max_length=10, null=True, verbose_name='Typ listu'),
        ),
        migrations.AddField(
            model_name='historicalformular',
            name='triedalistu',
            field=models.IntegerField(help_text='Uveďte triedu listu (1 alebo 2)', null=True, verbose_name='Trieda'),
        ),
        migrations.AddField(
            model_name='historicalformular',
            name='typlistu',
            field=models.CharField(choices=[('doporucene', 'Doporučene'), ('obycajne', 'Obyčajne')], help_text='Zvoľté typ listu', max_length=10, null=True, verbose_name='Typ listu'),
        ),
    ]
