# Generated by Django 3.2.4 on 2024-01-22 12:23

import dennik.models
from django.db import migrations, models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0047_auto_20240122_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='podaciharok',
            field=models.FileField(blank=True, help_text='Vytvorený podací hárok pre Slovenskú poštu. Pred použitím na stránke pošty ho treba <strong>skonvertovať do formátu XLS</strong>', null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, verbose_name='Podací hárok'),
        ),
        migrations.AddField(
            model_name='historicalformular',
            name='podaciharok',
            field=models.TextField(blank=True, help_text='Vytvorený podací hárok pre Slovenskú poštu. Pred použitím na stránke pošty ho treba <strong>skonvertovať do formátu XLS</strong>', max_length=100, null=True, verbose_name='Podací hárok'),
        ),
        migrations.AlterField(
            model_name='formular',
            name='vyplnene_data',
            field=models.FileField(blank=True, help_text="Vytvorený XLSX súbor s dátami použitými na vytvorenie hromadného dokumentu (vytvorený akciou 'Vyplniť formulár').", null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=dennik.models.form_file_path, verbose_name='Vyplnené dáta'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='vyplnene_data',
            field=models.TextField(blank=True, help_text="Vytvorený XLSX súbor s dátami použitými na vytvorenie hromadného dokumentu (vytvorený akciou 'Vyplniť formulár').", max_length=100, null=True, verbose_name='Vyplnené dáta'),
        ),
    ]
