# Generated by Django 3.2.4 on 2024-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0049_auto_20240417_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatovarekapitulacia',
            name='poznamka',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='platovarekapitulacia',
            name='poznamka',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Poznámka'),
        ),
    ]
