# Generated by Django 3.2.4 on 2025-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0052_auto_20250610_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='sposob',
            field=models.CharField(choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('ipostamail', 'Interná pošta + E-mail'), ('oblakmail', 'Na oblak CSČ + E-mail'), ('oblak', 'Na oblak CSČ'), ('mail', 'E-mail'), ('osobne', 'Osobne'), ('web', 'Web rozhranie')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='sposob',
            field=models.CharField(choices=[('posta', 'Pošta'), ('iposta', 'Interná pošta'), ('ipostamail', 'Interná pošta + E-mail'), ('oblakmail', 'Na oblak CSČ + E-mail'), ('oblak', 'Na oblak CSČ'), ('mail', 'E-mail'), ('osobne', 'Osobne'), ('web', 'Web rozhranie')], help_text='Zvoľte spôsob, akým bol dokument prijatý/doručený', max_length=20, null=True, verbose_name='Spôsob doručenia'),
        ),
    ]
