# Generated by Django 3.2.4 on 2025-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0053_auto_20250827_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('drobny_nákup', 'Drobný nákup'), ('dobps', 'DoBPS'), ('dopc', 'DoPC'), ('dovp', 'DoVP'), ('hromadny', 'Hromadný dokument'), ('internyprevod', 'Interný prevod'), ('iny', 'Iný'), ('list', 'List'), ('najomnazmluva', 'Nájomná zmluva'), ('najomne', 'Nájomné'), ('nepritomnost', 'Neprítomnosť'), ('objednavka', 'Objednávka'), ('odmena_oprava', 'Odmena/Oprava'), ('pokladnicnakniha', 'Pokladničná kniha'), ('posta', 'Pošta'), ('pravidelnaplatba', 'Pravidelná platba'), ('faktura', 'Prijatá faktúra'), ('pstravne', 'Príspevok na stravné'), ('rekreacia', 'Príspevok na rekreáciu a šport'), ('vobjednavka', 'Výtvarná objednávka'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('vyplacanie_vh', 'Vyplácanie výtvarných honorárov'), ('vystavenafaktura', 'Vystavená faktúra'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('zmluva', 'Zmluva')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001</em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='typdokumentu',
            field=models.CharField(blank=True, choices=[('autorskazmluva', 'Autorská zmluva'), ('drobny_nákup', 'Drobný nákup'), ('dobps', 'DoBPS'), ('dopc', 'DoPC'), ('dovp', 'DoVP'), ('hromadny', 'Hromadný dokument'), ('internyprevod', 'Interný prevod'), ('iny', 'Iný'), ('list', 'List'), ('najomnazmluva', 'Nájomná zmluva'), ('najomne', 'Nájomné'), ('nepritomnost', 'Neprítomnosť'), ('objednavka', 'Objednávka'), ('odmena_oprava', 'Odmena/Oprava'), ('pokladnicnakniha', 'Pokladničná kniha'), ('posta', 'Pošta'), ('pravidelnaplatba', 'Pravidelná platba'), ('faktura', 'Prijatá faktúra'), ('pstravne', 'Príspevok na stravné'), ('rekreacia', 'Príspevok na rekreáciu a šport'), ('vobjednavka', 'Výtvarná objednávka'), ('vyplacanie_ah', 'Vyplácanie autorských honorárov'), ('vyplacanie_vh', 'Vyplácanie výtvarných honorárov'), ('vystavenafaktura', 'Vystavená faktúra'), ('vytvarnazmluva', 'Výtvarná zmluva'), ('zmluva', 'Zmluva')], help_text='Uveďte typ dokumentu. <strong>Netreba vypĺňať, ak je v poli <em>Súvisiaca položka</em> uvedená položka databázy v tvare X-RRRR-NNN</strong>, napr. <em>DoVP-2021-001</em>.', max_length=20, null=True, verbose_name='Typ dokumentu'),
        ),
    ]
