# Generated by Django 3.2.4 on 2026-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennik', '0054_auto_20250919_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formular',
            name='typformulara',
            field=models.CharField(choices=[('vseobecny', 'Všeobecný dokument'), ('ah_zrazena', 'Potvrdenie o príjme z autorských honorárov')], help_text='Uveďte typ šablóny. Určuje, aké tokeny možno použiť:\n                <ul>\n                <li style="list-style-type:square"><em>Všeobecný dokument</em>: ľubovoľné tokeny, bez väzby na databázu</li>\n                <li style="list-style-type:square"><em>Potvrdenie o príjme z autorských honorárov</em>: v dátovom súbore zadajte len stĺpec \'za_rok\' s jedným riadkom, v ktorom je uvedený rok, za ktorý sa má potvrdenie vytvoriť.<br />Povolené tokeny:</li>\n                <li style="list-style-type:square"> Ako dátum vytvorenia dokumentu možno použiť token <em>dat_vytv</em>. Ak sa v dátovom súbore neuvedie, vloží sa aktuálny dátum.</li>\n                </ul>', max_length=20, null=True, verbose_name='Typ šablóny'),
        ),
        migrations.AlterField(
            model_name='historicalformular',
            name='typformulara',
            field=models.CharField(choices=[('vseobecny', 'Všeobecný dokument'), ('ah_zrazena', 'Potvrdenie o príjme z autorských honorárov')], help_text='Uveďte typ šablóny. Určuje, aké tokeny možno použiť:\n                <ul>\n                <li style="list-style-type:square"><em>Všeobecný dokument</em>: ľubovoľné tokeny, bez väzby na databázu</li>\n                <li style="list-style-type:square"><em>Potvrdenie o príjme z autorských honorárov</em>: v dátovom súbore zadajte len stĺpec \'za_rok\' s jedným riadkom, v ktorom je uvedený rok, za ktorý sa má potvrdenie vytvoriť.<br />Povolené tokeny:</li>\n                <li style="list-style-type:square"> Ako dátum vytvorenia dokumentu možno použiť token <em>dat_vytv</em>. Ak sa v dátovom súbore neuvedie, vloží sa aktuálny dátum.</li>\n                </ul>', max_length=20, null=True, verbose_name='Typ šablóny'),
        ),
    ]
