# Generated by Django 3.2.6 on 2021-10-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalZamestnanecDohodar',
        ),
    ]
