# Generated by Django 3.2.6 on 2021-10-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uctovnictvo', '0002_delete_historicalzamestnanecdohodar'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamestnanecdohodar',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uctovnictvo.zamestnanecdohodar_set+', to='contenttypes.contenttype'),
        ),
    ]
