# Generated by Django 3.2.6 on 2021-10-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0004_auto_20211028_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dohodar',
            fields=[
                ('zamestnanecdohodar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uctovnictvo.zamestnanecdohodar')),
            ],
            options={
                'verbose_name': 'Dohodár',
                'verbose_name_plural': 'Dohodári',
            },
            bases=('uctovnictvo.zamestnanecdohodar',),
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('zamestnanecdohodar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uctovnictvo.zamestnanecdohodar')),
                ('zapocitane_roky', models.IntegerField(blank=True, help_text='Započítané celé roky z predchádzajúcich zamestnaní. Nevyplňovať pre dohodára', null=True, verbose_name='Započítané roky')),
                ('zapocitane_dni', models.IntegerField(blank=True, help_text='Započítané dni z predchádzajúcich zamestnaní. Nevyplňovať pre dohodára', null=True, verbose_name='Započítané dni')),
                ('zamestnanie_od', models.DateField(blank=True, help_text='Zadajte dátum nástupu do zamestnanie v EnÚ. Nevyplňovať pre dohodára', null=True, verbose_name='Zamestnanie v EnÚ od')),
            ],
            options={
                'verbose_name': 'Zamestnanec',
                'verbose_name_plural': 'Zamestnanci',
            },
            bases=('uctovnictvo.zamestnanecdohodar',),
        ),
        migrations.AlterModelOptions(
            name='zamestnanecdohodar',
            options={'base_manager_name': 'objects'},
        ),
    ]
