# Generated by Django 3.2.6 on 2021-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0005_auto_20211028_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamestnanec',
            name='cislo_zamestnanca',
            field=models.CharField(max_length=50, null=True, verbose_name='Číslo zamestnanca'),
        ),
    ]
