# Generated by Django 3.2.6 on 2021-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0007_historicaldohodar_historicalzamestnanec'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatovyvymer',
            name='zamestnaniedni',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky, ak je pole 'Dátum do' vyplnené. Vtedy toto pole obsahuje počet dní neúplného posledného roku zamestnania do konca platnosti tohoto výmeru.", null=True, verbose_name='Doba zamestnania v EnÚ (dni)'),
        ),
        migrations.AddField(
            model_name='historicalplatovyvymer',
            name='zamestnanieroky',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky, ak je pole 'Dátum do' vyplnené. Vtedy toto pole obsahuje počet celých rokov zamestnania v EnÚ do konca platnosti tohoto výmeru", null=True, verbose_name='Doba zamestnania v Enú (roky)'),
        ),
        migrations.AddField(
            model_name='platovyvymer',
            name='zamestnaniedni',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky, ak je pole 'Dátum do' vyplnené. Vtedy toto pole obsahuje počet dní neúplného posledného roku zamestnania do konca platnosti tohoto výmeru.", null=True, verbose_name='Doba zamestnania v EnÚ (dni)'),
        ),
        migrations.AddField(
            model_name='platovyvymer',
            name='zamestnanieroky',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky, ak je pole 'Dátum do' vyplnené. Vtedy toto pole obsahuje počet celých rokov zamestnania v EnÚ do konca platnosti tohoto výmeru", null=True, verbose_name='Doba zamestnania v Enú (roky)'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='praxdni',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky. Ak je pole 'Dátum do' prázdne, tak toto pole obsahuje počet dní neúplného posledného roku praxe do začiatku platnosti tohoto výmeru. Ak je pole 'Dátum do' vyplnené, tak toto pole obsahuje počet dní do konca platnosti tohoto výmeru.", null=True, verbose_name='Prax (dni)'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='praxroky',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky. Ak je pole 'Dátum do' prázdne, tak toto pole obsahuje počet celých rokov praxe do začiatku platnosti tohoto výmeru. Ak je pole 'Dátum do' vyplnené, tak toto pole obsahuje počet celých rokov praxe do konca platnosti tohoto výmeru.", null=True, verbose_name='Prax (roky)'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='zamestnanie_od',
            field=models.DateField(blank=True, help_text='Dátum nástupu do zamestnania v EnÚ.', null=True, verbose_name='Zamestnanie v EnÚ od'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='zapocitane_dni',
            field=models.IntegerField(blank=True, help_text='Započítané dni z predchádzajúcich zamestnaní.', null=True, verbose_name='Započítané dni'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='zapocitane_roky',
            field=models.IntegerField(blank=True, help_text='Započítané celé roky z predchádzajúcich zamestnaní', null=True, verbose_name='Započítané roky'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='praxdni',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky. Ak je pole 'Dátum do' prázdne, tak toto pole obsahuje počet dní neúplného posledného roku praxe do začiatku platnosti tohoto výmeru. Ak je pole 'Dátum do' vyplnené, tak toto pole obsahuje počet dní do konca platnosti tohoto výmeru.", null=True, verbose_name='Prax (dni)'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='praxroky',
            field=models.IntegerField(blank=True, help_text="Pole sa vyplňuje automaticky. Ak je pole 'Dátum do' prázdne, tak toto pole obsahuje počet celých rokov praxe do začiatku platnosti tohoto výmeru. Ak je pole 'Dátum do' vyplnené, tak toto pole obsahuje počet celých rokov praxe do konca platnosti tohoto výmeru.", null=True, verbose_name='Prax (roky)'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='zamestnanie_od',
            field=models.DateField(blank=True, help_text='Dátum nástupu do zamestnania v EnÚ.', null=True, verbose_name='Zamestnanie v EnÚ od'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='zapocitane_dni',
            field=models.IntegerField(blank=True, help_text='Započítané dni z predchádzajúcich zamestnaní.', null=True, verbose_name='Započítané dni'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='zapocitane_roky',
            field=models.IntegerField(blank=True, help_text='Započítané celé roky z predchádzajúcich zamestnaní', null=True, verbose_name='Započítané roky'),
        ),
    ]
