# Generated by Django 3.2.6 on 2021-11-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0009_auto_20211109_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='zamestnanec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platovyvymer_zamestnanec', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec'),
        ),
    ]
