# Generated by Django 3.2.6 on 2021-11-10 11:16

from django.db import migrations, models
import uctovnictvo.models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0010_auto_20211109_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='datum_postup',
            field=models.DateField(blank=True, help_text="Dátum najbližšieho platového postupu. Pole sa vyplňuje automaticky, ak je pole 'Dátum do' nie je vyplnené, inak je prázdne", null=True, verbose_name='Dátum pl. postupu'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='suborvymer',
            field=models.TextField(blank=True, help_text='Vložte zoskenovaný platový výmer (vytvorený mzdovou účtárňou)', max_length=100, null=True, verbose_name='Výmer'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='datum_postup',
            field=models.DateField(blank=True, help_text="Dátum najbližšieho platového postupu. Pole sa vyplňuje automaticky, ak je pole 'Dátum do' nie je vyplnené, inak je prázdne", null=True, verbose_name='Dátum pl. postupu'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='suborvymer',
            field=models.FileField(blank=True, help_text='Vložte zoskenovaný platový výmer (vytvorený mzdovou účtárňou)', null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=uctovnictvo.models.vymer_file_path, verbose_name='Výmer'),
        ),
    ]
