# Generated by Django 3.2.6 on 2021-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0011_auto_20211110_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='datum_postup',
            field=models.DateField(blank=True, help_text="Dátum najbližšieho platového postupu. Pole sa vyplňuje automaticky, ak nie je pole 'Dátum do' vyplnené, inak je prázdne", null=True, verbose_name='Dátum pl. postupu'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='datum_postup',
            field=models.DateField(blank=True, help_text="Dátum najbližšieho platového postupu. Pole sa vyplňuje automaticky, ak nie je pole 'Dátum do' vyplnené, inak je prázdne", null=True, verbose_name='Dátum pl. postupu'),
        ),
    ]
