# Generated by Django 3.2.6 on 2021-11-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0012_auto_20211113_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvyplacaniedohod',
            name='dan_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daň z príjmu uhradená za dohodára. Vypočíta sa automaticky', max_digits=8, verbose_name='Daň dohodár'),
        ),
        migrations.AddField(
            model_name='historicalvyplacaniedohod',
            name='poistne_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Poistné uhradené za dohodára (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Poistné dohodár'),
        ),
        migrations.AddField(
            model_name='historicalvyplacaniedohod',
            name='poistne_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Poistné zamestnávateľa (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Poistné zamestnávateľ'),
        ),
        migrations.AddField(
            model_name='vyplacaniedohod',
            name='dan_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daň z príjmu uhradená za dohodára. Vypočíta sa automaticky', max_digits=8, verbose_name='Daň dohodár'),
        ),
        migrations.AddField(
            model_name='vyplacaniedohod',
            name='poistne_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Poistné uhradené za dohodára (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Poistné dohodár'),
        ),
        migrations.AddField(
            model_name='vyplacaniedohod',
            name='poistne_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Poistné zamestnávateľa (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Poistné zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odmena vyplatená dohodárovi. Vypočíta sa automaticky', max_digits=8, verbose_name='Vyplatená odmena'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odmena vyplatená dohodárovi. Vypočíta sa automaticky', max_digits=8, verbose_name='Vyplatená odmena'),
        ),
    ]
