# Generated by Django 3.2.6 on 2021-11-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0013_auto_20211123_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvyplacaniedohod',
            name='na_ucet',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odmena odoslaná dohodárovi na účet. Vypočíta sa automaticky', max_digits=8, verbose_name='Suma na účet'),
        ),
        migrations.AddField(
            model_name='vyplacaniedohod',
            name='na_ucet',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odmena odoslaná dohodárovi na účet. Vypočíta sa automaticky', max_digits=8, verbose_name='Suma na účet'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Uveďte vyplatenú sumu', max_digits=8, verbose_name='Vyplatená odmena v EUR'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Uveďte vyplatenú sumu', max_digits=8, verbose_name='Vyplatená odmena v EUR'),
        ),
    ]
