# Generated by Django 3.2.6 on 2021-11-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0014_auto_20211123_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='datum_vyplatenia',
            field=models.DateField(blank=True, help_text='Zadajte dátum vyplatenia dohody', null=True, verbose_name='Dátum vyplatenia dohody'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Uveďte vyplatenú sumu. Ak ponecháte hodnotu 0, preberie sa celková alebo mesačná odmena z príslušnej dohody', max_digits=8, verbose_name='Vyplatená odmena v EUR'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='datum_vyplatenia',
            field=models.DateField(blank=True, help_text='Zadajte dátum vyplatenia dohody', null=True, verbose_name='Dátum vyplatenia dohody'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Uveďte vyplatenú sumu. Ak ponecháte hodnotu 0, preberie sa celková alebo mesačná odmena z príslušnej dohody', max_digits=8, verbose_name='Vyplatená odmena v EUR'),
        ),
    ]
