# Generated by Django 3.2.6 on 2021-11-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0016_auto_20211124_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dovp',
            name='id_tsh',
            field=models.CharField(blank=True, help_text='Uveďte číslo, pod ktorým dohody vedie THS', max_length=100, null=True, verbose_name='Číslo pridadené THS'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='id_tsh',
            field=models.CharField(blank=True, help_text='Uveďte číslo, pod ktorým dohody vedie THS', max_length=100, null=True, verbose_name='Číslo pridadené THS'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='datum_vyplatenia',
            field=models.DateField(help_text='Zadajte dátum vyplatenia dohody', null=True, verbose_name='Dátum vyplatenia dohody'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='poistne_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody uhradené za dohodára (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Odvody dohodár'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='poistne_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody zamestnávateľa (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Odvody zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='datum_vyplatenia',
            field=models.DateField(help_text='Zadajte dátum vyplatenia dohody', null=True, verbose_name='Dátum vyplatenia dohody'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='poistne_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody uhradené za dohodára (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Odvody dohodár'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='poistne_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody zamestnávateľa (sociálne a zdravotné). Vypočíta sa automaticky', max_digits=8, verbose_name='Odvody zamestnávateľ'),
        ),
    ]
