# Generated by Django 3.2.6 on 2021-11-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0017_auto_20211126_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dohoda',
            name='vyplatene',
            field=models.CharField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky', max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='vyplatene',
            field=models.CharField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky', max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='vyplatene',
            field=models.CharField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky', max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='vyplatene',
            field=models.CharField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky', max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='dan_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daň z príjmu uhradená za dohodára', max_digits=8, verbose_name='Daň dohodár'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='datum_vyplatenia',
            field=models.DateField(help_text='Zadajte dátum odoslania podkladov na vyplatenie dohody. Ostatné polia sa vyplnia automaticky.', null=True, verbose_name='Dátum odoslania podkladov dohody'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='na_ucet',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odmena odoslaná dohodárovi na účet', max_digits=8, verbose_name='Suma na účet'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='poistne_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody uhradené za dohodára (sociálne a zdravotné)', max_digits=8, verbose_name='Odvody dohodár'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='poistne_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody zamestnávateľa (sociálne a zdravotné)', max_digits=8, verbose_name='Odvody zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='historicalvyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadajte sumu na vyplatenie. Ak ponecháte 0, doplní sa dohodnutá suma z dohody', max_digits=8, verbose_name='Vyplatená odmena'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='dan_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daň z príjmu uhradená za dohodára', max_digits=8, verbose_name='Daň dohodár'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='datum_vyplatenia',
            field=models.DateField(help_text='Zadajte dátum odoslania podkladov na vyplatenie dohody. Ostatné polia sa vyplnia automaticky.', null=True, verbose_name='Dátum odoslania podkladov dohody'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='na_ucet',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odmena odoslaná dohodárovi na účet', max_digits=8, verbose_name='Suma na účet'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='poistne_dohodar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody uhradené za dohodára (sociálne a zdravotné)', max_digits=8, verbose_name='Odvody dohodár'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='poistne_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odvody zamestnávateľa (sociálne a zdravotné)', max_digits=8, verbose_name='Odvody zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='vyplacaniedohod',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadajte sumu na vyplatenie. Ak ponecháte 0, doplní sa dohodnutá suma z dohody', max_digits=8, verbose_name='Vyplatená odmena'),
        ),
    ]
