# Generated by Django 3.2.6 on 2021-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0020_auto_20211206_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='mena',
            field=models.CharField(choices=[('EUR', 'Eur'), ('CZK', 'Czk'), ('USD', 'Usd'), ('GBP', 'Gbp')], default='EUR', max_length=3, verbose_name='Mena'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='mena',
            field=models.CharField(choices=[('EUR', 'Eur'), ('CZK', 'Czk'), ('USD', 'Usd'), ('GBP', 'Gbp')], default='EUR', max_length=3, verbose_name='Mena'),
        ),
    ]
