# Generated by Django 3.2.6 on 2021-12-17 15:18

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0022_auto_20211217_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dohoda',
            name='sken_dohody',
            field=models.FileField(blank=True, help_text='Súbor s podpísanou dohodou, treba naskenovať', null=True, upload_to=uctovnictvo.models.dohoda_upload_location, verbose_name='Skenovaná dohoda'),
        ),
        migrations.AlterField(
            model_name='dohoda',
            name='subor_dohody',
            field=models.FileField(blank=True, help_text="Súbor s textom dohody. Generuje sa akciou 'Vytvoriť subor dohody'", null=True, upload_to=uctovnictvo.models.dohoda_upload_location, verbose_name='Vygenerovaná dohoda'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='sken_dohody',
            field=models.TextField(blank=True, help_text='Súbor s podpísanou dohodou, treba naskenovať', max_length=100, null=True, verbose_name='Skenovaná dohoda'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='subor_dohody',
            field=models.TextField(blank=True, help_text="Súbor s textom dohody. Generuje sa akciou 'Vytvoriť subor dohody'", max_length=100, null=True, verbose_name='Vygenerovaná dohoda'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='sken_dohody',
            field=models.TextField(blank=True, help_text='Súbor s podpísanou dohodou, treba naskenovať', max_length=100, null=True, verbose_name='Skenovaná dohoda'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='subor_dohody',
            field=models.TextField(blank=True, help_text="Súbor s textom dohody. Generuje sa akciou 'Vytvoriť subor dohody'", max_length=100, null=True, verbose_name='Vygenerovaná dohoda'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='sken_dohody',
            field=models.TextField(blank=True, help_text='Súbor s podpísanou dohodou, treba naskenovať', max_length=100, null=True, verbose_name='Skenovaná dohoda'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='subor_dohody',
            field=models.TextField(blank=True, help_text="Súbor s textom dohody. Generuje sa akciou 'Vytvoriť subor dohody'", max_length=100, null=True, verbose_name='Vygenerovaná dohoda'),
        ),
    ]
