# Generated by Django 3.2.6 on 2022-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0025_auto_20220120_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum, kedy bola faktúra odovzdaná na sekretariát na vyplatenie', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum, kedy bola faktúra odovzdaná na sekretariát na vyplatenie', null=True, verbose_name='Dané na úhradu dňa'),
        ),
    ]
