# Generated by Django 3.2.6 on 2022-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0026_auto_20220120_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu faktúry a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu faktúry a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
    ]
