# Generated by Django 3.2.6 on 2022-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0027_auto_20220121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte príjmy ako kladné, výdavky ako záporné číslo', max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte príjmy ako kladné, výdavky ako záporné číslo', max_digits=8, null=True, verbose_name='Suma'),
        ),
    ]
