# Generated by Django 3.2.6 on 2022-01-24 09:13

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0028_auto_20220121_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='prijata_faktura',
            field=models.TextField(help_text='Súbor s faktúrou od dodávateľa', max_length=100, null=True, verbose_name='Faktúra dodádateľa'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='prijata_faktura',
            field=models.FileField(help_text='Súbor s faktúrou od dodávateľa', null=True, upload_to=uctovnictvo.models.prijata_faktura_upload_location, verbose_name='Faktúra dodádateľa'),
        ),
    ]
