# Generated by Django 3.2.6 on 2022-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0029_auto_20220124_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='dohoda',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
    ]
