# Generated by Django 3.2.6 on 2022-01-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0030_auto_20220130_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dohoda',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='stav_dohody',
            field=models.CharField(blank=True, choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpisaná')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
    ]
