# Generated by Django 3.2.6 on 2022-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0032_auto_20220130_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dohoda',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='dovp',
            name='id_tsh',
            field=models.CharField(blank=True, help_text='Uveďte číslo, pod ktorým dohody vedie THS', max_length=100, null=True, verbose_name='Číslo priradené THS'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='id_tsh',
            field=models.CharField(blank=True, help_text='Uveďte číslo, pod ktorým dohody vedie THS', max_length=100, null=True, verbose_name='Číslo priradené THS'),
        ),
    ]
