# Generated by Django 3.2.6 on 2022-02-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0034_auto_20220201_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobps',
            name='hod_mesacne',
            field=models.DecimalField(decimal_places=1, help_text='Uveďte predpokladaný priemerný počet odpracovaných hodín. Počet nesmie v priemere prekračovať 80 hodín mesačne', max_digits=8, null=True, verbose_name='Predpokl. počet hodín mesačne'),
        ),
        migrations.AlterField(
            model_name='dobps',
            name='odmena_celkom',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte celkovú odmenu za vykonanú prácu. Bude vyplatená po odovzdaní práce a výkazu', max_digits=8, null=True, verbose_name='Celková suma v EUR'),
        ),
        migrations.AlterField(
            model_name='dohoda',
            name='dohoda_odoslana',
            field=models.DateField(help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='dohoda',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='dopc',
            name='hod_mesacne',
            field=models.DecimalField(decimal_places=1, help_text='Dohodnutý počet odpracovaných hodín za mesiac, najviac 40', max_digits=8, null=True, verbose_name='Hodín za mesiac'),
        ),
        migrations.AlterField(
            model_name='dopc',
            name='odmena_mesacne',
            field=models.DecimalField(decimal_places=2, help_text='Dohodnutá mesačná odmena', max_digits=8, null=True, verbose_name='Odmena za mesiac'),
        ),
        migrations.AlterField(
            model_name='dovp',
            name='hod_celkom',
            field=models.DecimalField(decimal_places=1, help_text='Uveďte predpokladaný celkový počet odpracovaných hodín, najviac 350.', max_digits=8, null=True, verbose_name='Predpokl. počet hodín'),
        ),
        migrations.AlterField(
            model_name='dovp',
            name='odmena_celkom',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte celkovú odmenu za vykonanú prácu. Bude vyplatená po odovzdaní práce a výkazu', max_digits=8, null=True, verbose_name='Celková suma v EUR'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='dohoda_odoslana',
            field=models.DateField(help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='hod_mesacne',
            field=models.DecimalField(decimal_places=1, help_text='Uveďte predpokladaný priemerný počet odpracovaných hodín. Počet nesmie v priemere prekračovať 80 hodín mesačne', max_digits=8, null=True, verbose_name='Predpokl. počet hodín mesačne'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='odmena_celkom',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte celkovú odmenu za vykonanú prácu. Bude vyplatená po odovzdaní práce a výkazu', max_digits=8, null=True, verbose_name='Celková suma v EUR'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='dohoda_odoslana',
            field=models.DateField(help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='hod_mesacne',
            field=models.DecimalField(decimal_places=1, help_text='Dohodnutý počet odpracovaných hodín za mesiac, najviac 40', max_digits=8, null=True, verbose_name='Hodín za mesiac'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='odmena_mesacne',
            field=models.DecimalField(decimal_places=2, help_text='Dohodnutá mesačná odmena', max_digits=8, null=True, verbose_name='Odmena za mesiac'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='dohoda_odoslana',
            field=models.DateField(help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='hod_celkom',
            field=models.DecimalField(decimal_places=1, help_text='Uveďte predpokladaný celkový počet odpracovaných hodín, najviac 350.', max_digits=8, null=True, verbose_name='Predpokl. počet hodín'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='odmena_celkom',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte celkovú odmenu za vykonanú prácu. Bude vyplatená po odovzdaní práce a výkazu', max_digits=8, null=True, verbose_name='Celková suma v EUR'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť každej jeho zmene</font>.', max_length=20),
        ),
    ]
