# Generated by Django 3.2.6 on 2022-02-06 21:17

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0035_auto_20220201_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprijatafaktura',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prijatá faktúra / trvalá platba'},
        ),
        migrations.AlterModelOptions(
            name='prijatafaktura',
            options={'verbose_name': 'Prijatá faktúra / trvalá platba', 'verbose_name_plural': 'Faktúry - Prijaté faktúry / trvalé platby'},
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='prijata_faktura',
            field=models.TextField(blank=True, help_text='Súbor s faktúrou od dodávateľa', max_length=100, null=True, verbose_name='Faktúra dodádateľa'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='prijata_faktura',
            field=models.FileField(blank=True, help_text='Súbor s faktúrou od dodávateľa', null=True, upload_to=uctovnictvo.models.prijata_faktura_upload_location, verbose_name='Faktúra dodádateľa'),
        ),
    ]
