# Generated by Django 3.2.6 on 2022-02-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0036_auto_20220206_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorskyhonorar',
            name='program',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='autorskyhonorar_klasifikacia', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='dohoda',
            name='program',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='dohoda_klasifikacia', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicalautorskyhonorar',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='popis',
            field=models.CharField(blank=True, help_text='Popíšte program', max_length=100, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='program',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='platovyvymer_klasifikacia', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='program',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='prijatafaktura_klasifikacia', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='program',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='prispevoknastravne_klasifikacia', to='uctovnictvo.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='popis',
            field=models.CharField(blank=True, help_text='Popíšte program', max_length=100, null=True, verbose_name='Popis'),
        ),
    ]
