# Generated by Django 3.2.6 on 2022-02-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0037_auto_20220207_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzdroj',
            name='popis',
            field=models.CharField(blank=True, help_text='Popíšte zdroj', max_length=100, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='zdroj',
            name='popis',
            field=models.CharField(blank=True, help_text='Popíšte zdroj', max_length=100, null=True, verbose_name='Popis'),
        ),
    ]
