# Generated by Django 3.2.6 on 2022-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0038_auto_20220209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='uvazok',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadajte pracovný úväzok týždenne (najviac 37,5 hod)', max_digits=8, verbose_name='Úväzok'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='uvazok',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadajte pracovný úväzok týždenne (najviac 37,5 hod)', max_digits=8, verbose_name='Úväzok'),
        ),
    ]
