# Generated by Django 3.2.6 on 2022-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0039_auto_20220304_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatovyvymer',
            name='stav',
            field=models.CharField(choices=[('aktualny', 'Aktuálny'), ('neaktualny', 'Neaktuálny'), ('ukonceny', 'Ukončený PP')], help_text='Uveďte, v ktorom stave sa výmer nachádza.', max_length=20, null=True, verbose_name='Stav'),
        ),
        migrations.AddField(
            model_name='platovyvymer',
            name='stav',
            field=models.CharField(choices=[('aktualny', 'Aktuálny'), ('neaktualny', 'Neaktuálny'), ('ukonceny', 'Ukončený PP')], help_text='Uveďte, v ktorom stave sa výmer nachádza.', max_length=20, null=True, verbose_name='Stav'),
        ),
    ]
