# Generated by Django 3.2.6 on 2022-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0040_auto_20220304_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplatovyvymer',
            name='praxdni',
        ),
        migrations.RemoveField(
            model_name='historicalplatovyvymer',
            name='praxroky',
        ),
        migrations.RemoveField(
            model_name='historicalzamestnanec',
            name='zapocitane_dni',
        ),
        migrations.RemoveField(
            model_name='historicalzamestnanec',
            name='zapocitane_roky',
        ),
        migrations.RemoveField(
            model_name='platovyvymer',
            name='praxdni',
        ),
        migrations.RemoveField(
            model_name='platovyvymer',
            name='praxroky',
        ),
        migrations.RemoveField(
            model_name='zamestnanec',
            name='zapocitane_dni',
        ),
        migrations.RemoveField(
            model_name='zamestnanec',
            name='zapocitane_roky',
        ),
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='zamestnanie_enu_od',
            field=models.DateField(blank=True, help_text='Dátum nástupu do zamestnania v EnÚ.', null=True, verbose_name='Zamestnanie v EnÚ od'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='zamestnanie_enu_od',
            field=models.DateField(blank=True, help_text='Dátum nástupu do zamestnania v EnÚ.', null=True, verbose_name='Zamestnanie v EnÚ od'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='datum_do',
            field=models.DateField(blank=True, help_text='Nechajte prázdne alebo zadajte dátum ukončenia prac. pomeru. Ak sa pre zamestnanca vytvorí nový výmer, toto pole v predchádzajúcom výmere sa vyplní automaticky, čím sa jeho platnosť ukončí', null=True, verbose_name='Platný do'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='datum_od',
            field=models.DateField(help_text='Zadajte dátum začiatku platnosti výmeru', null=True, verbose_name='Platný od'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='datum_postup',
            field=models.DateField(blank=True, help_text="Dátum najbližšieho platového postupu. Pole sa vyplňuje automaticky, ak nie je pole 'Dátum do' vyplnené, inak je prázdne", null=True, verbose_name='Pl. postup'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='zamestnanie_od',
            field=models.DateField(blank=True, help_text='Dátum nástupu do 1. zamestnania. Preberá sa zo Softipu, kde sa vypočíta z dátumu nástupu do EnÚ a započítanej praxe', null=True, verbose_name='1. zamestnanie od'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='datum_do',
            field=models.DateField(blank=True, help_text='Nechajte prázdne alebo zadajte dátum ukončenia prac. pomeru. Ak sa pre zamestnanca vytvorí nový výmer, toto pole v predchádzajúcom výmere sa vyplní automaticky, čím sa jeho platnosť ukončí', null=True, verbose_name='Platný do'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='datum_od',
            field=models.DateField(help_text='Zadajte dátum začiatku platnosti výmeru', null=True, verbose_name='Platný od'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='datum_postup',
            field=models.DateField(blank=True, help_text="Dátum najbližšieho platového postupu. Pole sa vyplňuje automaticky, ak nie je pole 'Dátum do' vyplnené, inak je prázdne", null=True, verbose_name='Pl. postup'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='zamestnanie_od',
            field=models.DateField(blank=True, help_text='Dátum nástupu do 1. zamestnania. Preberá sa zo Softipu, kde sa vypočíta z dátumu nástupu do EnÚ a započítanej praxe', null=True, verbose_name='1. zamestnanie od'),
        ),
    ]
