# Generated by Django 3.2.6 on 2022-03-25 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0043_auto_20220324_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijatafaktura',
            name='objednavka_zmluva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prijatafaktura_faktury', to='uctovnictvo.objednavkazmluva', verbose_name='Objednávka / zmluva'),
        ),
        migrations.CreateModel(
            name='PravidelnaPlatba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa')),
                ('splatnost_datum', models.DateField(null=True, verbose_name='Dátum splatnosti')),
                ('predmet', models.CharField(max_length=100, verbose_name='Predmet')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma')),
                ('platobny_prikaz', models.FileField(blank=True, help_text="Súbor s platobným príkazom a krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Platobný príkaz pre THS-ku')),
                ('typ', models.CharField(choices=[('zaloha_el_energia', 'Záloha za el. energiu')], max_length=25, verbose_name='Typ platby')),
                ('ekoklas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('objednavka_zmluva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_faktury', to='uctovnictvo.objednavkazmluva', verbose_name='Objednávka / zmluva')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_klasifikacia', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_klasifikacia', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'Pravidelná platba',
                'verbose_name_plural': 'Pravidelné platby',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPravidelnaPlatba',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa')),
                ('splatnost_datum', models.DateField(null=True, verbose_name='Dátum splatnosti')),
                ('predmet', models.CharField(max_length=100, verbose_name='Predmet')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma')),
                ('platobny_prikaz', models.TextField(blank=True, help_text="Súbor s platobným príkazom a krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", max_length=100, null=True, verbose_name='Platobný príkaz pre THS-ku')),
                ('typ', models.CharField(choices=[('zaloha_el_energia', 'Záloha za el. energiu')], max_length=25, verbose_name='Typ platby')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ekoklas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objednavka_zmluva', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.objednavkazmluva', verbose_name='Objednávka / zmluva')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'historical Pravidelná platba',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
