# Generated by Django 3.2.6 on 2022-03-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0044_auto_20220325_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpravidelnaplatba',
            name='predmet',
        ),
        migrations.RemoveField(
            model_name='pravidelnaplatba',
            name='predmet',
        ),
    ]
