# Generated by Django 3.2.6 on 2022-03-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0045_auto_20220325_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dobps',
            options={'verbose_name': 'Dohoda o bigádnickej práci študentov', 'verbose_name_plural': 'PaM - Dohody o bigádnickej práci študentov'},
        ),
        migrations.AlterModelOptions(
            name='dohodar',
            options={'verbose_name': 'Dohodár', 'verbose_name_plural': 'PaM - Dohodári'},
        ),
        migrations.AlterModelOptions(
            name='dopc',
            options={'verbose_name': 'Dohoda o pracovnej činnosti', 'verbose_name_plural': 'PaM - Dohody o pracovnej činnosti'},
        ),
        migrations.AlterModelOptions(
            name='dovp',
            options={'verbose_name': 'Dohoda o vykonaní práce', 'verbose_name_plural': 'PaM - Dohody o vykonaní práce'},
        ),
        migrations.AlterModelOptions(
            name='platovyvymer',
            options={'verbose_name': 'Platový výmer', 'verbose_name_plural': 'PaM - Platové výmery'},
        ),
        migrations.AlterModelOptions(
            name='pravidelnaplatba',
            options={'verbose_name': 'Pravidelná platba', 'verbose_name_plural': 'Faktúry - Pravidelné platby'},
        ),
        migrations.AlterModelOptions(
            name='prispevoknastravne',
            options={'verbose_name': 'Príspevok na stravné', 'verbose_name_plural': 'PaM - Príspevky na stravné'},
        ),
        migrations.AlterModelOptions(
            name='vyplacaniedohod',
            options={'verbose_name': 'Vyplatenie dohody', 'verbose_name_plural': 'PaM - Vyplácanie dohôd'},
        ),
        migrations.AlterModelOptions(
            name='zamestnanec',
            options={'verbose_name': 'Zamestnanec', 'verbose_name_plural': 'PaM - Zamestnanci'},
        ),
    ]
