# Generated by Django 3.2.6 on 2022-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0046_auto_20220329_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodavatel',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='historicaldodavatel',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='historicaldohodar',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='zamestnanecdohodar',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
    ]
