# Generated by Django 3.2.6 on 2022-04-03 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0048_auto_20220329_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='NajomnaZmluva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('url_zmluvy', models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy')),
                ('datum_zverejnenia_CRZ', models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň).', null=True, verbose_name='Platná od')),
                ('datum_do', models.DateField(blank=True, help_text='Nechajte prázdne alebo zadajte dátum ukončenia prenájmu (ukončenia platnosti zmluvy).<br />Po zadaní dátumu sa zmaže obsah polí <em>Miestnosti</em> a <em>Výmera miestností</em>', null=True, verbose_name='Platná do')),
                ('miestnosti', models.CharField(blank=True, help_text='Zadajte číslo prenajatej miestnosti alebo zoznam čísiel prenajatých miestností oddelených čiarkou', max_length=100, null=True, verbose_name='Miestnosti')),
                ('vymery', models.CharField(blank=True, help_text='Zadajte výmeru prenajatej miestnosti alebo zoznam výmer v poradí podľa poľa <em>Miestnosti</em>', max_length=150, null=True, verbose_name='Výmera miestností')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': ('Nájomná zmluva',),
                'verbose_name_plural': 'Prenájom - Zmluvy',
            },
        ),
        migrations.CreateModel(
            name='Najomnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankovy_kontakt', models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt')),
                ('adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – ulica a číslo domu')),
                ('adresa_mesto', models.CharField(max_length=200, null=True, verbose_name='Adresa – PSČ a mesto')),
                ('adresa_stat', models.CharField(max_length=100, null=True, verbose_name='Adresa – štát')),
                ('datum_aktualizacie', models.DateField(auto_now=True, null=True, verbose_name='Dátum aktualizácie')),
                ('nazov', models.CharField(max_length=200, verbose_name='Názov')),
                ('zastupeny', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zastúpený')),
                ('s_danou', models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak sa nájomníkovi fakturuje s DPH, inak uveďte 'Nie'", max_length=3, null=True, verbose_name='Fakturované s daňou')),
            ],
            options={
                'verbose_name': 'Nájomník',
                'verbose_name_plural': 'Prenájom - Nájomníci',
            },
        ),
        migrations.CreateModel(
            name='NajomneFaktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('cislo_softip', models.CharField(blank=True, help_text='Zadajte číslo faktúry zo Softipu', max_length=25, null=True, verbose_name='Číslo Softip')),
                ('typ', models.CharField(choices=[('najomne', 'Nájomné'), ('sluzby', 'Služby spojené s prenájmom'), ('vyuctovanie', 'Vyúčtovanie služieb')], max_length=25, verbose_name='Typ faktúry')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na vybavenie dňa')),
                ('splatnost_datum', models.DateField(help_text='Zadajte dátum splatnosti 1. platby v aktuálnom roku.<br />Platby sú štvrťročné, po zadaní 1. faktúry (ak nejde o vyúčtovanie) sa doplnia záznamy pre zvyšné faktúry v roku.', null=True, verbose_name='Dátum splatnosti')),
                ('suma', models.DecimalField(decimal_places=2, help_text='Zadajte sumu bez DPH štrvrťročne. Ak sa nájmníkovi DPH účtuje, vypočíta sa z tejto sumy.', max_digits=8, null=True, verbose_name='Suma bez DPH')),
                ('platobny_prikaz', models.FileField(blank=True, help_text="Súbor s krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť krycí list pre THS'.<br />Ak treba, v prípade vyúčtovania je súčasťou aj platobný prikaz", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Krycí list pre THS-ku')),
                ('ekoklas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='najomnefaktura_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='najomnefaktura_klasifikacia', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='najomnefaktura_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='najomnefaktura_klasifikacia', to='uctovnictvo.zdroj')),
                ('zmluva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='uctovnictvo.najomnazmluva', verbose_name='Nájomná zmluva')),
            ],
            options={
                'verbose_name': 'Faktúra za prenájom',
                'verbose_name_plural': 'Prenájom - Faktúry',
            },
        ),
        migrations.AddField(
            model_name='najomnazmluva',
            name='najomnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uctovnictvo.najomnik', verbose_name='Nájomník'),
        ),
        migrations.CreateModel(
            name='HistoricalNajomnik',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bankovy_kontakt', models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt')),
                ('adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – ulica a číslo domu')),
                ('adresa_mesto', models.CharField(max_length=200, null=True, verbose_name='Adresa – PSČ a mesto')),
                ('adresa_stat', models.CharField(max_length=100, null=True, verbose_name='Adresa – štát')),
                ('datum_aktualizacie', models.DateField(blank=True, editable=False, null=True, verbose_name='Dátum aktualizácie')),
                ('nazov', models.CharField(max_length=200, verbose_name='Názov')),
                ('zastupeny', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zastúpený')),
                ('s_danou', models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak sa nájomníkovi fakturuje s DPH, inak uveďte 'Nie'", max_length=3, null=True, verbose_name='Fakturované s daňou')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Nájomník',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNajomnaZmluva',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('url_zmluvy', models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy')),
                ('datum_zverejnenia_CRZ', models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň).', null=True, verbose_name='Platná od')),
                ('datum_do', models.DateField(blank=True, help_text='Nechajte prázdne alebo zadajte dátum ukončenia prenájmu (ukončenia platnosti zmluvy).<br />Po zadaní dátumu sa zmaže obsah polí <em>Miestnosti</em> a <em>Výmera miestností</em>', null=True, verbose_name='Platná do')),
                ('miestnosti', models.CharField(blank=True, help_text='Zadajte číslo prenajatej miestnosti alebo zoznam čísiel prenajatých miestností oddelených čiarkou', max_length=100, null=True, verbose_name='Miestnosti')),
                ('vymery', models.CharField(blank=True, help_text='Zadajte výmeru prenajatej miestnosti alebo zoznam výmer v poradí podľa poľa <em>Miestnosti</em>', max_length=150, null=True, verbose_name='Výmera miestností')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('najomnik', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.najomnik', verbose_name='Nájomník')),
            ],
            options={
                'verbose_name': "historical ('Nájomná zmluva',)",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
