# Generated by Django 3.2.6 on 2022-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0049_auto_20220403_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnajomnik',
            name='s_danou',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak sa nájomníkovi fakturuje nájomné s DPH, inak uveďte 'Nie'. Služby za nájomné sa vždy fakturujú s DPH", max_length=3, null=True, verbose_name='Fakturované s daňou'),
        ),
        migrations.AlterField(
            model_name='najomnefaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte sumu bez DPH štrvrťročne.<br />Ak sa nájomníkovi účtuje DPH za nájomné, vypočíta sa z tejto sumy. DPH za služby sa účtuje vždy.', max_digits=8, null=True, verbose_name='Suma bez DPH'),
        ),
        migrations.AlterField(
            model_name='najomnik',
            name='s_danou',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak sa nájomníkovi fakturuje nájomné s DPH, inak uveďte 'Nie'. Služby za nájomné sa vždy fakturujú s DPH", max_length=3, null=True, verbose_name='Fakturované s daňou'),
        ),
    ]
