# Generated by Django 3.2.6 on 2022-05-13 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0052_auto_20220410_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankovy_kontakt', models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt')),
                ('adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – ulica a číslo domu')),
                ('adresa_mesto', models.CharField(max_length=200, null=True, verbose_name='Adresa – PSČ a mesto')),
                ('adresa_stat', models.CharField(max_length=100, null=True, verbose_name='Adresa – štát')),
                ('datum_aktualizacie', models.DateField(auto_now=True, null=True, verbose_name='Dátum aktualizácie')),
                ('nazov', models.CharField(max_length=200, verbose_name='Názov')),
            ],
            options={
                'verbose_name': 'Interný partner',
                'verbose_name_plural': 'Faktúry - Interní partneri',
            },
        ),
        migrations.CreateModel(
            name='InternyPrevod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa')),
                ('splatnost_datum', models.DateField(null=True, verbose_name='Dátum splatnosti')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma')),
                ('platobny_prikaz', models.FileField(blank=True, help_text="Súbor s platobným príkazom a krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Platobný príkaz pre THS-ku')),
                ('cinnost', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='internyprevod_klasifikacia', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internyprevod_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internyprevod_requests_created', to='uctovnictvo.internypartner', verbose_name='InternyPartner')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='internyprevod_klasifikacia', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internyprevod_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internyprevod_klasifikacia', to='uctovnictvo.zdroj')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalInternyPrevod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa')),
                ('splatnost_datum', models.DateField(null=True, verbose_name='Dátum splatnosti')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma')),
                ('platobny_prikaz', models.TextField(blank=True, help_text="Súbor s platobným príkazom a krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", max_length=100, null=True, verbose_name='Platobný príkaz pre THS-ku')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cinnost', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.internypartner', verbose_name='InternyPartner')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'historical interny prevod',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInternyPartner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bankovy_kontakt', models.CharField(blank=True, help_text='Zadajte IBAN bankového účtu.', max_length=200, null=True, verbose_name='Bankový kontakt')),
                ('adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – ulica a číslo domu')),
                ('adresa_mesto', models.CharField(max_length=200, null=True, verbose_name='Adresa – PSČ a mesto')),
                ('adresa_stat', models.CharField(max_length=100, null=True, verbose_name='Adresa – štát')),
                ('datum_aktualizacie', models.DateField(blank=True, editable=False, null=True, verbose_name='Dátum aktualizácie')),
                ('nazov', models.CharField(max_length=200, verbose_name='Názov')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Interný partner',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
