# Generated by Django 3.2.6 on 2022-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0053_historicalinternypartner_historicalinternyprevod_internypartner_internyprevod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinternyprevod',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': "historical ('Interný prevod',)"},
        ),
        migrations.AlterModelOptions(
            name='internyprevod',
            options={'verbose_name': ('Interný prevod',), 'verbose_name_plural': 'Faktúry - Interné prevody'},
        ),
        migrations.AddField(
            model_name='historicalinternyprevod',
            name='doslo_datum',
            field=models.DateField(null=True, verbose_name='Došlo dňa'),
        ),
        migrations.AddField(
            model_name='internyprevod',
            name='doslo_datum',
            field=models.DateField(null=True, verbose_name='Došlo dňa'),
        ),
    ]
