# Generated by Django 3.2.6 on 2022-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0054_auto_20220513_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinternyprevod',
            name='na_zaklade',
            field=models.CharField(max_length=100, null=True, verbose_name='Na základe'),
        ),
        migrations.AddField(
            model_name='historicalinternyprevod',
            name='predmet',
            field=models.CharField(max_length=100, null=True, verbose_name='Predmet'),
        ),
        migrations.AddField(
            model_name='internyprevod',
            name='na_zaklade',
            field=models.CharField(max_length=100, null=True, verbose_name='Na základe'),
        ),
        migrations.AddField(
            model_name='internyprevod',
            name='predmet',
            field=models.CharField(max_length=100, null=True, verbose_name='Predmet'),
        ),
    ]
