# Generated by Django 3.2.6 on 2022-05-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0056_auto_20220523_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadajte celkový príspevok zamestnávateľa (Ek. klas. 642014) ako zápornú hodnotu', max_digits=8, verbose_name='Príspevok zamestnávateľa'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadajte celkový príspevok zamestnávateľa (Ek. klas. 642014) ako zápornú hodnotu', max_digits=8, verbose_name='Príspevok zamestnávateľa'),
        ),
    ]
