# Generated by Django 3.2.6 on 2022-05-24 10:56

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0057_auto_20220524_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprispevoknastravne',
            name='po_zamestnancoch',
            field=models.TextField(help_text='Súbor s mesačným prehľadom príspevkov po zamestnancoch', max_length=100, null=True, verbose_name='Prehľad po zamestnancoch'),
        ),
        migrations.AddField(
            model_name='historicalprispevoknastravne',
            name='za_mesiac',
            field=models.CharField(choices=[('januar', 'január'), ('februar', 'február'), ('marec', 'marec'), ('april', 'apríl'), ('maj', 'máj'), ('jun', 'jún'), ('jul', 'júl'), ('august', 'august'), ('september', 'september'), ('oktober', 'október'), ('november', 'november'), ('december', 'december')], help_text='Zvoľte mesiac, za ktorý príspevok je. <br />Príspevok za január sa vypláca v decembri predchádzajúceho roku (v čísle príspevku má byť uvedený rok, v ktorom sa príspevok vyplácal).', max_length=20, null=True, verbose_name='Za mesiac'),
        ),
        migrations.AddField(
            model_name='prispevoknastravne',
            name='po_zamestnancoch',
            field=models.FileField(help_text='Súbor s mesačným prehľadom príspevkov po zamestnancoch', null=True, upload_to=uctovnictvo.models.prispevok_stravne_upload_location, verbose_name='Prehľad po zamestnancoch'),
        ),
        migrations.AddField(
            model_name='prispevoknastravne',
            name='za_mesiac',
            field=models.CharField(choices=[('januar', 'január'), ('februar', 'február'), ('marec', 'marec'), ('april', 'apríl'), ('maj', 'máj'), ('jun', 'jún'), ('jul', 'júl'), ('august', 'august'), ('september', 'september'), ('oktober', 'október'), ('november', 'november'), ('december', 'december')], help_text='Zvoľte mesiac, za ktorý príspevok je. <br />Príspevok za január sa vypláca v decembri predchádzajúceho roku (v čísle príspevku má byť uvedený rok, v ktorom sa príspevok vyplácal).', max_length=20, null=True, verbose_name='Za mesiac'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='cislo',
            field=models.CharField(max_length=50, verbose_name='Poradové číslo príspevku'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='cislo',
            field=models.CharField(max_length=50, verbose_name='Poradové číslo príspevku'),
        ),
    ]
