# Generated by Django 3.2.6 on 2022-05-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0058_auto_20220524_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='tarifny_plat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarifný plat podľa prílohy č. 5 Zákona č. 553/2003 Z. z. (Zákon o odmeňovaní niektorých zamestnancov pri výkone práce vo verejnom záujme)', max_digits=8, verbose_name='Tarifný plat'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='tarifny_plat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarifný plat podľa prílohy č. 5 Zákona č. 553/2003 Z. z. (Zákon o odmeňovaní niektorých zamestnancov pri výkone práce vo verejnom záujme)', max_digits=8, verbose_name='Tarifný plat'),
        ),
    ]
