# Generated by Django 3.2.6 on 2022-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0059_auto_20220524_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatovyvymer',
            name='cislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AddField(
            model_name='platovyvymer',
            name='cislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Číslo'),
        ),
    ]
