# Generated by Django 3.2.6 on 2022-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0060_auto_20220526_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldohodar',
            name='typ_doch',
            field=models.CharField(blank=True, choices=[('starobny', 'starobný'), ('invalidny', 'invalidný (len dohodári)'), ('invalidny30', 'invalidný 30 % (len zamestnanci)'), ('invalidny70', 'invalidný 70 % (len zamestnanci)'), ('invalidny_vysl', 'invalidný výsluhový'), ('vysluhovy', 'výsluhový po dovŕšení dôchodkového veku'), ('predcasny', 'predčasný (poberateľovi zanikne nárok na výplatu predčasného dôchodku)')], max_length=100, null=True, verbose_name='Typ dôchodku'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='typ_doch',
            field=models.CharField(blank=True, choices=[('starobny', 'starobný'), ('invalidny', 'invalidný (len dohodári)'), ('invalidny30', 'invalidný 30 % (len zamestnanci)'), ('invalidny70', 'invalidný 70 % (len zamestnanci)'), ('invalidny_vysl', 'invalidný výsluhový'), ('vysluhovy', 'výsluhový po dovŕšení dôchodkového veku'), ('predcasny', 'predčasný (poberateľovi zanikne nárok na výplatu predčasného dôchodku)')], max_length=100, null=True, verbose_name='Typ dôchodku'),
        ),
        migrations.AlterField(
            model_name='zamestnanecdohodar',
            name='typ_doch',
            field=models.CharField(blank=True, choices=[('starobny', 'starobný'), ('invalidny', 'invalidný (len dohodári)'), ('invalidny30', 'invalidný 30 % (len zamestnanci)'), ('invalidny70', 'invalidný 70 % (len zamestnanci)'), ('invalidny_vysl', 'invalidný výsluhový'), ('vysluhovy', 'výsluhový po dovŕšení dôchodkového veku'), ('predcasny', 'predčasný (poberateľovi zanikne nárok na výplatu predčasného dôchodku)')], max_length=100, null=True, verbose_name='Typ dôchodku'),
        ),
    ]
