# Generated by Django 3.2.6 on 2022-06-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0061_auto_20220603_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nepritomnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo')),
                ('nepritomnost_od', models.DateField(help_text='Prvý deň neprítomnosti', null=True, verbose_name='Neprítomnosť od')),
                ('nepritomnost_do', models.DateField(blank=True, help_text='Posledný deň neprítomnosti', null=True, verbose_name='Neprítomnosť do')),
                ('nepritomnost_typ', models.CharField(choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('neplatene', 'Neplatené voľno')], max_length=20, null=True, verbose_name='Typ neprítomnosti')),
                ('zamestnanec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nepritomnost_zamestnanec', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec')),
            ],
            options={
                'verbose_name': 'Neprítomnosť',
                'verbose_name_plural': 'PaM - Neprítomnosť',
            },
        ),
    ]
