# Generated by Django 3.2.6 on 2022-06-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0067_auto_20220610_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatbaBezPrikazu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('suma', models.DecimalField(decimal_places=2, help_text='Suma podľa výpisu zo Softipu. výdavky uveďte ako záporné číslo.', max_digits=8, null=True, verbose_name='Suma')),
                ('datum_platby', models.DateField(help_text='Dátum realizácie platby podľa výpisu zo Softipu', null=True, verbose_name='Dátum vyplatenia')),
                ('predmet', models.CharField(help_text='Stručný popis platby podľa výpisu zo Softipu.', max_length=100, null=True, verbose_name='Popis platby')),
                ('cinnost', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='platbabezprikazu_klasifikacia', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platbabezprikazu_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='platbabezprikazu_klasifikacia', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platbabezprikazu_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platbabezprikazu_klasifikacia', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'Platba bez platobného príkazu',
                'verbose_name_plural': 'Platby bez platobného príkazu',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlatbaBezPrikazu',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('suma', models.DecimalField(decimal_places=2, help_text='Suma podľa výpisu zo Softipu. výdavky uveďte ako záporné číslo.', max_digits=8, null=True, verbose_name='Suma')),
                ('datum_platby', models.DateField(help_text='Dátum realizácie platby podľa výpisu zo Softipu', null=True, verbose_name='Dátum vyplatenia')),
                ('predmet', models.CharField(help_text='Stručný popis platby podľa výpisu zo Softipu.', max_length=100, null=True, verbose_name='Popis platby')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cinnost', models.ForeignKey(blank=True, db_constraint=False, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'historical Platba bez platobného príkazu',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
