# Generated by Django 3.2.6 on 2022-06-21 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0068_historicalplatbabezprikazu_platbabezprikazu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokladna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo záznamu')),
                ('typ_transakcie', models.CharField(choices=[('dotacia', 'Dotácia'), ('vpd', 'Vystavenie VPD')], max_length=15, null=True, verbose_name='Typ transakcie')),
                ('suma', models.DecimalField(decimal_places=2, help_text='Suma. Dotácia je kladná, suma výdavku je záporná', max_digits=8, null=True, verbose_name='Suma')),
                ('datum_transakcie', models.DateField(help_text='Dátum realizácie platby', null=True, verbose_name='Dátum transakcie')),
                ('cislo_VPD', models.IntegerField(blank=True, null=True, verbose_name='Poradové číslo VPD')),
                ('datum_softip', models.DateField(blank=True, help_text='Dátum záznamu transakcie do Softipu', null=True, verbose_name='Dátum Softip')),
                ('popis', models.CharField(help_text='Stručný popis transakcie.', max_length=100, null=True, verbose_name='Popis platby.')),
                ('cinnost', models.ForeignKey(blank=True, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(blank=True, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('zakazka', models.ForeignKey(blank=True, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zamestnanec', models.ForeignKey(blank=True, help_text='Uveďte zamestnanca, ktorého výdavok bol uhradený. V prípade dotácie nechajte prázdne.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.zamestnanec')),
                ('zdroj', models.ForeignKey(blank=True, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'Záznam pokladne',
                'verbose_name_plural': 'Záznamy pokladne',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPokladna',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo záznamu')),
                ('typ_transakcie', models.CharField(choices=[('dotacia', 'Dotácia'), ('vpd', 'Vystavenie VPD')], max_length=15, null=True, verbose_name='Typ transakcie')),
                ('suma', models.DecimalField(decimal_places=2, help_text='Suma. Dotácia je kladná, suma výdavku je záporná', max_digits=8, null=True, verbose_name='Suma')),
                ('datum_transakcie', models.DateField(help_text='Dátum realizácie platby', null=True, verbose_name='Dátum transakcie')),
                ('cislo_VPD', models.IntegerField(blank=True, null=True, verbose_name='Poradové číslo VPD')),
                ('datum_softip', models.DateField(blank=True, help_text='Dátum záznamu transakcie do Softipu', null=True, verbose_name='Dátum Softip')),
                ('popis', models.CharField(help_text='Stručný popis transakcie.', max_length=100, null=True, verbose_name='Popis platby.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cinnost', models.ForeignKey(blank=True, db_constraint=False, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(blank=True, db_constraint=False, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zamestnanec', models.ForeignKey(blank=True, db_constraint=False, help_text='Uveďte zamestnanca, ktorého výdavok bol uhradený. V prípade dotácie nechajte prázdne.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanec')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, help_text='V prípade výdavku je pole povinné, v prípade dotácie nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'historical Záznam pokladne',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
