# Generated by Django 3.2.6 on 2022-06-21 18:24

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0069_historicalpokladna_pokladna'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpokladna',
            name='subor_vpd',
            field=models.TextField(blank=True, help_text="Súbor s VPD. Generuje sa akciou 'Vytvoriť VPD'", max_length=100, null=True, verbose_name='Súbor VPD'),
        ),
        migrations.AddField(
            model_name='pokladna',
            name='subor_vpd',
            field=models.FileField(blank=True, help_text="Súbor s VPD. Generuje sa akciou 'Vytvoriť VPD'", null=True, upload_to=uctovnictvo.models.pokladna_upload_location, verbose_name='Súbor VPD'),
        ),
    ]
