# Generated by Django 3.2.6 on 2022-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0071_auto_20220622_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpokladna',
            name='poznamka',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='pokladna',
            name='poznamka',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='historicalpokladna',
            name='datum_softip',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia zoznamu VPD pre THS. Vypĺňa sa automaticky akciou 'vytvoriť zoznam VPD pre THS'", null=True, verbose_name='Dátum THS'),
        ),
        migrations.AlterField(
            model_name='historicalpokladna',
            name='popis',
            field=models.CharField(help_text='Stručný popis transakcie.', max_length=30, null=True, verbose_name='Popis platby'),
        ),
        migrations.AlterField(
            model_name='historicalpokladna',
            name='typ_transakcie',
            field=models.CharField(choices=[('dotacia', 'Príjem do pokladne'), ('vpd', 'Vystavenie VPD')], max_length=15, null=True, verbose_name='Typ transakcie'),
        ),
        migrations.AlterField(
            model_name='pokladna',
            name='datum_softip',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia zoznamu VPD pre THS. Vypĺňa sa automaticky akciou 'vytvoriť zoznam VPD pre THS'", null=True, verbose_name='Dátum THS'),
        ),
        migrations.AlterField(
            model_name='pokladna',
            name='popis',
            field=models.CharField(help_text='Stručný popis transakcie.', max_length=30, null=True, verbose_name='Popis platby'),
        ),
        migrations.AlterField(
            model_name='pokladna',
            name='typ_transakcie',
            field=models.CharField(choices=[('dotacia', 'Príjem do pokladne'), ('vpd', 'Vystavenie VPD')], max_length=15, null=True, verbose_name='Typ transakcie'),
        ),
    ]
