# Generated by Django 3.2.6 on 2022-07-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0073_auto_20220624_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopc',
            name='dodatok_k',
            field=models.ForeignKey(blank=True, help_text="Ak ide len o dodatok k existujúcej DoVP, zadajte ju v tomto poli.<br />V tomto prípade sa pri ukladaní číslo tohohto dodatku zmení na číslo dohody doplnené o text 'Dodatok'. <br />Ďalší postup vytvárania dodatku je rovnaký ako v prípade DoVP", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dopc_dopc', to='uctovnictvo.dopc'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='dodatok_k',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Ak ide len o dodatok k existujúcej DoVP, zadajte ju v tomto poli.<br />V tomto prípade sa pri ukladaní číslo tohohto dodatku zmení na číslo dohody doplnené o text 'Dodatok'. <br />Ďalší postup vytvárania dodatku je rovnaký ako v prípade DoVP", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.dopc'),
        ),
    ]
