# Generated by Django 3.2.6 on 2022-07-14 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0074_auto_20220714_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialnyFond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo')),
                ('suma', models.DecimalField(decimal_places=2, help_text='Príjmy uveďte ako kladné číslo, výdavky uveďte ako záporné číslo.', max_digits=8, null=True, verbose_name='Suma')),
                ('datum_platby', models.DateField(help_text='Dátum realizácie operácie', null=True, verbose_name='Dátum operácie')),
                ('predmet', models.CharField(help_text='Stručný popis operácie.', max_length=100, null=True, verbose_name='Popis operácie')),
            ],
            options={
                'verbose_name': 'Operácia na účte sociálneho fondu',
                'verbose_name_plural': 'Sociálny fond',
            },
        ),
        migrations.AlterField(
            model_name='historicalplatbabezprikazu',
            name='suma',
            field=models.DecimalField(decimal_places=2, help_text='Suma podľa výpisu zo Softipu. Výdavky uveďte ako záporné číslo.', max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='platbabezprikazu',
            name='suma',
            field=models.DecimalField(decimal_places=2, help_text='Suma podľa výpisu zo Softipu. Výdavky uveďte ako záporné číslo.', max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.CreateModel(
            name='HistoricalSocialnyFond',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo')),
                ('suma', models.DecimalField(decimal_places=2, help_text='Príjmy uveďte ako kladné číslo, výdavky uveďte ako záporné číslo.', max_digits=8, null=True, verbose_name='Suma')),
                ('datum_platby', models.DateField(help_text='Dátum realizácie operácie', null=True, verbose_name='Dátum operácie')),
                ('predmet', models.CharField(help_text='Stručný popis operácie.', max_length=100, null=True, verbose_name='Popis operácie')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Operácia na účte sociálneho fondu',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
