# Generated by Django 3.2.6 on 2022-07-15 14:47

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0075_auto_20220714_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('neplatene', 'Neplatené voľno')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='po_zamestnancoch',
            field=models.TextField(help_text='Súbor s mesačným prehľadom príspevkov na stravné po zamestnancoch', max_length=100, null=True, verbose_name='Prehľad po zamestnancoch'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu.', max_digits=8, verbose_name='Príspevok zo soc. fondu'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.', max_digits=8, verbose_name='Príspevok zamestnávateľa'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('neplatene', 'Neplatené voľno')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='po_zamestnancoch',
            field=models.FileField(help_text='Súbor s mesačným prehľadom príspevkov na stravné po zamestnancoch', null=True, upload_to=uctovnictvo.models.prispevok_stravne_upload_location, verbose_name='Prehľad po zamestnancoch'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu.', max_digits=8, verbose_name='Príspevok zo soc. fondu'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.', max_digits=8, verbose_name='Príspevok zamestnávateľa'),
        ),
    ]
