# Generated by Django 3.2.6 on 2022-08-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0076_auto_20220715_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplatovyvymer',
            name='stav',
        ),
        migrations.RemoveField(
            model_name='platovyvymer',
            name='stav',
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='cislo',
            field=models.CharField(help_text='Uveďte číslo výmeru podľa THS', max_length=50, null=True, verbose_name='Číslo výmeru'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='cislo',
            field=models.CharField(help_text='Uveďte číslo výmeru podľa THS', max_length=50, null=True, verbose_name='Číslo výmeru'),
        ),
    ]
