# Generated by Django 3.2.6 on 2022-08-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0078_prispevoknarekreaciu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dohoda',
            name='vyplatene',
            field=models.CharField(blank=True, help_text="Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky pri vyplnení položky 'PAM Vyplatenie dohody'", max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='vyplatene',
            field=models.CharField(blank=True, help_text="Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky pri vyplnení položky 'PAM Vyplatenie dohody'", max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='vyplatene',
            field=models.CharField(blank=True, help_text="Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky pri vyplnení položky 'PAM Vyplatenie dohody'", max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='vyplatene',
            field=models.CharField(blank=True, help_text="Dátum odoslania podkladov na vyplatenie, vypĺňa sa automaticky pri vyplnení položky 'PAM Vyplatenie dohody'", max_length=200, null=True, verbose_name='Vyplatené'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu.', max_digits=8, verbose_name='Príspevok (zrážka) soc. fond'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.', max_digits=8, verbose_name='Príspevok (zrážka) zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu.', max_digits=8, verbose_name='Príspevok (zrážka) soc. fond'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.', max_digits=8, verbose_name='Príspevok (zrážka) zamestnávateľ'),
        ),
    ]
