# Generated by Django 3.2.6 on 2022-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0079_auto_20220823_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='vymeriavaci_zaklad',
            field=models.TextField(blank=True, help_text="Zadajte po riadkoch denný vymeriavací základ podľa Softipu (PaM > PAM - Personalistika a Mzdy > Mzdy > Nemocenské dávky > Denný VZ €.<br />v tvare 'RRRR/MM suma (napr. '2022/02 30,4986').<br />Údaje treba zadať len za mesiace, za ktoré má zamestnanec nárok na náhradu mzdy. Na chýbajúce údaje sa upozorní pri výpočte čerpania rozpočtu.", max_length=500, null=True, verbose_name='Denný vymeriavací základ'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='vymeriavaci_zaklad',
            field=models.TextField(blank=True, help_text="Zadajte po riadkoch denný vymeriavací základ podľa Softipu (PaM > PAM - Personalistika a Mzdy > Mzdy > Nemocenské dávky > Denný VZ €.<br />v tvare 'RRRR/MM suma (napr. '2022/02 30,4986').<br />Údaje treba zadať len za mesiace, za ktoré má zamestnanec nárok na náhradu mzdy. Na chýbajúce údaje sa upozorní pri výpočte čerpania rozpočtu.", max_length=500, null=True, verbose_name='Denný vymeriavací základ'),
        ),
    ]
