# Generated by Django 3.2.6 on 2022-08-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0082_auto_20220827_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnajomnik',
            name='s_danou',
        ),
        migrations.RemoveField(
            model_name='najomnik',
            name='s_danou',
        ),
    ]
