# Generated by Django 3.2.6 on 2022-09-07 15:35

from django.db import migrations, models
import uctovnictvo.models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0083_auto_20220827_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatbabezprikazu',
            name='subor',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Priložený súbor'),
        ),
        migrations.AddField(
            model_name='platbabezprikazu',
            name='subor',
            field=models.FileField(blank=True, null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=uctovnictvo.models.bezprikazu_file_path, verbose_name='Priložený súbor'),
        ),
    ]
