# Generated by Django 3.2.6 on 2022-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0084_auto_20220907_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatovyvymer',
            name='uvazok_denne',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='Zadajte denný pracovný úväzok. Pri plnom úväzku 7,5 hod, pri polovičnom úväzku a dohodnutých 3 prac. dňoch týždenne 6,25 hod (3*6,25= 18,75)', max_digits=8, verbose_name='Úväzok denne'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platovyvymer',
            name='uvazok_denne',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='Zadajte denný pracovný úväzok. Pri plnom úväzku 7,5 hod, pri polovičnom úväzku a dohodnutých 3 prac. dňoch týždenne 6,25 hod (3*6,25= 18,75)', max_digits=8, verbose_name='Úväzok denne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára'), ('lekardoprovod', 'Doprovod k lekárovi'), ('pzv', 'Pracovné zdrav. voľno'), ('neplatene', 'Neplatené voľno')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='uvazok',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte týždenný pracovný úväzok. Pri plnom úväzku 37,5 hod, pri polovičnom 18,75 hod', max_digits=8, verbose_name='Úväzok mesačne'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára'), ('lekardoprovod', 'Doprovod k lekárovi'), ('pzv', 'Pracovné zdrav. voľno'), ('neplatene', 'Neplatené voľno')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='uvazok',
            field=models.DecimalField(decimal_places=2, help_text='Zadajte týždenný pracovný úväzok. Pri plnom úväzku 37,5 hod, pri polovičnom 18,75 hod', max_digits=8, verbose_name='Úväzok mesačne'),
        ),
    ]
