# Generated by Django 3.2.6 on 2022-09-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0086_auto_20220916_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnepritomnost',
            name='dlzka_nepritomnosti',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dĺžka neprítomnosti v hodinách, napr '1,5'.<br /> Vypĺňa sa len v prípade návštevy lekára a doprovodu k lekárovi.<br />Ak v týchto prípadoch pole necháte prázdne, automaticky sa doplní na denný úväzok zamestnanca.", max_digits=4, null=True, verbose_name='Dĺžka nepritomnosti'),
        ),
        migrations.AddField(
            model_name='nepritomnost',
            name='dlzka_nepritomnosti',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dĺžka neprítomnosti v hodinách, napr '1,5'.<br /> Vypĺňa sa len v prípade návštevy lekára a doprovodu k lekárovi.<br />Ak v týchto prípadoch pole necháte prázdne, automaticky sa doplní na denný úväzok zamestnanca.", max_digits=4, null=True, verbose_name='Dĺžka nepritomnosti'),
        ),
    ]
