# Generated by Django 3.2.6 on 2022-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0088_auto_20220918_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='dds',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Uveďte 'Áno', ak sa zamestnanec zúčastňuje doplnkového dôchdkového sporenia", max_length=3, null=True, verbose_name='Účastník DDS'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='dds',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Uveďte 'Áno', ak sa zamestnanec zúčastňuje doplnkového dôchdkového sporenia", max_length=3, null=True, verbose_name='Účastník DDS'),
        ),
    ]
