# Generated by Django 3.2.6 on 2022-10-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0089_auto_20220920_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='dds_od',
            field=models.DateField(blank=True, help_text='Dátum, odkedy sa zamestnanec zúčastňuje doplnkového dôchodkového sporenia.', null=True, verbose_name='DDS od'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='dds_od',
            field=models.DateField(blank=True, help_text='Dátum, odkedy sa zamestnanec zúčastňuje doplnkového dôchodkového sporenia.', null=True, verbose_name='DDS od'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='dds',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Uveďte 'Áno', ak sa zamestnanec zúčastňuje doplnkového dôchodkového sporenia.<br />V tom prípade vyplňte aj položku 'DDS od'", max_length=3, null=True, verbose_name='Účastník DDS'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='dds',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Uveďte 'Áno', ak sa zamestnanec zúčastňuje doplnkového dôchodkového sporenia.<br />V tom prípade vyplňte aj položku 'DDS od'", max_length=3, null=True, verbose_name='Účastník DDS'),
        ),
    ]
