# Generated by Django 3.2.6 on 2022-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0091_auto_20221124_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzmluva',
            name='trvala_zmluva',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text="Uveďte 'Áno', ak ide o trvalú zmluvu (očakáva sa viacero faktúr), inak uveďte 'Nie'.<br /><strong>Ak zmluva nahrádza staršiu zmluvu, treba jej platnosť ukončiť vyplnením poľa 'Platná do'.</strong> ", max_length=3, verbose_name='Trvalá zmluva'),
        ),
        migrations.AlterField(
            model_name='zmluva',
            name='trvala_zmluva',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text="Uveďte 'Áno', ak ide o trvalú zmluvu (očakáva sa viacero faktúr), inak uveďte 'Nie'.<br /><strong>Ak zmluva nahrádza staršiu zmluvu, treba jej platnosť ukončiť vyplnením poľa 'Platná do'.</strong> ", max_length=3, verbose_name='Trvalá zmluva'),
        ),
    ]
