# Generated by Django 3.2.6 on 2022-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0091_auto_20221012_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopc',
            name='zmena_zdroja',
            field=models.TextField(blank=True, help_text='Zadajte po riadkoch mesiace (v rozsahu platnosti dohody), v ktorých sa zdroj alebo suma odlišujú od svojich preddefinovaných hodnôt, a to v tvare <em>RRRR/MM zdroj odmena</em>.<br />Vždy treba zadať zdroj aj odmenu, aj keď sa zmenila len jedna z týchto hodnôt.', max_length=500, null=True, verbose_name='Zmena zdroja alebo odmeny'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='zmena_zdroja',
            field=models.TextField(blank=True, help_text='Zadajte po riadkoch mesiace (v rozsahu platnosti dohody), v ktorých sa zdroj alebo suma odlišujú od svojich preddefinovaných hodnôt, a to v tvare <em>RRRR/MM zdroj odmena</em>.<br />Vždy treba zadať zdroj aj odmenu, aj keď sa zmenila len jedna z týchto hodnôt.', max_length=500, null=True, verbose_name='Zmena zdroja alebo odmeny'),
        ),
    ]
