# Generated by Django 3.2.6 on 2022-10-13 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0092_auto_20221012_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdmenaOprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo')),
                ('typ', models.CharField(choices=[('odmena', 'Odmena'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie')], help_text='Uveďte, či ide o odmenu a opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Odmena/Oprava')),
                ('suma', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška odmeny alebo opravy. Odmena je záporná, oprava môže byť kladná (t.j. zmestnancovi bola strhnutá z výplaty).', max_digits=8, null=True, verbose_name='Suma')),
                ('vyplatene_v_obdobi', models.CharField(help_text='Uveďte mesiac vyplatenia odmeny alebo mesiac, ku ktorému sa oprava vzťahuje v tvare em>MM/RRRR</em>', max_length=10, null=True, verbose_name='Vyplatené v')),
                ('zdovodnenie', models.TextField(help_text='Zadajte dôvod vyplatenia odmeny alebo vykonania opravy', max_length=500, null=True, verbose_name='Zdôvodnenie')),
                ('subor_kl', models.FileField(blank=True, help_text='Súbor s príkazom na vyplatenie odmeny a krycím listom.<br />Generuje sa akciou <em>Vytvoriť príkaz na vyplatenie odmeny</em>.', null=True, upload_to=uctovnictvo.models.odmena_upload_location, verbose_name='Príkaz a krycí list')),
                ('datum_kl', models.DateField(blank=True, help_text='Dátum odoslania krycieho listu.<br />Po zadaní sa vytvorí záznam v Denníku.', null=True, verbose_name='Dátum odoslania KL')),
                ('cinnost', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_klasifikacia', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_klasifikacia', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zamestnanec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_zamestnanec', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_klasifikacia', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'Odmena alebo oprava',
                'verbose_name_plural': 'PaM - Odmeny a opravy',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOdmenaOprava',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo')),
                ('typ', models.CharField(choices=[('odmena', 'Odmena'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie')], help_text='Uveďte, či ide o odmenu a opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Odmena/Oprava')),
                ('suma', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška odmeny alebo opravy. Odmena je záporná, oprava môže byť kladná (t.j. zmestnancovi bola strhnutá z výplaty).', max_digits=8, null=True, verbose_name='Suma')),
                ('vyplatene_v_obdobi', models.CharField(help_text='Uveďte mesiac vyplatenia odmeny alebo mesiac, ku ktorému sa oprava vzťahuje v tvare em>MM/RRRR</em>', max_length=10, null=True, verbose_name='Vyplatené v')),
                ('zdovodnenie', models.TextField(help_text='Zadajte dôvod vyplatenia odmeny alebo vykonania opravy', max_length=500, null=True, verbose_name='Zdôvodnenie')),
                ('subor_kl', models.TextField(blank=True, help_text='Súbor s príkazom na vyplatenie odmeny a krycím listom.<br />Generuje sa akciou <em>Vytvoriť príkaz na vyplatenie odmeny</em>.', max_length=100, null=True, verbose_name='Príkaz a krycí list')),
                ('datum_kl', models.DateField(blank=True, help_text='Dátum odoslania krycieho listu.<br />Po zadaní sa vytvorí záznam v Denníku.', null=True, verbose_name='Dátum odoslania KL')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cinnost', models.ForeignKey(blank=True, db_constraint=False, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zamestnanec', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'historical Odmena alebo oprava',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
