# Generated by Django 3.2.6 on 2022-10-17 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0094_auto_20221013_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrispevokNaRekreaciu',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo')),
                ('datum', models.DateField(help_text='Dátum prijatia žiadosti', null=True, verbose_name='Dátum prijatia žiadosti')),
                ('subor_ziadost', models.TextField(help_text='Súbor so žiadosťou o príspevok (doručený zamestnancom).<br />Po zadaní sa vytvorí záznam v Denníku.', max_length=100, verbose_name='Žiadosť o príspevok')),
                ('subor_vyuctovanie', models.TextField(blank=True, help_text='Súbor s vyúčtovaním príspevku (doručený mzdovou účtárňou).<br />Po zadaní sa vytvorí záznam v Denníku.', max_length=100, null=True, verbose_name='Vyúčtovanie príspevku')),
                ('prispevok', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška príspevku na rekreáciu určená mzdovou účtárňou (záporné číslo).', max_digits=8, null=True, verbose_name='Príspevok na vyplatenie')),
                ('vyplatene_v_obdobi', models.CharField(blank=True, help_text='Uveďte obdobie vyplatenia podľa vyúčtovania v tvare MM/RRRR (napr. 07/2022)', max_length=10, null=True, verbose_name='Vyplatené v')),
                ('subor_kl', models.TextField(blank=True, help_text='Súbor s krycím listom.<br />Generuje sa akciou <em>Vytvoriť krycí list</em> po vyplnení položky <em>Príspevok na vyplatenie</em>', max_length=100, null=True, verbose_name='Krycí list')),
                ('datum_kl', models.DateField(blank=True, help_text='Dátum odoslania krycieho listu.<br />Po zadaní sa vytvorí záznam v Denníku.', null=True, verbose_name='Dátum odoslania KL')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cinnost', models.ForeignKey(blank=True, db_constraint=False, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zamestnanec', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
            ],
            options={
                'verbose_name': 'historical Príspevok na rekreáciu',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
