# Generated by Django 3.2.6 on 2022-10-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0095_historicalprispevoknarekreaciu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprispevoknarekreaciu',
            name='datum_podpisu_ziadosti',
            field=models.DateField(help_text='Dátum podpisu žiadosti. <br />Po zadaní sa vytvorí záznam v denníku na odoslanie žiadosti na PaM', null=True, verbose_name='Dátum podpisu žiadosti'),
        ),
        migrations.AddField(
            model_name='prispevoknarekreaciu',
            name='datum_podpisu_ziadosti',
            field=models.DateField(help_text='Dátum podpisu žiadosti. <br />Po zadaní sa vytvorí záznam v denníku na odoslanie žiadosti na PaM', null=True, verbose_name='Dátum podpisu žiadosti'),
        ),
    ]
