# Generated by Django 3.2.6 on 2022-10-24 20:20

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0096_auto_20221019_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dohoda',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár (dôchodca) na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár (dôchodca) na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár (dôchodca) na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár (dôchodca) na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknarekreaciu',
            name='datum_podpisu_ziadosti',
            field=models.DateField(help_text='Dátum podpisu žiadosti vedením. <br />Po zadaní sa vytvorí záznam v denníku na odoslanie žiadosti na PaM', null=True, verbose_name='Dátum podpisu žiadosti'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknarekreaciu',
            name='prispevok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška príspevku na rekreáciu určená mzdovou účtárňou (záporné číslo).', max_digits=8, null=True, verbose_name='Na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknarekreaciu',
            name='subor_vyuctovanie',
            field=models.TextField(blank=True, help_text='Súbor s vyúčtovaním príspevku.<br />Po zadaní sa vytvorí záznam v Denníku.', max_length=100, null=True, verbose_name='Vyúčtovanie príspevku'),
        ),
        migrations.AlterField(
            model_name='prispevoknarekreaciu',
            name='datum_podpisu_ziadosti',
            field=models.DateField(help_text='Dátum podpisu žiadosti vedením. <br />Po zadaní sa vytvorí záznam v denníku na odoslanie žiadosti na PaM', null=True, verbose_name='Dátum podpisu žiadosti'),
        ),
        migrations.AlterField(
            model_name='prispevoknarekreaciu',
            name='prispevok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška príspevku na rekreáciu určená mzdovou účtárňou (záporné číslo).', max_digits=8, null=True, verbose_name='Na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='prispevoknarekreaciu',
            name='subor_vyuctovanie',
            field=models.FileField(blank=True, help_text='Súbor s vyúčtovaním príspevku.<br />Po zadaní sa vytvorí záznam v Denníku.', null=True, upload_to=uctovnictvo.models.rekreacia_upload_location, verbose_name='Vyúčtovanie príspevku'),
        ),
    ]
