# Generated by Django 3.2.6 on 2022-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0097_auto_20221024_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Pracovné voľno (PzV, PV, P, S, KZVS)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('pracadoma', 'Práca na doma')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Pracovné voľno (PzV, PV, P, S, KZVS)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('pracadoma', 'Práca na doma')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
    ]
