# Generated by Django 3.2.6 on 2022-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0098_auto_20221105_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dohoda',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná dohodárom'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť po každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná dohodárom'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť po každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná dohodárom'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť po každej jeho zmene</font>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='stav_dohody',
            field=models.CharField(choices=[('nova', 'Nová'), ('vytvorena', 'Vytvorená'), ('napodpis', 'Daná na podpis vedeniu EnÚ'), ('odoslana_dohodarovi', 'Daná dohodárovi na podpis'), ('podpisana_dohodarom', 'Podpísaná dohodárom'), ('dokoncena', 'Dokončená')], default='nova', help_text='Aktuálny stav dohody, <font color="#aa0000">správne nastaviť po každej jeho zmene</font>.', max_length=20),
        ),
    ]
