# Generated by Django 3.2.6 on 2022-11-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0099_auto_20221110_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrozpoctovapolozkapresun',
            old_name='zdroj',
            new_name='presun_zdroj',
        ),
        migrations.RenameField(
            model_name='rozpoctovapolozkapresun',
            old_name='zdroj',
            new_name='presun_zdroj',
        ),
        migrations.RemoveField(
            model_name='historicalrozpoctovapolozkapresun',
            name='ciel',
        ),
        migrations.RemoveField(
            model_name='rozpoctovapolozkapresun',
            name='ciel',
        ),
        migrations.AddField(
            model_name='historicalrozpoctovapolozka',
            name='za_rok',
            field=models.IntegerField(default='2022', help_text='Uveďte rok, ktorého sa dotácia týka', verbose_name='Za rok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrozpoctovapolozkadotacia',
            name='za_rok',
            field=models.IntegerField(default='2022', verbose_name='Za rok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrozpoctovapolozkapresun',
            name='presun_ciel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ak cieľová rozpočtová položka ešte neexistuje, vytvorte ju s 0-ovou výškou a požadovanou klasifikáciou.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.rozpoctovapolozka', verbose_name='Do položky'),
        ),
        migrations.AddField(
            model_name='rozpoctovapolozka',
            name='za_rok',
            field=models.IntegerField(default='2022', help_text='Uveďte rok, ktorého sa dotácia týka', verbose_name='Za rok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rozpoctovapolozkadotacia',
            name='za_rok',
            field=models.IntegerField(default='2022', verbose_name='Za rok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rozpoctovapolozkapresun',
            name='presun_ciel',
            field=models.ForeignKey(help_text='Ak cieľová rozpočtová položka ešte neexistuje, vytvorte ju s 0-ovou výškou a požadovanou klasifikáciou.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rozpoctovapolozkapresun_ciel', to='uctovnictvo.rozpoctovapolozka', verbose_name='Do položky'),
        ),
        migrations.AlterField(
            model_name='historicalrozpoctovapolozka',
            name='suma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Automaticky vypočítaná položka. Nezohľadňuje prímy a výdavky', max_digits=8, null=True, verbose_name='Aktuálny súčet dotácií a prevodov'),
        ),
        migrations.AlterField(
            model_name='historicalrozpoctovapolozkadotacia',
            name='suma',
            field=models.DecimalField(decimal_places=2, help_text='Suma sa pripočíta k zodpovedajúcej rozpočtovej položke za špecifikovaný rok. Ak tá ešte neexistuje, vytvorí sa. <br />Ak ide o zníženie rozpočtu, uveďte <strong>zápornú hodnotu</strong>"', max_digits=8, null=True, verbose_name='Výška dotácie'),
        ),
        migrations.AlterField(
            model_name='rozpoctovapolozka',
            name='suma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Automaticky vypočítaná položka. Nezohľadňuje prímy a výdavky', max_digits=8, null=True, verbose_name='Aktuálny súčet dotácií a prevodov'),
        ),
        migrations.AlterField(
            model_name='rozpoctovapolozkadotacia',
            name='suma',
            field=models.DecimalField(decimal_places=2, help_text='Suma sa pripočíta k zodpovedajúcej rozpočtovej položke za špecifikovaný rok. Ak tá ešte neexistuje, vytvorí sa. <br />Ak ide o zníženie rozpočtu, uveďte <strong>zápornú hodnotu</strong>"', max_digits=8, null=True, verbose_name='Výška dotácie'),
        ),
    ]
