# Generated by Django 3.2.6 on 2022-11-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0092_auto_20221124_2104'),
        ('uctovnictvo', '0100_auto_20221115_1541'),
    ]

    operations = [
    ]
