# Generated by Django 3.2.6 on 2022-11-29 16:48

from django.db import migrations, models
import django.db.models.deletion
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0101_merge_0092_auto_20221124_2104_0100_auto_20221115_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalodmenaoprava',
            name='subor_odmeny',
            field=models.TextField(blank=True, help_text='Súbor so zoznamom odmien.<br />Po vložení sa vytvoria záznamy jednotlivo pre všetkých odmenených. Ak sa záznam s takýmto súborom zmaže,tak sa zmažú aj všetky s ním súvisiace záznamy.', max_length=100, null=True, verbose_name='Súbor so zoznamom odmien'),
        ),
        migrations.AddField(
            model_name='odmenaoprava',
            name='subor_odmeny',
            field=models.FileField(blank=True, help_text='Súbor so zoznamom odmien.<br />Po vložení sa vytvoria záznamy jednotlivo pre všetkých odmenených. Ak sa záznam s takýmto súborom zmaže,tak sa zmažú aj všetky s ním súvisiace záznamy.', null=True, upload_to=uctovnictvo.models.odmena_upload_location, verbose_name='Súbor so zoznamom odmien'),
        ),
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='suma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Výška odmeny alebo opravy. Odmena je záporná, oprava môže byť kladná (t.j. zmestnancovi bola strhnutá z výplaty).<br /> Ak sa vkladá súbor so zoznamom odmien, uveďte súčet.', max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='typ',
            field=models.CharField(choices=[('odmena', 'Odmena'), ('odmenasubor', 'Súbor s odmenami'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie')], help_text='Uveďte, či ide o odmenu a opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Odmena/Oprava'),
        ),
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Nevypĺňa sa, ak sa vkladá súbor so zoznamom odmien', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='suma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Výška odmeny alebo opravy. Odmena je záporná, oprava môže byť kladná (t.j. zmestnancovi bola strhnutá z výplaty).<br /> Ak sa vkladá súbor so zoznamom odmien, uveďte súčet.', max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='typ',
            field=models.CharField(choices=[('odmena', 'Odmena'), ('odmenasubor', 'Súbor s odmenami'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie')], help_text='Uveďte, či ide o odmenu a opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Odmena/Oprava'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, help_text='Nevypĺňa sa, ak sa vkladá súbor so zoznamom odmien', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_zamestnanec', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec'),
        ),
    ]
