# Generated by Django 3.2.6 on 2022-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0104_auto_20221201_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma [EUR]'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma [EUR]'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma [EUR]'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='sumacm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="V prípade uvedenia sumy v cudzej mene vložte do poľa 'Suma' nulu. Pole 'Suma vypňte až bude známa skutočne uhradená suma v EUR", max_digits=8, null=True, verbose_name='Suma v cudzej mene'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma [EUR]'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma [EUR]'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma [EUR]'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='sumacm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="V prípade uvedenia sumy v cudzej mene vložte do poľa 'Suma' nulu. Pole 'Suma vypňte až bude známa skutočne uhradená suma v EUR", max_digits=8, null=True, verbose_name='Suma v cudzej mene'),
        ),
    ]
