# Generated by Django 3.2.6 on 2022-12-02 10:57

from django.db import migrations, models
import django.db.models.deletion
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0105_auto_20221201_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnepritomnost',
            name='subor_nepritomnost',
            field=models.TextField(blank=True, help_text="XLSX súbor so zoznamom neprítomností.<br />Po vložení treba akciou 'Generovať neprítomnosť' vytvoriť jednotlivé záznamy. Zmazaním tejto položky zmažú aj všetky vygenerované záznamy o neprítomnosti", max_length=100, null=True, verbose_name='Súbor so zoznamom'),
        ),
        migrations.AddField(
            model_name='nepritomnost',
            name='subor_nepritomnost',
            field=models.FileField(blank=True, help_text="XLSX súbor so zoznamom neprítomností.<br />Po vložení treba akciou 'Generovať neprítomnosť' vytvoriť jednotlivé záznamy. Zmazaním tejto položky zmažú aj všetky vygenerované záznamy o neprítomnosti", null=True, upload_to=uctovnictvo.models.nepritomnost_upload_location, verbose_name='Súbor so zoznamom'),
        ),
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='nepritomnost_od',
            field=models.DateField(blank=True, help_text='Prvý deň neprítomnosti', null=True, verbose_name='Neprítomnosť od'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='nepritomnost_od',
            field=models.DateField(blank=True, help_text='Prvý deň neprítomnosti', null=True, verbose_name='Neprítomnosť od'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nepritomnost_zamestnanec', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec'),
        ),
    ]
