# Generated by Django 3.2.6 on 2022-12-02 18:38

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0106_auto_20221202_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(blank=True, choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Pracovné voľno (PzV, PV, P, S, KZVS)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('pracadoma', 'Práca na doma'), ('skolenie', 'Školenie')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='subor_nepritomnost',
            field=models.TextField(blank=True, help_text="XLSX súbor so zoznamom neprítomností.<br />Po vložení treba akciou 'Generovať záznamy neprítomnosti' vytvoriť jednotlivé záznamy.", max_length=100, null=True, verbose_name='Súbor so zoznamom'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(blank=True, choices=[('materská', 'Materská'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Pracovné voľno (PzV, PV, P, S, KZVS)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('pracadoma', 'Práca na doma'), ('skolenie', 'Školenie')], max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='subor_nepritomnost',
            field=models.FileField(blank=True, help_text="XLSX súbor so zoznamom neprítomností.<br />Po vložení treba akciou 'Generovať záznamy neprítomnosti' vytvoriť jednotlivé záznamy.", null=True, upload_to=uctovnictvo.models.nepritomnost_upload_location, verbose_name='Súbor so zoznamom'),
        ),
    ]
