# Generated by Django 3.2.6 on 2022-12-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0108_auto_20221219_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='vyplatene_v_obdobi',
            field=models.CharField(help_text='Uveďte mesiac vyplatenia odmeny alebo mesiac, ku ktorému sa oprava vzťahuje v tvare <em>MM/RRRR</em>', max_length=10, null=True, verbose_name='Vyplatené v'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='vyplatene_v_obdobi',
            field=models.CharField(help_text='Uveďte mesiac vyplatenia odmeny alebo mesiac, ku ktorému sa oprava vzťahuje v tvare <em>MM/RRRR</em>', max_length=10, null=True, verbose_name='Vyplatené v'),
        ),
    ]
