# Generated by Django 3.2.6 on 2022-12-20 00:34

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0109_auto_20221220_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='subor_odmeny',
            field=models.TextField(blank=True, help_text='XLSX súbor so zoznamom odmien.<br />Po vygenerovaní krycieho listu sa vytvoria záznamy jednotlivo pre všetkých odmenených. Ak sa záznam s takýmto súborom zmaže,tak sa zmažú aj všetky s ním súvisiace záznamy.', max_length=100, null=True, verbose_name='Súbor so zoznamom odmien'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='subor_odmeny',
            field=models.FileField(blank=True, help_text='XLSX súbor so zoznamom odmien.<br />Po vygenerovaní krycieho listu sa vytvoria záznamy jednotlivo pre všetkých odmenených. Ak sa záznam s takýmto súborom zmaže,tak sa zmažú aj všetky s ním súvisiace záznamy.', null=True, upload_to=uctovnictvo.models.odmena_upload_location, verbose_name='Súbor so zoznamom odmien'),
        ),
    ]
