# Generated by Django 3.2.6 on 2022-12-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0110_auto_20221220_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopc',
            name='hod_mesacne',
            field=models.DecimalField(decimal_places=1, help_text='Dohodnutý počet odpracovaných hodín za mesiac, najviac 42', max_digits=8, null=True, verbose_name='Hodín za mesiac'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='hod_mesacne',
            field=models.DecimalField(decimal_places=1, help_text='Dohodnutý počet odpracovaných hodín za mesiac, najviac 42', max_digits=8, null=True, verbose_name='Hodín za mesiac'),
        ),
    ]
