# Generated by Django 3.2.6 on 2022-12-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0111_auto_20221220_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='dovp',
            name='interny_prevod',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Uveďte 'Áno', ak sa hradí interným prevodom na organizačnú zložku. Takáto položka sa nezaráta do platovej rekapitulácie", max_length=3, null=True, verbose_name='Int. prevod'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='interny_prevod',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='nie', help_text="Uveďte 'Áno', ak sa hradí interným prevodom na organizačnú zložku. Takáto položka sa nezaráta do platovej rekapitulácie", max_length=3, null=True, verbose_name='Int. prevod'),
        ),
        migrations.AlterField(
            model_name='dopc',
            name='dodatok_k',
            field=models.ForeignKey(blank=True, help_text="Ak ide len o dodatok k existujúcej DoPC, zadajte ju v tomto poli.<br />V tomto prípade sa pri ukladaní číslo tohohto dodatku zmení na číslo dohody doplnené o text 'Dodatok'. <br />Ďalší postup vytvárania dodatku je rovnaký ako v prípade DoVP", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dopc_dopc', to='uctovnictvo.dopc'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='dodatok_k',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Ak ide len o dodatok k existujúcej DoPC, zadajte ju v tomto poli.<br />V tomto prípade sa pri ukladaní číslo tohohto dodatku zmení na číslo dohody doplnené o text 'Dodatok'. <br />Ďalší postup vytvárania dodatku je rovnaký ako v prípade DoVP", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.dopc'),
        ),
    ]
