# Generated by Django 3.2.6 on 2023-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0112_auto_20221221_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='zdovodnenie',
            field=models.TextField(help_text="Zadajte dôvod vyplatenia odmeny alebo vykonania opravy. <br />Začnite 'za' a text neukončite bodkou", max_length=500, null=True, verbose_name='Zdôvodnenie'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='zdovodnenie',
            field=models.TextField(help_text="Zadajte dôvod vyplatenia odmeny alebo vykonania opravy. <br />Začnite 'za' a text neukončite bodkou", max_length=500, null=True, verbose_name='Zdôvodnenie'),
        ),
    ]
