# Generated by Django 3.2.6 on 2023-02-15 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0113_auto_20230113_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrozhodnutie',
            name='datum_vydania',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Zadajte dátum vyvydania rozhodnutia/povolenia', null=True, verbose_name='Dátum vydania'),
        ),
        migrations.AddField(
            model_name='rozhodnutie',
            name='datum_vydania',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Zadajte dátum vyvydania rozhodnutia/povolenia', null=True, verbose_name='Dátum vydania'),
        ),
    ]
