# Generated by Django 3.2.6 on 2023-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0114_auto_20230215_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='stupnica',
            field=models.CharField(choices=[('zakladna', 'Základná'), ('osobitna', 'Osobitná')], default='osobitna', help_text='Uveďte typ stupnice platovej tarify zamestnanca', max_length=10, null=True, verbose_name='Platová stupnica'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='stupnica',
            field=models.CharField(choices=[('zakladna', 'Základná'), ('osobitna', 'Osobitná')], default='osobitna', help_text='Uveďte typ stupnice platovej tarify zamestnanca', max_length=10, null=True, verbose_name='Platová stupnica'),
        ),
    ]
