# Generated by Django 3.2.6 on 2023-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0115_auto_20230220_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='dohoda',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: Miesto výkonu práce určuje zamestnanec', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: Miesto výkonu práce určuje zamestnanec', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: Miesto výkonu práce určuje zamestnanec', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: Miesto výkonu práce určuje zamestnanec', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
    ]
