# Generated by Django 3.2.6 on 2023-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0116_auto_20230223_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='dohoda',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "Zamestnanec si sám rozvrhuje pracovný čas"</li> <li>2. znenie: uviesť presnú informáciu o\xa0dňoch a\xa0časových úsekoch, v\xa0ktorých sa od zamestnanca vyžaduje vykonávanie práce, a o\xa0lehote, v\xa0ktorej má byť zamestnanec informovaný o\xa0výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín</li>/ul>)', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "Zamestnanec si sám rozvrhuje pracovný čas"</li> <li>2. znenie: uviesť presnú informáciu o\xa0dňoch a\xa0časových úsekoch, v\xa0ktorých sa od zamestnanca vyžaduje vykonávanie práce, a o\xa0lehote, v\xa0ktorej má byť zamestnanec informovaný o\xa0výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín</li>/ul>)', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "Zamestnanec si sám rozvrhuje pracovný čas"</li> <li>2. znenie: uviesť presnú informáciu o\xa0dňoch a\xa0časových úsekoch, v\xa0ktorých sa od zamestnanca vyžaduje vykonávanie práce, a o\xa0lehote, v\xa0ktorej má byť zamestnanec informovaný o\xa0výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín</li>/ul>)', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "Zamestnanec si sám rozvrhuje pracovný čas"</li> <li>2. znenie: uviesť presnú informáciu o\xa0dňoch a\xa0časových úsekoch, v\xa0ktorých sa od zamestnanca vyžaduje vykonávanie práce, a o\xa0lehote, v\xa0ktorej má byť zamestnanec informovaný o\xa0výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín</li>/ul>)', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
    ]
