# Generated by Django 3.2.6 on 2023-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0117_auto_20230223_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dovp',
            name='pomocnik',
        ),
        migrations.AddField(
            model_name='dohoda',
            name='pomocnik',
            field=models.CharField(blank=True, help_text='Uveďte zoznam rod. príslušníkov, ktorí budú pomáhať pri vykonávaní činnosti, alebo nechajte prázdne. Pre každého uveďte meno a priezvisko.', max_length=100, null=True, verbose_name='Pomoc rod. príslušníkov'),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='pomocnik',
            field=models.CharField(blank=True, help_text='Uveďte zoznam rod. príslušníkov, ktorí budú pomáhať pri vykonávaní činnosti, alebo nechajte prázdne. Pre každého uveďte meno a priezvisko.', max_length=100, null=True, verbose_name='Pomoc rod. príslušníkov'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='pomocnik',
            field=models.CharField(blank=True, help_text='Uveďte zoznam rod. príslušníkov, ktorí budú pomáhať pri vykonávaní činnosti, alebo nechajte prázdne. Pre každého uveďte meno a priezvisko.', max_length=100, null=True, verbose_name='Pomoc rod. príslušníkov'),
        ),
        migrations.AlterField(
            model_name='dohoda',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: <strong>Miesto výkonu práce určuje zamestnanec</strong>', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
        migrations.AlterField(
            model_name='dohoda',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "<strong>Zamestnanec si sám rozvrhuje pracovný čas</strong></li> <li>2. znenie: uviesť presnú informáciu o <ul><li>a) dňoch a časových úsekoch, v ktorých môže od zamestnanca vyžadovať vykonávanie práce,</li> <li>b) lehote, v ktorej má byť zamestnanec informovaný o výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín.</li> </ul> </li></ul>', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: <strong>Miesto výkonu práce určuje zamestnanec</strong>', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "<strong>Zamestnanec si sám rozvrhuje pracovný čas</strong></li> <li>2. znenie: uviesť presnú informáciu o <ul><li>a) dňoch a časových úsekoch, v ktorých môže od zamestnanca vyžadovať vykonávanie práce,</li> <li>b) lehote, v ktorej má byť zamestnanec informovaný o výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín.</li> </ul> </li></ul>', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: <strong>Miesto výkonu práce určuje zamestnanec</strong>', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "<strong>Zamestnanec si sám rozvrhuje pracovný čas</strong></li> <li>2. znenie: uviesť presnú informáciu o <ul><li>a) dňoch a časových úsekoch, v ktorých môže od zamestnanca vyžadovať vykonávanie práce,</li> <li>b) lehote, v ktorej má byť zamestnanec informovaný o výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín.</li> </ul> </li></ul>', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='miesto_vykonu',
            field=models.CharField(help_text='Miesto výkonu práce: presná adresa alebo presné adresy, prípadne ak je viac adries, určenie hlavného miesta výkonu práce, <br />alebo znenie: <strong>Miesto výkonu práce určuje zamestnanec</strong>', max_length=200, null=True, verbose_name='Miesto výkonu'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='pracovny_cas',
            field=models.CharField(help_text='Uviesť jednu z možností:<ul><li>1. znenie: "<strong>Zamestnanec si sám rozvrhuje pracovný čas</strong></li> <li>2. znenie: uviesť presnú informáciu o <ul><li>a) dňoch a časových úsekoch, v ktorých môže od zamestnanca vyžadovať vykonávanie práce,</li> <li>b) lehote, v ktorej má byť zamestnanec informovaný o výkone práce pred jej začiatkom, ktorá nesmie byť kratšia ako 24 hodín.</li> </ul> </li></ul>', max_length=200, null=True, verbose_name='Pracovný čas'),
        ),
    ]
