# Generated by Django 3.2.4 on 2023-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0119_auto_20230224_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzmluva',
            name='nase_cislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Naše číslo'),
        ),
        migrations.AddField(
            model_name='zmluva',
            name='nase_cislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Naše číslo'),
        ),
    ]
