# Generated by Django 3.2.4 on 2023-06-11 19:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0120_auto_20230526_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinternyprevod',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AddField(
            model_name='historicalpravidelnaplatba',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AddField(
            model_name='historicalpravidelnaplatba',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AddField(
            model_name='historicalpravidelnaplatba',
            name='zakazka2',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Druhá zákazka v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky 2'),
        ),
        migrations.AddField(
            model_name='historicalpravidelnaplatba',
            name='zdroj2',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Druhý zdroj v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj', verbose_name='Zdroj 2'),
        ),
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='zakazka2',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Druhá zákazka v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky 2'),
        ),
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='zdroj2',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Druhý zdroj v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj', verbose_name='Zdroj 2'),
        ),
        migrations.AddField(
            model_name='internyprevod',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AddField(
            model_name='pravidelnaplatba',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AddField(
            model_name='pravidelnaplatba',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AddField(
            model_name='pravidelnaplatba',
            name='zakazka2',
            field=models.ForeignKey(blank=True, help_text='Druhá zákazka v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_klasifikacia2', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky 2'),
        ),
        migrations.AddField(
            model_name='pravidelnaplatba',
            name='zdroj2',
            field=models.ForeignKey(blank=True, help_text='Druhý zdroj v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_klasifikacia2', to='uctovnictvo.zdroj', verbose_name='Zdroj 2'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='zakazka2',
            field=models.ForeignKey(blank=True, help_text='Druhá zákazka v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prijatafaktura_klasifikacia2', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky 2'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='zdroj2',
            field=models.ForeignKey(blank=True, help_text='Druhý zdroj v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prijatafaktura_klasifikacia2', to='uctovnictvo.zdroj', verbose_name='Zdroj 2'),
        ),
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma (EUR, s DPH)'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma (EUR, s DPH)'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma (EUR, s DPH)'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='sumacm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="V prípade uvedenia sumy v cudzej mene vložte do poľa 'Suma' nulu. Pole 'Suma vypňte až bude známa skutočne uhradená suma v EUR", max_digits=8, null=True, verbose_name='Suma v cudzej mene (s DPH)'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma (EUR, s DPH)'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma (EUR, s DPH)'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma (EUR, s DPH)'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='sumacm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="V prípade uvedenia sumy v cudzej mene vložte do poľa 'Suma' nulu. Pole 'Suma vypňte až bude známa skutočne uhradená suma v EUR", max_digits=8, null=True, verbose_name='Suma v cudzej mene (s DPH)'),
        ),
    ]
