# Generated by Django 3.2.4 on 2023-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0121_auto_20230611_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], default='0', help_text='Uveďte sadzbu DPH (20 % v prípade výkupu elektriny, inak 0 %)', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma)'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], default='0', help_text='Uveďte sadzbu DPH (20 % v prípade výkupu elektriny, inak 0 %)', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma)'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], default='0', help_text='Uveďte sadzbu DPH (20 % v prípade výkupu elektriny, inak 0 %)', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma)'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], default='0', help_text='Uveďte sadzbu DPH (20 % v prípade výkupu elektriny, inak 0 %)', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma)'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], default='0', help_text='Uveďte sadzbu DPH (20 % v prípade výkupu elektriny, inak 0 %)', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma)'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], default='0', help_text='Uveďte sadzbu DPH (20 % v prípade výkupu elektriny, inak 0 %)', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma)'),
        ),
    ]
