# Generated by Django 3.2.4 on 2023-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0124_auto_20230713_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma'),
        ),
    ]
