# Generated by Django 3.2.4 on 2023-07-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0126_auto_20230716_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='historicalpokladna',
            name='popis',
            field=models.CharField(help_text='Stručný popis transakcie. Ak sa dá, v prípade PPD uveďte číslo súvisiaveho VPD', max_length=60, null=True, verbose_name='Popis platby'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='pokladna',
            name='popis',
            field=models.CharField(help_text='Stručný popis transakcie. Ak sa dá, v prípade PPD uveďte číslo súvisiaveho VPD', max_length=60, null=True, verbose_name='Popis platby'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='sadzbadph',
            field=models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
    ]
