# Generated by Django 3.2.4 on 2023-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0128_auto_20231009_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 5 poľami oddelenými bodkočiarkou v poradí: <b>názov položky</b>; <b>merná jednotka</b> - ks, kg, l, m, m2, m3; <b>množstvo</b>; <b>cena za jednotku bez DPH; CPV kód</b>, napr. <em>Euroobal A4;bal;10;7,50;30193300-1</em>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarlou, za ktorou nasleduje CPV kód, napr. <em>Objednávame tovar podľa priloženej ponuky / priloženého zoznamu; 45321000-3</em> (súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em>).</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 5 poľami oddelenými bodkočiarkou v poradí: <b>názov položky</b>; <b>merná jednotka</b> - ks, kg, l, m, m2, m3; <b>množstvo</b>; <b>cena za jednotku bez DPH; CPV kód</b>, napr. <em>Euroobal A4;bal;10;7,50;30193300-1</em>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarlou, za ktorou nasleduje CPV kód, napr. <em>Objednávame tovar podľa priloženej ponuky / priloženého zoznamu; 45321000-3</em> (súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em>).</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
    ]
