# Generated by Django 3.2.4 on 2023-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0129_auto_20231029_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné')], help_text="Zvoľte typ zoznamu.<br/>Položku uložte a následne príslušnou akciou 'Generovať zoznam príspevkov/zrážok' vytvorte súbor 'Prehľad po zamestnancoch' za nasledujúci mesiac.", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
        migrations.AddField(
            model_name='prispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné')], help_text="Zvoľte typ zoznamu.<br/>Položku uložte a následne príslušnou akciou 'Generovať zoznam príspevkov/zrážok' vytvorte súbor 'Prehľad po zamestnancoch' za nasledujúci mesiac.", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu. <br /> Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, verbose_name='Príspevok (zrážka) soc. fond'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br /> Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, verbose_name='Príspevok (zrážka) zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu. <br /> Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, verbose_name='Príspevok (zrážka) soc. fond'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br /> Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, verbose_name='Príspevok (zrážka) zamestnávateľ'),
        ),
    ]
