# Generated by Django 3.2.4 on 2023-11-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0129_auto_20231029_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='typ',
            field=models.CharField(choices=[('odmena', 'Odmena'), ('odmenasubor', 'XLSX súbor s odmenami'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie'), ('odstupne', 'Odstupné'), ('odchodne', 'Odchodné'), ('dovolenka', 'Náhrada mzdy - dovolenka')], help_text='Uveďte, či ide o odmenu, súbor s odmenami alebo opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Typ záznamu'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='typ',
            field=models.CharField(choices=[('odmena', 'Odmena'), ('odmenasubor', 'XLSX súbor s odmenami'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie'), ('odstupne', 'Odstupné'), ('odchodne', 'Odchodné'), ('dovolenka', 'Náhrada mzdy - dovolenka')], help_text='Uveďte, či ide o odmenu, súbor s odmenami alebo opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Typ záznamu'),
        ),
    ]
