# Generated by Django 3.2.4 on 2023-11-01 20:47

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0130_auto_20231101_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='po_zamestnancoch',
            field=models.TextField(blank=True, help_text='Súbor s mesačným prehľadom príspevkov na stravné po zamestnancoch', max_length=100, null=True, verbose_name='Prehľad po zamestnancoch'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='po_zamestnancoch',
            field=models.FileField(blank=True, help_text='Súbor s mesačným prehľadom príspevkov na stravné po zamestnancoch', null=True, upload_to=uctovnictvo.models.prispevok_stravne_upload_location, verbose_name='Prehľad po zamestnancoch'),
        ),
    ]
