# Generated by Django 3.2.4 on 2023-11-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0132_auto_20231104_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='bez_stravneho_od',
            field=models.DateField(blank=True, help_text='Dátum, odkedy sa zamestnanec z dôvodu dlhej neprítomnosti (materská, PN) <strong>nemá evidovať</strong> za účelom príspevku na stravné<br\xa0/>Zadať príp. zmazať pred výpočtom príspevku za nasledujúci mesiac.<br />Zadávajte vždy len 1. deň v mesiaci.', null=True, verbose_name='Bez stravného od'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='bez_stravneho_od',
            field=models.DateField(blank=True, help_text='Dátum, odkedy sa zamestnanec z dôvodu dlhej neprítomnosti (materská, PN) <strong>nemá evidovať</strong> za účelom príspevku na stravné<br\xa0/>Zadať príp. zmazať pred výpočtom príspevku za nasledujúci mesiac.<br />Zadávajte vždy len 1. deň v mesiaci.', null=True, verbose_name='Bez stravného od'),
        ),
    ]
