# Generated by Django 3.2.4 on 2023-12-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0130_auto_20231112_1017'),
        ('uctovnictvo', '0133_auto_20231109_1125'),
    ]

    operations = [
    ]
