# Generated by Django 3.2.4 on 2023-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0134_merge_0130_auto_20231112_1017_0133_auto_20231109_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprispevoknastravne',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Príspevok na stravné / zrážka za stravné'},
        ),
        migrations.AlterModelOptions(
            name='prispevoknastravne',
            options={'verbose_name': 'Príspevok na stravné / zrážka za stravné', 'verbose_name_plural': 'PaM - Stravné'},
        ),
        migrations.RemoveField(
            model_name='historicalzamestnanec',
            name='bez_stravneho_od',
        ),
        migrations.RemoveField(
            model_name='zamestnanec',
            name='bez_stravneho_od',
        ),
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='bez_stravneho',
            field=models.TextField(blank=True, help_text='Zadajte obdobie, v ktorom sa zamestnancovi z dôvodu dlhej neprítomnosti (materská, PN, NV) <strong>nemá vyplácať</strong> príspevok na stravné. <br />Obdobie zadajte ako <em>prvy_den_v_prvom_mesiaci, posledny_den_v_poslednom_mesiaci</em>, napr. <em>1.2.2022, 31.8.2022</em>. Ak druhý dátum nie je známy, tak ho neuveďte.<br />Prvý dátum treba zadať pred výpočtom príspevku za mesiac, v ktorom sa príspevok nemá vyplatiť.<br />Príspevok sa v danom mesiaci nevyplatí len vtedy, ak neprítomnosť zadaná v PaM - Neprítomnosť trvá celý tento mesiac (napr. neukončená PN, MD alebo NV na celý mesiac.)', null=True, verbose_name='Bez stravného od / do'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='bez_stravneho',
            field=models.TextField(blank=True, help_text='Zadajte obdobie, v ktorom sa zamestnancovi z dôvodu dlhej neprítomnosti (materská, PN, NV) <strong>nemá vyplácať</strong> príspevok na stravné. <br />Obdobie zadajte ako <em>prvy_den_v_prvom_mesiaci, posledny_den_v_poslednom_mesiaci</em>, napr. <em>1.2.2022, 31.8.2022</em>. Ak druhý dátum nie je známy, tak ho neuveďte.<br />Prvý dátum treba zadať pred výpočtom príspevku za mesiac, v ktorom sa príspevok nemá vyplatiť.<br />Príspevok sa v danom mesiaci nevyplatí len vtedy, ak neprítomnosť zadaná v PaM - Neprítomnosť trvá celý tento mesiac (napr. neukončená PN, MD alebo NV na celý mesiac.)', null=True, verbose_name='Bez stravného od / do'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu. <br /> Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Príspevok (zrážka) soc. fond'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Príspevok (zrážka) zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné')], help_text="Zvoľte typ zoznamu.<br/>Položku uložte a následne akciou 'Generovať zoznam príspevkov/zrážok' vytvorte súbor so zoznamom.", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='za_mesiac',
            field=models.CharField(choices=[('januar', 'január'), ('februar', 'február'), ('marec', 'marec'), ('april', 'apríl'), ('maj', 'máj'), ('jun', 'jún'), ('jul', 'júl'), ('august', 'august'), ('september', 'september'), ('oktober', 'október'), ('november', 'november'), ('december', 'december')], help_text="Zadajte uplynulý kalendárny mesiac.<br /> <strong>Príspevok na stravné</strong> sa vypočíta na nasledujúci mesiac. Napr. ak koncom mája chcete vytvoriť zoznam príspevkov na jún, zvoľte 'máj'. Vytvorí sa zoznam na jún, v zozname aj bude uvedené 'na jún'.<br /><strong>Zrážka za stravné</strong> sa vypočíta za uplynulý mesiac.", max_length=20, null=True, verbose_name='Mesiac'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok zo sociálneho fondu (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Vytvorením Príspevku na stravné sa automaticky vytvorí položka sociálneho fondu. <br /> Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Príspevok (zrážka) soc. fond'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok zamestnávateľa (Ek. klas. 642014) na stravné.<br />Ak ide o vyplatenie zamestnancovi, uveďte zápornú hodnotu, ak ide o zrážku, tak kladnú hodnotu.<br />Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Príspevok (zrážka) zamestnávateľ'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné')], help_text="Zvoľte typ zoznamu.<br/>Položku uložte a následne akciou 'Generovať zoznam príspevkov/zrážok' vytvorte súbor so zoznamom.", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='za_mesiac',
            field=models.CharField(choices=[('januar', 'január'), ('februar', 'február'), ('marec', 'marec'), ('april', 'apríl'), ('maj', 'máj'), ('jun', 'jún'), ('jul', 'júl'), ('august', 'august'), ('september', 'september'), ('oktober', 'október'), ('november', 'november'), ('december', 'december')], help_text="Zadajte uplynulý kalendárny mesiac.<br /> <strong>Príspevok na stravné</strong> sa vypočíta na nasledujúci mesiac. Napr. ak koncom mája chcete vytvoriť zoznam príspevkov na jún, zvoľte 'máj'. Vytvorí sa zoznam na jún, v zozname aj bude uvedené 'na jún'.<br /><strong>Zrážka za stravné</strong> sa vypočíta za uplynulý mesiac.", max_length=20, null=True, verbose_name='Mesiac'),
        ),
    ]
