# Generated by Django 3.2.4 on 2023-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0135_auto_20231201_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='bez_stravneho',
            field=models.TextField(blank=True, help_text='Zadajte obdobie, v ktorom sa zamestnancovi z dôvodu dlhej neprítomnosti (materská, PN, NV) <strong>nemá vyplácať</strong> príspevok na stravné. <br />Obdobie zadajte ako <em>prvy_den_v_prvom_mesiaci, posledny_den_v_poslednom_mesiaci</em>, napr. <em>1.2.2022, 31.8.2022</em>. Ak druhý dátum nie je známy, tak ho neuveďte.<br />Prvý dátum treba zadať pred výpočtom príspevku za mesiac, v ktorom sa príspevok nemá vyplatiť.<br />Príspevok sa v danom mesiaci nevyplatí len vtedy, ak neprítomnosť zadaná v PaM - Neprítomnosť trvá celý tento mesiac (napr. neukončená PN, MD alebo NV na celý mesiac. <br />Za dátumami možno zadať poznámku, v ktorej sa nenachádza dátum.)', null=True, verbose_name='Bez stravného od / do'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='bez_stravneho',
            field=models.TextField(blank=True, help_text='Zadajte obdobie, v ktorom sa zamestnancovi z dôvodu dlhej neprítomnosti (materská, PN, NV) <strong>nemá vyplácať</strong> príspevok na stravné. <br />Obdobie zadajte ako <em>prvy_den_v_prvom_mesiaci, posledny_den_v_poslednom_mesiaci</em>, napr. <em>1.2.2022, 31.8.2022</em>. Ak druhý dátum nie je známy, tak ho neuveďte.<br />Prvý dátum treba zadať pred výpočtom príspevku za mesiac, v ktorom sa príspevok nemá vyplatiť.<br />Príspevok sa v danom mesiaci nevyplatí len vtedy, ak neprítomnosť zadaná v PaM - Neprítomnosť trvá celý tento mesiac (napr. neukončená PN, MD alebo NV na celý mesiac. <br />Za dátumami možno zadať poznámku, v ktorej sa nenachádza dátum.)', null=True, verbose_name='Bez stravného od / do'),
        ),
    ]
