# Generated by Django 3.2.4 on 2023-12-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0137_auto_20231205_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjednavka',
            name='predpokladana_cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH, ak už nie je zadaná v poli <em>Objednané položky</em>. <br />Vo vygenerovanej objednávke sa zoberie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='predpokladana_cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH, ak už nie je zadaná v poli <em>Objednané položky</em>. <br />Vo vygenerovanej objednávke sa zoberie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: s 5 poľami oddelenými bodkočiarkou v poradí: <b>názov položky</b>; <b>merná jednotka</b> - ks, kg, l, m, m2, m3; <b>množstvo</b>; <b>cena za jednotku bez DPH; CPV kód</b>, napr. <strong>Euroobal A4; bal; 10; 7,50; 30193300-1</strong>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa priloženej ponuky / priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: s 5 poľami oddelenými bodkočiarkou v poradí: <b>názov položky</b>; <b>merná jednotka</b> - ks, kg, l, m, m2, m3; <b>množstvo</b>; <b>cena za jednotku bez DPH; CPV kód</b>, napr. <strong>Euroobal A4; bal; 10; 7,50; 30193300-1</strong>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa priloženej ponuky / priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
    ]
