# Generated by Django 3.2.4 on 2023-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0138_auto_20231206_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjednavka',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania objednávky. Po zadaní dátumu sa vytvorí záznam v denníku prijateh a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania objednávky. Po zadaní dátumu sa vytvorí záznam v denníku prijateh a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
    ]
