# Generated by Django 3.2.4 on 2023-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0139_auto_20231208_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnepritomnost',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania tabuľky so zoznamom neprítomností. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AddField(
            model_name='nepritomnost',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania tabuľky so zoznamom neprítomností. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania objednávky. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania objednávky. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
    ]
