# Generated by Django 3.2.4 on 2023-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0140_auto_20231209_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopc',
            name='zmena_zdroja',
            field=models.TextField(blank=True, help_text='Zadajte po riadkoch mesiace (v rozsahu platnosti dohody), v ktorých sa zdroj, zákazka alebo suma odlišujú od svojich preddefinovaných hodnôt, a to v tvare <em>RRRR/MM;zdroj;zákazka;odmena</em>.<br />Vždy treba zadať všetky tri položky, aj keď sa zmenila len jedna z týchto hodnôt.<br />Obvyklé hodnoty pre pár <strong>zdroj;zákazka</strong> sú: <strong>42;42002200</strong>, <strong>111;11010001</strong> a <strong>111;11070002</strong>.', max_length=500, null=True, verbose_name='Zmena zdroja alebo odmeny'),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='zmena_zdroja',
            field=models.TextField(blank=True, help_text='Zadajte po riadkoch mesiace (v rozsahu platnosti dohody), v ktorých sa zdroj, zákazka alebo suma odlišujú od svojich preddefinovaných hodnôt, a to v tvare <em>RRRR/MM;zdroj;zákazka;odmena</em>.<br />Vždy treba zadať všetky tri položky, aj keď sa zmenila len jedna z týchto hodnôt.<br />Obvyklé hodnoty pre pár <strong>zdroj;zákazka</strong> sú: <strong>42;42002200</strong>, <strong>111;11010001</strong> a <strong>111;11070002</strong>.', max_length=500, null=True, verbose_name='Zmena zdroja alebo odmeny'),
        ),
    ]
