# Generated by Django 3.2.4 on 2023-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0141_auto_20231211_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprispevoknastravne',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania tabuľky so zoznamom. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AddField(
            model_name='prispevoknastravne',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania tabuľky so zoznamom. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
    ]
