# Generated by Django 3.2.4 on 2023-12-20 14:20

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0145_auto_20231220_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='subor_odmeny',
            field=models.TextField(blank=True, help_text='XLSX súbor so zoznamom odmien.<br />Po vygenerovaní krycieho listu sa vytvoria záznamy jednotlivo pre všetkých odmenených. Ak sa záznam s takýmto súborom zmaže,tak sa zmažú aj všetky s ním súvisiace záznamy. <br />Dôvod (napr. udelenie odmeny P sav) prikladať ako PDF súbor.', max_length=100, null=True, verbose_name='Súbor so zoznamom odmien alebo dôvodom'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='subor_odmeny',
            field=models.FileField(blank=True, help_text='XLSX súbor so zoznamom odmien.<br />Po vygenerovaní krycieho listu sa vytvoria záznamy jednotlivo pre všetkých odmenených. Ak sa záznam s takýmto súborom zmaže,tak sa zmažú aj všetky s ním súvisiace záznamy. <br />Dôvod (napr. udelenie odmeny P sav) prikladať ako PDF súbor.', null=True, upload_to=uctovnictvo.models.odmena_upload_location, verbose_name='Súbor so zoznamom odmien alebo dôvodom'),
        ),
    ]
