# Generated by Django 3.2.4 on 2023-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0146_auto_20231220_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinternyprevod',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AddField(
            model_name='historicalpravidelnaplatba',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AddField(
            model_name='internyprevod',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AddField(
            model_name='pravidelnaplatba',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa'),
        ),
    ]
