# Generated by Django 3.2.4 on 2024-01-12 11:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0147_auto_20231222_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='dcislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo faktúry dodávateľa'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='dcislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo faktúry dodávateľa'),
        ),
        migrations.CreateModel(
            name='VystavenaFaktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('podiel2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa')),
                ('uhradene_dna', models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa')),
                ('splatnost_datum', models.DateField(null=True, verbose_name='Dátum splatnosti')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma')),
                ('sadzbadph', models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH')),
                ('platobny_prikaz', models.FileField(blank=True, help_text="Súbor s platobným príkazom a krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Platobný príkaz pre THS-ku')),
                ('dcislo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo faktúry odberateĺa')),
                ('predmet', models.CharField(max_length=100, verbose_name='Predmet')),
                ('doslo_datum', models.DateField(null=True, verbose_name='Došlo dňa')),
                ('na_zaklade', models.FileField(blank=True, help_text='Dokument (faktúra), na základe ktorého sa faktúra vystavuje.', null=True, upload_to=uctovnictvo.models.vystavena_faktura_upload_location, verbose_name='Na základe')),
                ('cinnost', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('objednavka_zmluva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_faktury', to='uctovnictvo.objednavkazmluva', verbose_name='Objednávka / zmluva')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zakazka2', models.ForeignKey(blank=True, help_text='Druhá zákazka v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia2', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky 2')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia', to='uctovnictvo.zdroj')),
                ('zdroj2', models.ForeignKey(blank=True, help_text='Druhý zdroj v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia2', to='uctovnictvo.zdroj', verbose_name='Zdroj 2')),
            ],
            options={
                'verbose_name': 'Vystavená faktúra',
                'verbose_name_plural': 'Faktúry - Vystavené faktúry',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVystavenaFaktura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('podiel2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie THS. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa')),
                ('uhradene_dna', models.DateField(blank=True, help_text='Zadajte dátum uhradenia učtárňou (podľa výpisu zo Softipu a tak podobne', null=True, verbose_name='Uhradené dňa')),
                ('splatnost_datum', models.DateField(null=True, verbose_name='Dátum splatnosti')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Suma')),
                ('sadzbadph', models.CharField(choices=[('20', '20 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH.', max_length=10, null=True, verbose_name='Sadzba DPH')),
                ('platobny_prikaz', models.TextField(blank=True, help_text="Súbor s platobným príkazom a krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", max_length=100, null=True, verbose_name='Platobný príkaz pre THS-ku')),
                ('dcislo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo faktúry odberateĺa')),
                ('predmet', models.CharField(max_length=100, verbose_name='Predmet')),
                ('doslo_datum', models.DateField(null=True, verbose_name='Došlo dňa')),
                ('na_zaklade', models.TextField(blank=True, help_text='Dokument (faktúra), na základe ktorého sa faktúra vystavuje.', max_length=100, null=True, verbose_name='Na základe')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cinnost', models.ForeignKey(blank=True, db_constraint=False, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.cinnost', verbose_name='Činnosť')),
                ('ekoklas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ekonomickaklasifikacia', verbose_name='Ekonomická klasifikácia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objednavka_zmluva', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.objednavkazmluva', verbose_name='Objednávka / zmluva')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.program')),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zakazka2', models.ForeignKey(blank=True, db_constraint=False, help_text='Druhá zákazka v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky 2')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
                ('zdroj2', models.ForeignKey(blank=True, db_constraint=False, help_text='Druhý zdroj v prípade delenia faktúry, inak nechajte prázdne', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj', verbose_name='Zdroj 2')),
            ],
            options={
                'verbose_name': 'historical Vystavená faktúra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
