# Generated by Django 3.2.4 on 2024-01-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0148_auto_20240112_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='dcislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Číslo faktúry odberateĺa'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='dcislo',
            field=models.CharField(max_length=50, null=True, verbose_name='Číslo faktúry odberateĺa'),
        ),
    ]
