# Generated by Django 3.2.4 on 2024-01-12 12:48

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0149_auto_20240112_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvystavenafaktura',
            name='zo_softipu',
            field=models.TextField(help_text='Faktúra pre odberateľa, vytvorená v Softipe', max_length=100, null=True, verbose_name='Faktúra zo Softipu'),
        ),
        migrations.AddField(
            model_name='vystavenafaktura',
            name='zo_softipu',
            field=models.FileField(help_text='Faktúra pre odberateľa, vytvorená v Softipe', null=True, upload_to=uctovnictvo.models.vystavena_faktura_upload_location, verbose_name='Faktúra zo Softipu'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='na_zaklade',
            field=models.TextField(help_text='Dokument (faktúra), na základe ktorého sa faktúra vystavuje.', max_length=100, null=True, verbose_name='Na základe'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='na_zaklade',
            field=models.FileField(help_text='Dokument (faktúra), na základe ktorého sa faktúra vystavuje.', null=True, upload_to=uctovnictvo.models.vystavena_faktura_upload_location, verbose_name='Na základe'),
        ),
    ]
