# Generated by Django 3.2.4 on 2024-01-12 13:26

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0150_auto_20240112_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnajomnefaktura',
            name='zo_softipu',
            field=models.TextField(help_text='Faktúra pre nájomníka, vytvorená v Softipe', max_length=100, null=True, verbose_name='Faktúra zo Softipu'),
        ),
        migrations.AddField(
            model_name='najomnefaktura',
            name='zo_softipu',
            field=models.FileField(help_text='Faktúra pre nájomníka, vytvorená v Softipe', null=True, upload_to=uctovnictvo.models.najomne_faktura_upload_location, verbose_name='Faktúra zo Softipu'),
        ),
        migrations.AlterField(
            model_name='najomnefaktura',
            name='platobny_prikaz',
            field=models.FileField(blank=True, help_text="Súbor s krycím listom pre THS-ku. Generuje sa akciou 'Vytvoriť krycí list pre THS'.<br />Ak treba, v prípade vyúčtovania je súčasťou aj platobný prikaz", null=True, upload_to=uctovnictvo.models.najomne_faktura_upload_location, verbose_name='Krycí list pre THS-ku'),
        ),
    ]
