# Generated by Django 3.2.4 on 2024-02-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0152_auto_20240120_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='cislo_biometric',
            field=models.IntegerField(help_text='Uveďte číslo zamestnanca v Biometricu', null=True, verbose_name='ČísloBiom'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='cislo_biometric',
            field=models.IntegerField(help_text='Uveďte číslo zamestnanca v Biometricu', null=True, verbose_name='ČísloBiom'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='cislo_zamestnanca',
            field=models.CharField(max_length=50, null=True, verbose_name='ČísloZam'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='cislo_zamestnanca',
            field=models.CharField(max_length=50, null=True, verbose_name='ČísloZam'),
        ),
    ]
