# Generated by Django 3.2.4 on 2024-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0153_auto_20240202_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='dovp',
            name='datum_ukoncenia',
            field=models.DateField(blank=True, help_text='Zadajte dátum predčasného ukončenia platnosti dohody', null=True, verbose_name='Dátum ukončenia'),
        ),
        migrations.AddField(
            model_name='dovp',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Zadajte sumu na vyplatenie. Ak ponecháte 0, doplní sa suma z poľa 'Celková suma v EUR'<br /><strong>Vyplniť v prípade predčasnéo ukončenia</strong> dohody.", max_digits=8, verbose_name='Vyplatená odmena'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='datum_ukoncenia',
            field=models.DateField(blank=True, help_text='Zadajte dátum predčasného ukončenia platnosti dohody', null=True, verbose_name='Dátum ukončenia'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='vyplatena_odmena',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Zadajte sumu na vyplatenie. Ak ponecháte 0, doplní sa suma z poľa 'Celková suma v EUR'<br /><strong>Vyplniť v prípade predčasnéo ukončenia</strong> dohody.", max_digits=8, verbose_name='Vyplatená odmena'),
        ),
    ]
