# Generated by Django 3.2.4 on 2024-02-09 15:00

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0154_auto_20240209_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpokladna',
            name='subor_doklad',
            field=models.TextField(blank=True, help_text='Súbor so zoskenovaným dokladom o úhrade', max_length=100, null=True, verbose_name='Doklad o úhrade'),
        ),
        migrations.AddField(
            model_name='pokladna',
            name='subor_doklad',
            field=models.FileField(blank=True, help_text='Súbor so zoskenovaným dokladom o úhrade', null=True, upload_to=uctovnictvo.models.pokladna_upload_location, verbose_name='Doklad o úhrade'),
        ),
    ]
