# Generated by Django 3.2.4 on 2024-02-18 11:28

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0155_auto_20240209_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='dcislo',
            field=models.CharField(help_text='Zadajte číslo faktúry zo Softipu', max_length=50, null=True, verbose_name='Číslo Softip'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='na_zaklade',
            field=models.TextField(help_text='Dokument (faktúra od odberateľa), na základe ktorého sa faktúra vystavuje.', max_length=100, null=True, verbose_name='Na základe'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='dcislo',
            field=models.CharField(help_text='Zadajte číslo faktúry zo Softipu', max_length=50, null=True, verbose_name='Číslo Softip'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='na_zaklade',
            field=models.FileField(help_text='Dokument (faktúra od odberateľa), na základe ktorého sa faktúra vystavuje.', null=True, upload_to=uctovnictvo.models.vystavena_faktura_upload_location, verbose_name='Na základe'),
        ),
    ]
