# Generated by Django 3.2.4 on 2024-03-05 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0156_auto_20240218_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjednavka',
            name='vybavuje',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vybavuje'),
        ),
        migrations.AddField(
            model_name='historicalobjednavkazmluva',
            name='vybavuje',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vybavuje'),
        ),
        migrations.AddField(
            model_name='historicalrozhodnutie',
            name='vybavuje',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vybavuje'),
        ),
        migrations.AddField(
            model_name='historicalzmluva',
            name='vybavuje',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vybavuje'),
        ),
        migrations.AddField(
            model_name='objednavkazmluva',
            name='vybavuje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objednavkazmluva_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Vybavuje'),
        ),
    ]
