# Generated by Django 3.2.4 on 2024-03-05 21:35

from django.db import migrations, models
import uctovnictvo.models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0157_auto_20240305_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dovp',
            name='id_tsh',
            field=models.CharField(blank=True, help_text='Uveďte číslo, pod ktorým dohody vedie mzdová učtáreň', max_length=100, null=True, verbose_name='Číslo priradené mzdovou učtárňou'),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='id_tsh',
            field=models.CharField(blank=True, help_text='Uveďte číslo, pod ktorým dohody vedie mzdová učtáreň', max_length=100, null=True, verbose_name='Číslo priradené mzdovou učtárňou'),
        ),
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='platobny_prikaz',
            field=models.TextField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", max_length=100, null=True, verbose_name='Platobný príkaz pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='historicalnajomnefaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na vybavenie dňa'),
        ),
        migrations.AlterField(
            model_name='historicalnajomnefaktura',
            name='platobny_prikaz',
            field=models.TextField(blank=True, help_text="Súbor s krycím listom. Generuje sa akciou 'Vytvoriť krycí list'.<br />Ak treba, v prípade vyúčtovania je súčasťou aj platobný prikaz", max_length=100, null=True, verbose_name='Krycí list'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='cislo',
            field=models.CharField(help_text='Uveďte číslo výmeru podľa mzdovej učtárne', max_length=50, null=True, verbose_name='Číslo výmeru'),
        ),
        migrations.AlterField(
            model_name='historicalplatovyvymer',
            name='suborvymer',
            field=models.TextField(blank=True, help_text='Vložte zoskenovaný platový výmer (vytvorený mzdovou učtárňou)', max_length=100, null=True, verbose_name='Výmer'),
        ),
        migrations.AlterField(
            model_name='historicalpokladna',
            name='datum_softip',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia zoznamu PD pre učtáreň. Vypĺňa sa automaticky akciou 'vytvoriť zoznam PD pre učtáreň'", null=True, verbose_name='Dátum učtárne'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='platobny_prikaz',
            field=models.TextField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", max_length=100, null=True, verbose_name='Platobný príkaz pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='platobny_prikaz',
            field=models.TextField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", max_length=100, null=True, verbose_name='Platobný príkaz pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknarekreaciu',
            name='prispevok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška príspevku na rekreáciu určená mzdovou učtárňou (záporné číslo).', max_digits=8, null=True, verbose_name='Na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='platobny_prikaz',
            field=models.TextField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", max_length=100, null=True, verbose_name='Platobný príkaz pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='platobny_prikaz',
            field=models.FileField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Platobný príkaz pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='najomnefaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na vybavenie dňa'),
        ),
        migrations.AlterField(
            model_name='najomnefaktura',
            name='platobny_prikaz',
            field=models.FileField(blank=True, help_text="Súbor s krycím listom. Generuje sa akciou 'Vytvoriť krycí list'.<br />Ak treba, v prípade vyúčtovania je súčasťou aj platobný prikaz", null=True, upload_to=uctovnictvo.models.najomne_faktura_upload_location, verbose_name='Krycí list'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='cislo',
            field=models.CharField(help_text='Uveďte číslo výmeru podľa mzdovej učtárne', max_length=50, null=True, verbose_name='Číslo výmeru'),
        ),
        migrations.AlterField(
            model_name='platovyvymer',
            name='suborvymer',
            field=models.FileField(blank=True, help_text='Vložte zoskenovaný platový výmer (vytvorený mzdovou učtárňou)', null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=uctovnictvo.models.vymer_file_path, verbose_name='Výmer'),
        ),
        migrations.AlterField(
            model_name='pokladna',
            name='datum_softip',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia zoznamu PD pre učtáreň. Vypĺňa sa automaticky akciou 'vytvoriť zoznam PD pre učtáreň'", null=True, verbose_name='Dátum učtárne'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='platobny_prikaz',
            field=models.FileField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Platobný príkaz pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='platobny_prikaz',
            field=models.FileField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Platobný príkaz pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='prispevoknarekreaciu',
            name='prispevok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška príspevku na rekreáciu určená mzdovou učtárňou (záporné číslo).', max_digits=8, null=True, verbose_name='Na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania podpísaného platobného príkazu a krycieho listu na sekretariát na odoslanie do učtárne. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dané na úhradu dňa'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='platobny_prikaz',
            field=models.FileField(blank=True, help_text="Súbor s platobným príkazom a krycím listom. Generuje sa akciou 'Vytvoriť platobný príkaz a krycí list'", null=True, upload_to=uctovnictvo.models.platobny_prikaz_upload_location, verbose_name='Platobný príkaz pre učtáreň'),
        ),
    ]
