# Generated by Django 3.2.4 on 2024-03-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0158_auto_20240305_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objednavkazmluva',
            name='vybavuje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objednavkazmluva_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Vybavuje'),
        ),
    ]
