# Generated by Django 3.2.4 on 2024-03-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0160_auto_20240306_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjednavka',
            name='ziadatel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Zadajte žiadateľa (pokiaľ sa líši od 'Vybavuje').", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='ziadatel',
            field=models.ForeignKey(blank=True, help_text="Zadajte žiadateľa (pokiaľ sa líši od 'Vybavuje').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objednavka_requests_created', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ'),
        ),
        migrations.AlterField(
            model_name='objednavkazmluva',
            name='vybavuje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objednavkazmluva_requests_created', to='uctovnictvo.zamestnanecdohodar', verbose_name='Vybavuje'),
        ),
    ]
