# Generated by Django 3.2.4 on 2024-03-06 16:25

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0161_auto_20240306_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjednavka',
            name='subor_ziadanky',
            field=models.TextField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť žiadanku'", max_length=100, null=True, verbose_name='Súbor žiadanky'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='subor_ziadanky',
            field=models.FileField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť žiadanku'", null=True, upload_to=uctovnictvo.models.objednavka_upload_location, verbose_name='Súbor žiadanky'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='subor_prilohy',
            field=models.TextField(blank=True, help_text='Súbor s prílohou k žiadanke/objednávke. Použite, ak sa v poli <em>Objednané položky</em> takáto príloha spomína.', max_length=100, null=True, verbose_name='Súbor prílohy'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='subor_prilohy',
            field=models.FileField(blank=True, help_text='Súbor s prílohou k žiadanke/objednávke. Použite, ak sa v poli <em>Objednané položky</em> takáto príloha spomína.', null=True, upload_to=uctovnictvo.models.objednavka_upload_location, verbose_name='Súbor prílohy'),
        ),
    ]
