# Generated by Django 3.2.4 on 2024-03-13 19:00

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0163_alter_objednavkazmluva_dodavatel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpokladna',
            name='subor_ziadanky',
            field=models.TextField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť žiadanku'", max_length=100, null=True, verbose_name='Súbor žiadanky'),
        ),
        migrations.AddField(
            model_name='pokladna',
            name='subor_ziadanky',
            field=models.FileField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť žiadanku'", null=True, upload_to=uctovnictvo.models.pokladna_upload_location, verbose_name='Súbor žiadanky'),
        ),
    ]
