# Generated by Django 3.2.4 on 2024-03-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0164_auto_20240313_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vybavovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, help_text='Uveďte telefónne číslo v EnÚ. Ak sa neuvedie, v príslušnom dokumente zostane predvolené číslo', max_length=20, null=True, verbose_name='Telefón')),
                ('enu_email', models.EmailField(blank=True, help_text='Uveďte e-mail v EnÚ. Ak sa neuvedie, preberie sa osobný e-mail', max_length=200, null=True, verbose_name='Email')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vybavovatel_vybavuje', to='uctovnictvo.zamestnanecdohodar', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Vybavovateľ',
                'verbose_name_plural': 'Faktúry - Vybavovatelia',
            },
        ),
    ]
