# Generated by Django 3.2.4 on 2024-03-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0165_vybavovatel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjednavka',
            name='vybavuje2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.vybavovatel', verbose_name='Vybavuje2'),
        ),
        migrations.AddField(
            model_name='historicalobjednavkazmluva',
            name='vybavuje2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.vybavovatel', verbose_name='Vybavuje2'),
        ),
        migrations.AddField(
            model_name='historicalrozhodnutie',
            name='vybavuje2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.vybavovatel', verbose_name='Vybavuje2'),
        ),
        migrations.AddField(
            model_name='historicalzmluva',
            name='vybavuje2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.vybavovatel', verbose_name='Vybavuje2'),
        ),
        migrations.AddField(
            model_name='objednavkazmluva',
            name='vybavuje2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objednavkazmluva_requests_created', to='uctovnictvo.vybavovatel', verbose_name='Vybavuje2'),
        ),
    ]
