# Generated by Django 3.2.4 on 2024-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0168_auto_20240326_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnajomnefaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AddField(
            model_name='najomnefaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='historicalinternyprevod',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='internyprevod',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='uhradene_dna',
            field=models.DateField(blank=True, help_text='Zadajte dátum uhradenia príp. zaúčtovanie učtárňou (podľa výpisu zo Softipu a tak podobne)', null=True, verbose_name='Uhradené dňa'),
        ),
    ]
