# Generated by Django 3.2.4 on 2024-04-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0169_auto_20240403_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='zrusena',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola faktúra zružená bez úhrady.", max_length=3, null=True, verbose_name='Zrušená'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='zrusena',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola faktúra zružená bez úhrady.", max_length=3, null=True, verbose_name='Zrušená'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='prenosDP',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak je faktúra v režime prenesenia daňovej povinnosti.", max_length=3, verbose_name='Prenos DP'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='prenosDP',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak je faktúra v režime prenesenia daňovej povinnosti.", max_length=3, verbose_name='Prenos DP'),
        ),
    ]
