# Generated by Django 3.2.4 on 2024-04-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0170_auto_20240403_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='zrusena',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola faktúra zrušená bez úhrady.", max_length=3, null=True, verbose_name='Zrušená'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='zrusena',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola faktúra zrušená bez úhrady.", max_length=3, null=True, verbose_name='Zrušená'),
        ),
    ]
