# Generated by Django 3.2.4 on 2024-04-17 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0173_auto_20240407_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: s 5 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 30193300-1</strong>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='historicalpokladna',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Uveďte zamestnanca, ktorého výdavok bol uhradený. V prípade dotácie nechajte prázdne.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanecdohodar'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: s 5 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 30193300-1</strong>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='pokladna',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, help_text='Uveďte zamestnanca, ktorého výdavok bol uhradený. V prípade dotácie nechajte prázdne.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.zamestnanecdohodar'),
        ),
        migrations.CreateModel(
            name='NakupSUhradou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('predmet', models.CharField(help_text="Zadajte stručný popis, napr. 'poštové známky'", max_length=100, verbose_name='Predmet')),
                ('forma_uhrady', models.CharField(choices=[('hotovost', 'V hotovosti'), ('ucet', 'Na účet')], max_length=10, verbose_name='Forma úhrady')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('objednane_polozky', models.TextField(blank=True, help_text='<p>Po riadkoch zadajte žiadané položky:</p>                <ol>                <li>pri vytváraní žiadanky: s tromi poľami oddelenými bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b>, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1</b>. </li>                <li>pri vytváraní žiadosti o preplatenie: aktualizujte zadané polia podľa účtového dokladu. </li>                <li>po spracovaní účtárňou: do každého riadka na posledné miesto doplňte ekonomickú klasifikáciu (EKRK) tovaru podľa dokladov účtárne.                </ol>', max_length=5000, null=True, verbose_name='Objednané položky')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, help_text="Cena s DPH. Vypočíta sa z údajov v poli 'Objednane položky'", max_digits=8, null=True, verbose_name='Cena')),
                ('zamietnute', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola žiadanka zamietnutá", max_length=3, null=True, verbose_name='Zamietnuté')),
                ('subor_ziadanky', models.FileField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť žiadanku'", null=True, upload_to=uctovnictvo.models.nakup_upload_location, verbose_name='Súbor žiadanky')),
                ('datum_ziadanky', models.DateField(blank=True, help_text='Zadajte dátum založenia podpísanej žiadanky do šanonu', null=True, verbose_name='Žiadanka do šanonu')),
                ('subor_preplatenie', models.FileField(blank=True, help_text="Súbor so žiadosťou o preplatenie a krycím listom. Generuje sa akciou 'Vytvoriť žiadosť o preplatenie'", null=True, upload_to=uctovnictvo.models.nakup_upload_location, verbose_name='Súbor žiadosti')),
                ('subor_ucty', models.FileField(blank=True, help_text='Súbor so zoskenovaným dokladom o úhrade', null=True, upload_to=uctovnictvo.models.nakup_upload_location, verbose_name='Doklad o úhrade')),
                ('datum_preplatenie', models.DateField(blank=True, help_text='<ol><li>Zadajte dátum odoslania žiadosti o preplatenie do účtárne</li><li>Ak ide o vyplatenie cez pokladňu, zadajte dnešný dátum. Vytvorí sa záznam v Pokladni</li></ol>', null=True, verbose_name='Dátum vybavenia')),
                ('datum_uhradenia', models.DateField(blank=True, help_text="Dátum uhradenia podľa údajov z učtárne (v oboch prípadoch - preplatenie na účet aj cez pokladňu). Pred zadaním treba na základe údajov z učtárne doplniť EKRK v poli 'Objednané položky'.", null=True, verbose_name='Dátum uhradenia')),
                ('vybavuje', models.ForeignKey(help_text='Osoba, ktorá veci kúpi a komu bude nákup vyúčtovaný', on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_nakup', to='uctovnictvo.zamestnanecdohodar', verbose_name='Vybavuje')),
                ('zakazka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_nakup', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_nakup', to='uctovnictvo.zdroj')),
                ('ziadatel', models.ForeignKey(blank=True, help_text="Zadajte žiadateľa (pokiaľ sa líši od 'Vybavuje').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_requests_created', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ')),
            ],
            options={
                'verbose_name': 'Drobný nákup - žiadanka',
                'verbose_name_plural': 'Drobný nákup / žiadanky',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNakupSUhradou',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo')),
                ('predmet', models.CharField(help_text="Zadajte stručný popis, napr. 'poštové známky'", max_length=100, verbose_name='Predmet')),
                ('forma_uhrady', models.CharField(choices=[('hotovost', 'V hotovosti'), ('ucet', 'Na účet')], max_length=10, verbose_name='Forma úhrady')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('objednane_polozky', models.TextField(blank=True, help_text='<p>Po riadkoch zadajte žiadané položky:</p>                <ol>                <li>pri vytváraní žiadanky: s tromi poľami oddelenými bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b>, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1</b>. </li>                <li>pri vytváraní žiadosti o preplatenie: aktualizujte zadané polia podľa účtového dokladu. </li>                <li>po spracovaní účtárňou: do každého riadka na posledné miesto doplňte ekonomickú klasifikáciu (EKRK) tovaru podľa dokladov účtárne.                </ol>', max_length=5000, null=True, verbose_name='Objednané položky')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, help_text="Cena s DPH. Vypočíta sa z údajov v poli 'Objednane položky'", max_digits=8, null=True, verbose_name='Cena')),
                ('zamietnute', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola žiadanka zamietnutá", max_length=3, null=True, verbose_name='Zamietnuté')),
                ('subor_ziadanky', models.TextField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť žiadanku'", max_length=100, null=True, verbose_name='Súbor žiadanky')),
                ('datum_ziadanky', models.DateField(blank=True, help_text='Zadajte dátum založenia podpísanej žiadanky do šanonu', null=True, verbose_name='Žiadanka do šanonu')),
                ('subor_preplatenie', models.TextField(blank=True, help_text="Súbor so žiadosťou o preplatenie a krycím listom. Generuje sa akciou 'Vytvoriť žiadosť o preplatenie'", max_length=100, null=True, verbose_name='Súbor žiadosti')),
                ('subor_ucty', models.TextField(blank=True, help_text='Súbor so zoskenovaným dokladom o úhrade', max_length=100, null=True, verbose_name='Doklad o úhrade')),
                ('datum_preplatenie', models.DateField(blank=True, help_text='<ol><li>Zadajte dátum odoslania žiadosti o preplatenie do účtárne</li><li>Ak ide o vyplatenie cez pokladňu, zadajte dnešný dátum. Vytvorí sa záznam v Pokladni</li></ol>', null=True, verbose_name='Dátum vybavenia')),
                ('datum_uhradenia', models.DateField(blank=True, help_text="Dátum uhradenia podľa údajov z učtárne (v oboch prípadoch - preplatenie na účet aj cez pokladňu). Pred zadaním treba na základe údajov z učtárne doplniť EKRK v poli 'Objednané položky'.", null=True, verbose_name='Dátum uhradenia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vybavuje', models.ForeignKey(blank=True, db_constraint=False, help_text='Osoba, ktorá veci kúpi a komu bude nákup vyúčtovaný', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanecdohodar', verbose_name='Vybavuje')),
                ('zakazka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.typzakazky', verbose_name='Typ zákazky')),
                ('zdroj', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zdroj')),
                ('ziadatel', models.ForeignKey(blank=True, db_constraint=False, help_text="Zadajte žiadateľa (pokiaľ sa líši od 'Vybavuje').", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ')),
            ],
            options={
                'verbose_name': 'historical Drobný nákup - žiadanka',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
