# Generated by Django 3.2.4 on 2024-04-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0174_auto_20240417_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnakupsuhradou',
            old_name='datum_preplatenie',
            new_name='datum_vybavenia',
        ),
        migrations.RenameField(
            model_name='nakupsuhradou',
            old_name='datum_preplatenie',
            new_name='datum_vybavenia',
        ),
        migrations.RemoveField(
            model_name='historicalnakupsuhradou',
            name='predmet',
        ),
        migrations.RemoveField(
            model_name='nakupsuhradou',
            name='predmet',
        ),
        migrations.AddField(
            model_name='historicalnakupsuhradou',
            name='pokladna_vpd',
            field=models.CharField(blank=True, help_text='Číslo záznamu v pokladni s VPD. Vypĺňa sa automaticky', max_length=50, null=True, verbose_name='Pokladňa VPD'),
        ),
        migrations.AddField(
            model_name='historicalnakupsuhradou',
            name='popis',
            field=models.CharField(default='', help_text="Zadajte stručný popis, napr. 'poštové známky'", max_length=100, verbose_name='Popis platby'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpokladna',
            name='ziadanka',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Žiadanka. Vypĺňa sa automaticky', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.nakupsuhradou'),
        ),
        migrations.AddField(
            model_name='nakupsuhradou',
            name='pokladna_vpd',
            field=models.CharField(blank=True, help_text='Číslo záznamu v pokladni s VPD. Vypĺňa sa automaticky', max_length=50, null=True, verbose_name='Pokladňa VPD'),
        ),
        migrations.AddField(
            model_name='nakupsuhradou',
            name='popis',
            field=models.CharField(default='', help_text="Zadajte stručný popis, napr. 'poštové známky'", max_length=100, verbose_name='Popis platby'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokladna',
            name='ziadanka',
            field=models.ForeignKey(blank=True, help_text='Žiadanka. Vypĺňa sa automaticky', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.nakupsuhradou'),
        ),
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text="Dátum uhradenia podľa Softipu (aj pri preplatení na účet a aj cez pokladňu). Pred zadaním treba na základe údajov z učtárne doplniť EKRK v poli 'Objednané položky'.", null=True, verbose_name='Dátum uhradenia'),
        ),
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte žiadané položky:</p>                <ol>                <li>pri vytváraní žiadanky: s tromi poľami oddelenými bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b>, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1</b>. </li>                <li>pri vytváraní žiadosti o preplatenie: aktualizujte zadané polia podľa účtového dokladu. </li>                <li>po spracovaní v Softipe: do každého riadka na posledné miesto doplňte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text="Dátum uhradenia podľa Softipu (aj pri preplatení na účet a aj cez pokladňu). Pred zadaním treba na základe údajov z učtárne doplniť EKRK v poli 'Objednané položky'.", null=True, verbose_name='Dátum uhradenia'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Po riadkoch zadajte žiadané položky:</p>                <ol>                <li>pri vytváraní žiadanky: s tromi poľami oddelenými bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b>, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1</b>. </li>                <li>pri vytváraní žiadosti o preplatenie: aktualizujte zadané polia podľa účtového dokladu. </li>                <li>po spracovaní v Softipe: do každého riadka na posledné miesto doplňte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='vybavuje',
            field=models.ForeignKey(help_text='Osoba, ktorá veci kúpi a komu bude nákup vyúčtovaný', on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_vybavuje', to='uctovnictvo.zamestnanecdohodar', verbose_name='Vybavuje'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='ziadatel',
            field=models.ForeignKey(blank=True, help_text="Zadajte žiadateľa (pokiaľ sa líši od 'Vybavuje').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_ziadatel', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ'),
        ),
    ]
