# Generated by Django 3.2.4 on 2024-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0175_auto_20240417_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnakupsuhradou',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Drobný nákup - Žiadanka'},
        ),
        migrations.AlterModelOptions(
            name='historicalpokladna',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Drobný nákup - Záznam pokladne'},
        ),
        migrations.AlterModelOptions(
            name='nakupsuhradou',
            options={'verbose_name': 'Drobný nákup - Žiadanka', 'verbose_name_plural': 'Drobný nákup / Žiadanky'},
        ),
        migrations.AlterModelOptions(
            name='pokladna',
            options={'verbose_name': 'Drobný nákup - Záznam pokladne', 'verbose_name_plural': 'Drobný nákup / Záznamy pokladne'},
        ),
    ]
