# Generated by Django 3.2.4 on 2024-04-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0176_auto_20240417_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cena s DPH. Vypočíta sa z údajov v poli 'Objednane položky'", max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text="Dátum uhradenia podľa Softipu (aj pri preplatení na účet a aj cez pokladňu). Pred zadaním treba na základe údajov z učtárne upraviť EKRK v poli 'Objednané položky'.", null=True, verbose_name='Dátum uhradenia'),
        ),
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text="<p>Žiadané položky zadajte po riadkoch (max. 8 riadkov):</p>                <ol>                <li>pri vytváraní žiadanky zadajte 4 polia oddelené bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b> / EKRK, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1 / 632003</b>. CPV kód možno nahradiť pomlčkou '-'. </li>                <li>pri vytváraní žiadosti o preplatenie aktualizujte zadané polia podľa dokladu o úhrade. </li>                <li>po spracovaní v Softipe aktualizujte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>", max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cena s DPH. Vypočíta sa z údajov v poli 'Objednane položky'", max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text="Dátum uhradenia podľa Softipu (aj pri preplatení na účet a aj cez pokladňu). Pred zadaním treba na základe údajov z učtárne upraviť EKRK v poli 'Objednané položky'.", null=True, verbose_name='Dátum uhradenia'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text="<p>Žiadané položky zadajte po riadkoch (max. 8 riadkov):</p>                <ol>                <li>pri vytváraní žiadanky zadajte 4 polia oddelené bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b> / EKRK, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1 / 632003</b>. CPV kód možno nahradiť pomlčkou '-'. </li>                <li>pri vytváraní žiadosti o preplatenie aktualizujte zadané polia podľa dokladu o úhrade. </li>                <li>po spracovaní v Softipe aktualizujte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>", max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
    ]
