# Generated by Django 3.2.4 on 2024-04-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0177_auto_20240417_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpokladna',
            name='ziadanka',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Žiadanka. Vypĺňa sa automaticky', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.nakupsuhradou', verbose_name='Žiadanka'),
        ),
        migrations.AlterField(
            model_name='pokladna',
            name='ziadanka',
            field=models.ForeignKey(blank=True, help_text='Žiadanka. Vypĺňa sa automaticky', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokladna_pokladna', to='uctovnictvo.nakupsuhradou', verbose_name='Žiadanka'),
        ),
    ]
