# Generated by Django 3.2.4 on 2024-04-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0178_auto_20240417_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpokladna',
            name='cinnost',
        ),
        migrations.RemoveField(
            model_name='historicalpokladna',
            name='ekoklas',
        ),
        migrations.RemoveField(
            model_name='historicalpokladna',
            name='subor_doklad',
        ),
        migrations.RemoveField(
            model_name='historicalpokladna',
            name='subor_ziadanky',
        ),
        migrations.RemoveField(
            model_name='historicalpokladna',
            name='zakazka',
        ),
        migrations.RemoveField(
            model_name='historicalpokladna',
            name='zdroj',
        ),
        migrations.RemoveField(
            model_name='pokladna',
            name='cinnost',
        ),
        migrations.RemoveField(
            model_name='pokladna',
            name='ekoklas',
        ),
        migrations.RemoveField(
            model_name='pokladna',
            name='subor_doklad',
        ),
        migrations.RemoveField(
            model_name='pokladna',
            name='subor_ziadanky',
        ),
        migrations.RemoveField(
            model_name='pokladna',
            name='zakazka',
        ),
        migrations.RemoveField(
            model_name='pokladna',
            name='zdroj',
        ),
    ]
