# Generated by Django 3.2.4 on 2024-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0180_auto_20240418_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text="<p>Žiadané položky zadajte po riadkoch (max. 8 riadkov):</p>                <ol>                <li>Pri vytváraní žiadanky zadajte 4 polia oddelené bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b> / EKRK, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1 / 632003</b>. CPV kód možno nahradiť pomlčkou '-'. </li>                <li>Cena tovaru/služby sa uvádza ako <b>kladná</b>, suma vrátená do pokladne ako <b>záporná</b>. </li>                <li>Pri vytváraní žiadosti o preplatenie aktualizujte zadané polia podľa dokladu o úhrade. </li>                <li>Po spracovaní v Softipe aktualizujte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>", max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text="<p>Žiadané položky zadajte po riadkoch (max. 8 riadkov):</p>                <ol>                <li>Pri vytváraní žiadanky zadajte 4 polia oddelené bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b> / EKRK, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1 / 632003</b>. CPV kód možno nahradiť pomlčkou '-'. </li>                <li>Cena tovaru/služby sa uvádza ako <b>kladná</b>, suma vrátená do pokladne ako <b>záporná</b>. </li>                <li>Pri vytváraní žiadosti o preplatenie aktualizujte zadané polia podľa dokladu o úhrade. </li>                <li>Po spracovaní v Softipe aktualizujte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>", max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
    ]
