# Generated by Django 3.2.4 on 2024-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0181_auto_20240418_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprispevoknastravne',
            name='zrazka_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka SF za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. SF'),
        ),
        migrations.AddField(
            model_name='historicalprispevoknastravne',
            name='zrazka_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka zamestnanca (Ek. klas. 642014) za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. zam.'),
        ),
        migrations.AddField(
            model_name='prispevoknastravne',
            name='zrazka_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka SF za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. SF'),
        ),
        migrations.AddField(
            model_name='prispevoknastravne',
            name='zrazka_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka zamestnanca (Ek. klas. 642014) za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. zam.'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok SF na stravné (záporná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. SF'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok zamestnávateľa (Ek. klas. 642014) na stravné (záporná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. zam.'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné'), ('pri_zra', 'Príspevky a zrážky')], default='pri_zra', help_text="Zvoľte typ zoznamu.<br/>Položku uložte a následne akciou 'Generovať zoznam príspevkov/zrážok' vytvorte súbor so zoznamom.", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok SF na stravné (záporná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. SF'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='suma_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Príspevok zamestnávateľa (Ek. klas. 642014) na stravné (záporná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Prísp. zam.'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné'), ('pri_zra', 'Príspevky a zrážky')], default='pri_zra', help_text="Zvoľte typ zoznamu.<br/>Položku uložte a následne akciou 'Generovať zoznam príspevkov/zrážok' vytvorte súbor so zoznamom.", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
    ]
