# Generated by Django 3.2.4 on 2024-04-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0182_auto_20240419_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(blank=True, choices=[('materská', 'MD/RD'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Platené zdr. voľno podľa KZ'), ('pv', 'Pracovné voľno (PV, P, S, KZVS, POH)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('pracadoma', 'Práca na doma'), ('skolenie', 'Školenie'), ('zrusena', 'Zrušená')], help_text="Ak sa tento záznam nedostal do Softipu a je to chyba, zvoľte 'Zrušená' v poli poznámka uveďte dôvod.", max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné'), ('pri_zra', 'Príspevky a zrážky')], default='pri_zra', help_text="Typ zoznamu. Od apríla 2024 je povolené len 'Príspevky a zrážky'", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='za_mesiac',
            field=models.CharField(choices=[('januar', 'január'), ('februar', 'február'), ('marec', 'marec'), ('april', 'apríl'), ('maj', 'máj'), ('jun', 'jún'), ('jul', 'júl'), ('august', 'august'), ('september', 'september'), ('oktober', 'október'), ('november', 'november'), ('december', 'december')], help_text="Zadajte mzdové obdobie.<br />Napr., ak koncom apríla chcete vytvoriť dokument na máj, zvoľte 'máj'. Vytvorí sa zoznam príspevkov na máj a zrážky za stravné sa vypočítajú za apríl.", max_length=20, null=True, verbose_name='Mesiac'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='zrazka_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka SF za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Zrážky SF'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknastravne',
            name='zrazka_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka zamestnanca (Ek. klas. 642014) za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Zrážky zam.'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(blank=True, choices=[('materská', 'MD/RD'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Platené zdr. voľno podľa KZ'), ('pv', 'Pracovné voľno (PV, P, S, KZVS, POH)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('pracadoma', 'Práca na doma'), ('skolenie', 'Školenie'), ('zrusena', 'Zrušená')], help_text="Ak sa tento záznam nedostal do Softipu a je to chyba, zvoľte 'Zrušená' v poli poznámka uveďte dôvod.", max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='typ_zoznamu',
            field=models.CharField(choices=[('prispevky', 'Príspevky na stravné'), ('zrazky', 'Zrážky za stravné'), ('pri_zra', 'Príspevky a zrážky')], default='pri_zra', help_text="Typ zoznamu. Od apríla 2024 je povolené len 'Príspevky a zrážky'", max_length=20, null=True, verbose_name='Typ zoznamu'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='za_mesiac',
            field=models.CharField(choices=[('januar', 'január'), ('februar', 'február'), ('marec', 'marec'), ('april', 'apríl'), ('maj', 'máj'), ('jun', 'jún'), ('jul', 'júl'), ('august', 'august'), ('september', 'september'), ('oktober', 'október'), ('november', 'november'), ('december', 'december')], help_text="Zadajte mzdové obdobie.<br />Napr., ak koncom apríla chcete vytvoriť dokument na máj, zvoľte 'máj'. Vytvorí sa zoznam príspevkov na máj a zrážky za stravné sa vypočítajú za apríl.", max_length=20, null=True, verbose_name='Mesiac'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='zrazka_socfond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka SF za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Zrážky SF'),
        ),
        migrations.AlterField(
            model_name='prispevoknastravne',
            name='zrazka_zamestnavatel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Zrážka zamestnanca (Ek. klas. 642014) za stravné (kladná hodnota). Suma sa automaticky generuje akciou 'Generovať zoznam príspevkov/zrážok'", max_digits=8, null=True, verbose_name='Zrážky zam.'),
        ),
    ]
