# Generated by Django 3.2.4 on 2024-04-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0184_auto_20240424_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dohoda',
            name='pomocnik',
        ),
        migrations.RemoveField(
            model_name='historicaldobps',
            name='pomocnik',
        ),
        migrations.RemoveField(
            model_name='historicaldopc',
            name='pomocnik',
        ),
        migrations.RemoveField(
            model_name='historicaldovp',
            name='pomocnik',
        ),
    ]
