# Generated by Django 3.2.4 on 2024-06-16 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0186_auto_20240610_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcetUctovnejOsnovy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text='Zadajte kód účtu účtovnej osnovy', max_length=10, verbose_name='Kód')),
                ('nazov', models.CharField(help_text='Zadajte názov účtu účtovnej osnovy', max_length=100, verbose_name='Názov')),
            ],
            options={
                'verbose_name': ('Účet účovnej osnovy',),
                'verbose_name_plural': 'Klasifikácia - Účet',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUcetUctovnejOsnovy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kod', models.CharField(help_text='Zadajte kód účtu účtovnej osnovy', max_length=10, verbose_name='Kód')),
                ('nazov', models.CharField(help_text='Zadajte názov účtu účtovnej osnovy', max_length=100, verbose_name='Názov')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical ('Účet účovnej osnovy',)",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
