# Generated by Django 3.2.4 on 2024-06-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0186_auto_20240610_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprispevoknarekreaciu',
            name='datum_vyplatenia',
            field=models.DateField(help_text='Dátum vyplatenia podľa Softipu. Obvykle najbližší výplatný termím (v nasledujúcom mesiaci).', null=True, verbose_name='Dátum vyplatenia'),
        ),
        migrations.AlterField(
            model_name='prispevoknarekreaciu',
            name='datum_vyplatenia',
            field=models.DateField(help_text='Dátum vyplatenia podľa Softipu. Obvykle najbližší výplatný termím (v nasledujúcom mesiaci).', null=True, verbose_name='Dátum vyplatenia'),
        ),
    ]
