# Generated by Django 3.2.4 on 2024-06-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0187_historicalucetuctovnejosnovy_ucetuctovnejosnovy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dohoda',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dohoda_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalinternyprevod',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalnajomnefaktura',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalodmenaoprava',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalplatbabezprikazu',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalplatovyvymer',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalpravidelnaplatba',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalprispevoknarekreaciu',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalprispevoknastravne',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalrozpoctovapolozka',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalrozpoctovapolozkadotacia',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='historicalvystavenafaktura',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='internyprevod',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='internyprevod_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='najomnefaktura',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='najomnefaktura_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='odmenaoprava',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='platbabezprikazu',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='platbabezprikazu_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='platovyvymer',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='platovyvymer_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='pravidelnaplatba',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pravidelnaplatba_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prijatafaktura_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='prispevoknarekreaciu',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prispevoknarekreaciu_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='prispevoknastravne',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prispevoknastravne_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='rozpoctovapolozka',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rozpoctovapolozka_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='rozpoctovapolozkadotacia',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rozpoctovapolozkadotacia_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='vystavenafaktura',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vystavenafaktura_klasifikacia', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
    ]
