# Generated by Django 3.2.4 on 2024-06-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0188_auto_20240616_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnakupsuhradou',
            name='ucet',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='nakupsuhradou',
            name='ucet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_nakup', to='uctovnictvo.ucetuctovnejosnovy', verbose_name='Účet'),
        ),
    ]
