# Generated by Django 3.2.4 on 2024-06-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0189_auto_20240616_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ucetuctovnejosnovy',
            options={'verbose_name': ('Účet účovnej osnovy',), 'verbose_name_plural': 'Klasifikácia - Účty'},
        ),
        migrations.AddField(
            model_name='historicalucetuctovnejosnovy',
            name='kategoria',
            field=models.CharField(default='-', help_text='Zadajte kategóriu účtu', max_length=100, verbose_name='Kategória účtu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ucetuctovnejosnovy',
            name='kategoria',
            field=models.CharField(default='-', help_text='Zadajte kategóriu účtu', max_length=100, verbose_name='Kategória účtu'),
            preserve_default=False,
        ),
    ]
