# Generated by Django 3.2.4 on 2024-07-19 13:08

from django.db import migrations, models
import uctovnictvo.models
import uctovnictvo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0191_auto_20240716_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldohodar',
            name='suborpriloha',
            field=models.TextField(blank=True, help_text='Vložte súbor prílohy', max_length=100, null=True, verbose_name='Príloha'),
        ),
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='suborpriloha',
            field=models.TextField(blank=True, help_text='Vložte súbor prílohy', max_length=100, null=True, verbose_name='Príloha'),
        ),
        migrations.AddField(
            model_name='zamestnanecdohodar',
            name='suborpriloha',
            field=models.FileField(blank=True, help_text='Vložte súbor prílohy', null=True, storage=uctovnictvo.storage.OverwriteStorage(), upload_to=uctovnictvo.models.priloha_file_path, verbose_name='Príloha'),
        ),
    ]
