# Generated by Django 3.2.4 on 2024-07-21 15:51

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0192_auto_20240719_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='dodaci_list',
            field=models.TextField(blank=True, help_text='Súbor s dodacím listom', max_length=100, null=True, verbose_name='Dodací list'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='dodaci_list',
            field=models.FileField(blank=True, help_text='Súbor s dodacím listom', null=True, upload_to=uctovnictvo.models.prijata_faktura_upload_location, verbose_name='Dodací list'),
        ),
    ]
