# Generated by Django 3.2.4 on 2024-08-28 15:06

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0193_auto_20240721_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='subor_pracnapln',
            field=models.TextField(blank=True, help_text='Súbor s textom pracovnej náplne (zoskenovať a vložiť)', max_length=100, null=True, verbose_name='Pracovná náplň'),
        ),
        migrations.AddField(
            model_name='historicalzamestnanec',
            name='subor_zmluva',
            field=models.TextField(blank=True, help_text='Súbor s textom pracovnej zmluvy (zoskenovať a vložiť)', max_length=100, null=True, verbose_name='Pracovná zmluva'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='subor_pracnapln',
            field=models.FileField(blank=True, help_text='Súbor s textom pracovnej náplne (zoskenovať a vložiť)', null=True, upload_to=uctovnictvo.models.zamestnanci_upload_location, verbose_name='Pracovná náplň'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='subor_zmluva',
            field=models.FileField(blank=True, help_text='Súbor s textom pracovnej zmluvy (zoskenovať a vložiť)', null=True, upload_to=uctovnictvo.models.zamestnanci_upload_location, verbose_name='Pracovná zmluva'),
        ),
    ]
