# Generated by Django 3.2.4 on 2024-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0195_auto_20240830_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='termin_dodania',
            field=models.CharField(help_text='Určite termín dodania (dátum alebo slovné určenie)', max_length=30, null=True, verbose_name='Termím dodania'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='termin_dodania',
            field=models.CharField(help_text='Určite termín dodania (dátum alebo slovné určenie)', max_length=30, null=True, verbose_name='Termím dodania'),
        ),
    ]
