# Generated by Django 3.2.4 on 2024-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0196_auto_20240831_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='zamietnute',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola žiadanka zamietnutá. V tom prípade uveďte dôvod v poli Poznámka", max_length=3, null=True, verbose_name='Zamietnuté'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='zamietnute',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak bola žiadanka zamietnutá. V tom prípade uveďte dôvod v poli Poznámka", max_length=3, null=True, verbose_name='Zamietnuté'),
        ),
    ]
