# Generated by Django 3.2.4 on 2024-09-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0197_auto_20240904_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vyplacaniedohod',
            name='dohoda',
        ),
        migrations.DeleteModel(
            name='HistoricalVyplacanieDohod',
        ),
        migrations.DeleteModel(
            name='VyplacanieDohod',
        ),
    ]
