# Generated by Django 3.2.4 on 2024-09-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0198_auto_20240905_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalobjednavka',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Žiadanka / Objednávka'},
        ),
        migrations.AlterModelOptions(
            name='objednavka',
            options={'verbose_name': 'Žiadanka / Objednávka', 'verbose_name_plural': 'Faktúry - Žiadanky / Objednávky'},
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='datum_vytvorenia',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia objednávky. Vypĺňa sa automaticky akciou 'vytvorit_subor_objednavky'", null=True, verbose_name='Dátum vytvorenia'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='datum_vytvorenia',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia objednávky. Vypĺňa sa automaticky akciou 'vytvorit_subor_objednavky'", null=True, verbose_name='Dátum vytvorenia'),
        ),
    ]
