# Generated by Django 3.2.4 on 2024-10-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0201_auto_20241002_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Nevypĺňa sa, ak sa vkladá súbor so zoznamom odmien alebo ak zamestnanec nie je určený (napr. v prípade 'Oprava zrážky - plat (len pre čerpanie rozpočtu)'.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, help_text="Nevypĺňa sa, ak sa vkladá súbor so zoznamom odmien alebo ak zamestnanec nie je určený (napr. v prípade 'Oprava zrážky - plat (len pre čerpanie rozpočtu)'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odmenaoprava_zamestnanec', to='uctovnictvo.zamestnanec', verbose_name='Zamestnanec'),
        ),
    ]
