# Generated by Django 3.2.4 on 2024-10-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0203_auto_20241003_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cena s DPH. <br />Pri žiadanke vložiť odhadovanú cenu.<br />Pri žiadosti o preplatenie sa vypočíta z údajov v poli 'Objednane položky'", max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='cislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text="<p>V prípade Žiadanky voľne popíšte požadovaný nákup.</p>                <p>V prípade Žiadosti o preplatenie zakúpené položky zadajte po riadkoch (max. 8 riadkov):</p>                <ol>                <li>Zadajte 4 polia oddelené bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b> / EKRK, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1 / 632003</b>. CPV kód možno nahradiť pomlčkou '-'. </li>                <li>Cena tovaru/služby sa uvádza ako <b>kladná</b>, suma vrátená do pokladne ako <b>záporná</b>. </li>                <li>Po spracovaní v Softipe aktualizujte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>", max_length=5000, null=True, verbose_name='Položky nákupu'),
        ),
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='popis',
            field=models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'poštové známky'", max_length=100, null=True, verbose_name='Popis nákupu'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cena s DPH. <br />Pri žiadanke vložiť odhadovanú cenu.<br />Pri žiadosti o preplatenie sa vypočíta z údajov v poli 'Objednane položky'", max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='cislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text="<p>V prípade Žiadanky voľne popíšte požadovaný nákup.</p>                <p>V prípade Žiadosti o preplatenie zakúpené položky zadajte po riadkoch (max. 8 riadkov):</p>                <ol>                <li>Zadajte 4 polia oddelené bodkočiarkou alebo <b>lomkou /</b> v poradí: <b>názov položky a množstvo / odhadovaná cena s DPH / CPV kód</b> / EKRK, napr. <b>Euroobal A4 50 ks / 7,50 / 30193300-1 / 632003</b>. CPV kód možno nahradiť pomlčkou '-'. </li>                <li>Cena tovaru/služby sa uvádza ako <b>kladná</b>, suma vrátená do pokladne ako <b>záporná</b>. </li>                <li>Po spracovaní v Softipe aktualizujte ekonomickú klasifikáciu (EKRK) tovaru podľa údajov zo Softipu.                </ol>", max_length=5000, null=True, verbose_name='Položky nákupu'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='popis',
            field=models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'poštové známky'", max_length=100, null=True, verbose_name='Popis nákupu'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='ziadatel',
            field=models.ForeignKey(blank=True, help_text='Zadajte žiadateľa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_ziadatel', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ'),
        ),
    ]
