# Generated by Django 3.2.4 on 2024-10-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0204_auto_20241022_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnakupsuhradou',
            name='ziadatel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Zadajte žiadateľa o drobný nákup.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ'),
        ),
        migrations.AlterField(
            model_name='nakupsuhradou',
            name='ziadatel',
            field=models.ForeignKey(blank=True, help_text='Zadajte žiadateľa o drobný nákup.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nakupsuhradou_ziadatel', to='uctovnictvo.zamestnanecdohodar', verbose_name='Žiadateľ'),
        ),
    ]
