# Generated by Django 3.2.4 on 2024-10-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0206_auto_20241023_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='cislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: s 5 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 30193300-1</strong>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Text žiadanky / Objednané položky'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='predmet',
            field=models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'Kávovar Saeco' alebo 'Servisná podpora RS Beliana'", max_length=100, null=True, verbose_name='Predmet'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='predpokladana_cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH.<br />                    Ak sú cenové údaje zadané v poli <em>Objednané položky</em>, tak hodnota v tomto poli sa podľa nich vypočíta a aktualizuje. <br />                    Vo vygenerovanej objednávke sa zoberie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='termin_dodania',
            field=models.CharField(blank=True, help_text='Určite termín dodania (dátum alebo slovné určenie)', max_length=30, null=True, verbose_name='Termín dodania'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavkazmluva',
            name='cislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavkazmluva',
            name='predmet',
            field=models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'Kávovar Saeco' alebo 'Servisná podpora RS Beliana'", max_length=100, null=True, verbose_name='Predmet'),
        ),
        migrations.AlterField(
            model_name='historicalrozhodnutie',
            name='cislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='historicalrozhodnutie',
            name='predmet',
            field=models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'Kávovar Saeco' alebo 'Servisná podpora RS Beliana'", max_length=100, null=True, verbose_name='Predmet'),
        ),
        migrations.AlterField(
            model_name='historicalzmluva',
            name='cislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='historicalzmluva',
            name='predmet',
            field=models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'Kávovar Saeco' alebo 'Servisná podpora RS Beliana'", max_length=100, null=True, verbose_name='Predmet'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: s 5 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 30193300-1</strong>. <br />Cena za jednotlivé položky a celková suma sa dopočíta. Pri výpočte sa berie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH. </li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Text žiadanky / Objednané položky'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='predpokladana_cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH.<br />                    Ak sú cenové údaje zadané v poli <em>Objednané položky</em>, tak hodnota v tomto poli sa podľa nich vypočíta a aktualizuje. <br />                    Vo vygenerovanej objednávke sa zoberie do úvahy, či dodávateľ účtuje alebo neúčtuje cenu s DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='termin_dodania',
            field=models.CharField(blank=True, help_text='Určite termín dodania (dátum alebo slovné určenie)', max_length=30, null=True, verbose_name='Termín dodania'),
        ),
        migrations.AlterField(
            model_name='objednavkazmluva',
            name='cislo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='objednavkazmluva',
            name='predmet',
            field=models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'Kávovar Saeco' alebo 'Servisná podpora RS Beliana'", max_length=100, null=True, verbose_name='Predmet'),
        ),
        migrations.AlterField(
            model_name='objednavkazmluva',
            name='vybavuje2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objednavkazmluva_requests_created', to='uctovnictvo.vybavovatel', verbose_name='Vybavuje'),
        ),
    ]
