# Generated by Django 3.2.4 on 2024-10-31 16:56

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0208_auto_20241031_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='datum_vytvorenia',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia objednávky. Vypĺňa sa automaticky akciou 'Vytvoriť súbor objednávky'", null=True, verbose_name='Dátum vytvorenia'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='predpokladana_cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='subor_objednavky',
            field=models.TextField(blank=True, help_text="Súbor s objednávkou a krycím listom. Generuje sa akciou 'Vytvoriť súbor objednávky'", max_length=100, null=True, verbose_name='Súbor objednávky'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='subor_prilohy',
            field=models.TextField(blank=True, help_text='Súbor s prílohou k objednávke, napr. ponuka od dodávateľa', max_length=100, null=True, verbose_name='Súbor prílohy'),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='subor_ziadanky',
            field=models.TextField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť súbor žiadanky'", max_length=100, null=True, verbose_name='Súbor žiadanky'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='datum_vytvorenia',
            field=models.DateField(blank=True, help_text="Dátum vytvorenia objednávky. Vypĺňa sa automaticky akciou 'Vytvoriť súbor objednávky'", null=True, verbose_name='Dátum vytvorenia'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='predpokladana_cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='subor_objednavky',
            field=models.FileField(blank=True, help_text="Súbor s objednávkou a krycím listom. Generuje sa akciou 'Vytvoriť súbor objednávky'", null=True, upload_to=uctovnictvo.models.objednavka_upload_location, verbose_name='Súbor objednávky'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='subor_prilohy',
            field=models.FileField(blank=True, help_text='Súbor s prílohou k objednávke, napr. ponuka od dodávateľa', null=True, upload_to=uctovnictvo.models.objednavka_upload_location, verbose_name='Súbor prílohy'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='subor_ziadanky',
            field=models.FileField(blank=True, help_text="Súbor so žiadankou a krycím listom. Generuje sa akciou 'Vytvoriť súbor žiadanky'", null=True, upload_to=uctovnictvo.models.objednavka_upload_location, verbose_name='Súbor žiadanky'),
        ),
    ]
