# Generated by Django 3.2.4 on 2024-12-30 09:51

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0211_auto_20241216_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='dodaci_list',
            field=models.TextField(blank=True, help_text='Súbor s dodacím listom alebo inými údajmi priloženými k faktúre', max_length=100, null=True, verbose_name='Dodací list'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='dodaci_list',
            field=models.FileField(blank=True, help_text='Súbor s dodacím listom alebo inými údajmi priloženými k faktúre', null=True, upload_to=uctovnictvo.models.prijata_faktura_upload_location, verbose_name='Dodací list'),
        ),
    ]
