# Generated by Django 3.2.4 on 2025-01-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0216_auto_20250126_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodavatel',
            name='sadzbadph',
            field=models.CharField(blank=True, choices=[('23', '23 %'), ('20', '20 %'), ('19', '19 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH, ktorú dodávateľ účtuje.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
        migrations.AddField(
            model_name='historicaldodavatel',
            name='sadzbadph',
            field=models.CharField(blank=True, choices=[('23', '23 %'), ('20', '20 %'), ('19', '19 %'), ('10', '10 %'), ('5', '5 %'), ('0', '0 %')], help_text='Uveďte sadzbu DPH, ktorú dodávateľ účtuje.', max_length=10, null=True, verbose_name='Sadzba DPH'),
        ),
    ]
