# Generated by Django 3.2.4 on 2025-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0217_auto_20250131_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='dohoda',
            name='dalsie_podmienky',
            field=models.CharField(blank=True, help_text='Ďalšie dohodnuté podmienky (napr. náhrada cestovných výdavkov, výkaz prác a\xa0odpracovaných hodín, dohoda o\xa0hmotnej zodpovednosti a\xa0iné) podľa § 224 Zákonníka práce', max_length=200, null=True, verbose_name='Ďalšie podmienky'),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='dalsie_podmienky',
            field=models.CharField(blank=True, help_text='Ďalšie dohodnuté podmienky (napr. náhrada cestovných výdavkov, výkaz prác a\xa0odpracovaných hodín, dohoda o\xa0hmotnej zodpovednosti a\xa0iné) podľa § 224 Zákonníka práce', max_length=200, null=True, verbose_name='Ďalšie podmienky'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='dalsie_podmienky',
            field=models.CharField(blank=True, help_text='Ďalšie dohodnuté podmienky (napr. náhrada cestovných výdavkov, výkaz prác a\xa0odpracovaných hodín, dohoda o\xa0hmotnej zodpovednosti a\xa0iné) podľa § 224 Zákonníka práce', max_length=200, null=True, verbose_name='Ďalšie podmienky'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='dalsie_podmienky',
            field=models.CharField(blank=True, help_text='Ďalšie dohodnuté podmienky (napr. náhrada cestovných výdavkov, výkaz prác a\xa0odpracovaných hodín, dohoda o\xa0hmotnej zodpovednosti a\xa0iné) podľa § 224 Zákonníka práce', max_length=200, null=True, verbose_name='Ďalšie podmienky'),
        ),
    ]
