# Generated by Django 3.2.4 on 2025-02-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0218_auto_20250203_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dohoda',
            name='dalsie_podmienky',
        ),
        migrations.RemoveField(
            model_name='historicaldobps',
            name='dalsie_podmienky',
        ),
        migrations.RemoveField(
            model_name='historicaldopc',
            name='dalsie_podmienky',
        ),
        migrations.RemoveField(
            model_name='historicaldovp',
            name='dalsie_podmienky',
        ),
    ]
