# Generated by Django 3.2.4 on 2025-02-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0220_auto_20250217_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalodmenaoprava',
            name='typ',
            field=models.CharField(choices=[('odmena', 'Odmena'), ('odmenasubor', 'XLSX súbor s odmenami'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie'), ('opravazr', 'Oprava zrážky - plat'), ('opravaZrDoPC', 'Oprava zrážky - DoPC'), ('opravaZrDoVP', 'Oprava zrážky - DoVP'), ('opravazrcerp', 'Oprava zrážky - plat (len pre čerpanie rozpočtu)'), ('odstupne', 'Odstupné'), ('odchodne', 'Odchodné'), ('dovolenka', 'Náhrada mzdy - dovolenka')], help_text='Uveďte, či ide o odmenu, súbor s odmenami alebo opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Typ záznamu'),
        ),
        migrations.AlterField(
            model_name='odmenaoprava',
            name='typ',
            field=models.CharField(choices=[('odmena', 'Odmena'), ('odmenasubor', 'XLSX súbor s odmenami'), ('opravatarif', 'Oprava tarifný plat'), ('opravaosob', 'Oprava osobný pr.'), ('opravariad', 'Oprava pr. za riadenie'), ('opravazr', 'Oprava zrážky - plat'), ('opravaZrDoPC', 'Oprava zrážky - DoPC'), ('opravaZrDoVP', 'Oprava zrážky - DoVP'), ('opravazrcerp', 'Oprava zrážky - plat (len pre čerpanie rozpočtu)'), ('odstupne', 'Odstupné'), ('odchodne', 'Odchodné'), ('dovolenka', 'Náhrada mzdy - dovolenka')], help_text='Uveďte, či ide o odmenu, súbor s odmenami alebo opravu vyplatenej mzdy', max_length=20, null=True, verbose_name='Typ záznamu'),
        ),
    ]
