# Generated by Django 3.2.4 on 2025-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0221_auto_20250217_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprispevoknarekreaciu',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Príspevok na rekreáciu šport'},
        ),
        migrations.AlterModelOptions(
            name='prispevoknarekreaciu',
            options={'verbose_name': 'Príspevok na rekreáciu šport', 'verbose_name_plural': 'PaM - Príspevky na rekreáciu šport'},
        ),
        migrations.AddField(
            model_name='historicalprispevoknarekreaciu',
            name='typ_prispevku',
            field=models.CharField(choices=[('rekreacia', 'Na rekreáciu'), ('sport', 'Na šport')], max_length=15, null=True, verbose_name='Typ príspevku'),
        ),
        migrations.AddField(
            model_name='prispevoknarekreaciu',
            name='typ_prispevku',
            field=models.CharField(choices=[('rekreacia', 'Na rekreáciu'), ('sport', 'Na šport')], max_length=15, null=True, verbose_name='Typ príspevku'),
        ),
        migrations.AlterField(
            model_name='historicalprispevoknarekreaciu',
            name='prispevok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška príspevku určená mzdovou učtárňou (záporné číslo).', max_digits=8, null=True, verbose_name='Na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='prispevoknarekreaciu',
            name='prispevok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Výška príspevku určená mzdovou učtárňou (záporné číslo).', max_digits=8, null=True, verbose_name='Na vyplatenie'),
        ),
    ]
