# Generated by Django 3.2.4 on 2025-03-13 16:46

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0223_auto_20250309_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvystavenafaktura',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vystavená faktúra SPP'},
        ),
        migrations.AlterModelOptions(
            name='vystavenafaktura',
            options={'verbose_name': 'Vystavená faktúra SPP', 'verbose_name_plural': 'Faktúry - Vystavené faktúry SPP'},
        ),
        migrations.AddField(
            model_name='historicalvystavenafaktura',
            name='scislo',
            field=models.CharField(help_text='Zadajte číslo faktúry z SPP', max_length=50, null=True, verbose_name='Číslo SPP'),
        ),
        migrations.AddField(
            model_name='vystavenafaktura',
            name='scislo',
            field=models.CharField(help_text='Zadajte číslo faktúry z SPP', max_length=50, null=True, verbose_name='Číslo SPP'),
        ),
        migrations.AlterField(
            model_name='historicalnajomnefaktura',
            name='cislo_softip',
            field=models.CharField(help_text='Zadajte číslo faktúry zo Softipu', max_length=25, null=True, verbose_name='Číslo Softip'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='dcislo',
            field=models.CharField(blank=True, help_text='Zadajte číslo faktúry zo Softipu', max_length=50, null=True, verbose_name='Číslo Softip'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='zo_softipu',
            field=models.TextField(blank=True, help_text='Faktúra pre odberateľa, vytvorená v Softipe', max_length=100, null=True, verbose_name='Faktúra zo Softipu'),
        ),
        migrations.AlterField(
            model_name='najomnefaktura',
            name='cislo_softip',
            field=models.CharField(help_text='Zadajte číslo faktúry zo Softipu', max_length=25, null=True, verbose_name='Číslo Softip'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='dcislo',
            field=models.CharField(blank=True, help_text='Zadajte číslo faktúry zo Softipu', max_length=50, null=True, verbose_name='Číslo Softip'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='zo_softipu',
            field=models.FileField(blank=True, help_text='Faktúra pre odberateľa, vytvorená v Softipe', null=True, upload_to=uctovnictvo.models.vystavena_faktura_upload_location, verbose_name='Faktúra zo Softipu'),
        ),
    ]
