# Generated by Django 3.2.4 on 2025-03-27 10:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0224_auto_20250313_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpravidelnaplatba',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AlterField(
            model_name='historicalvystavenafaktura',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AlterField(
            model_name='pravidelnaplatba',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
        migrations.AlterField(
            model_name='vystavenafaktura',
            name='podiel2',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), help_text='Podiel druhého zdroja/zákazky v prípade delenia faktúry, inak 0 %', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Podiel 2'),
        ),
    ]
