# Generated by Django 3.2.4 on 2025-05-15 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uctovnictvo', '0225_auto_20250327_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 6 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 23 / 30193300-1</strong> <br />Cena za jednotlivé položky a celková suma sa dopočíta.</li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 6 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 23 / 30193300-1</strong> <br />Cena za jednotlivé položky a celková suma sa dopočíta.</li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.CreateModel(
            name='ObjednavkaKZmluve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo')),
                ('predmet', models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'Kávovar Saeco' alebo 'Servisná podpora RS Beliana'", max_length=100, null=True, verbose_name='Predmet')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('objednane_polozky', models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 6 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 23 / 30193300-1</strong> <br />Cena za jednotlivé položky a celková suma sa dopočíta.</li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Text žiadanky / Objednané položky')),
                ('predpokladana_cena', models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena')),
                ('datum_odoslania', models.DateField(blank=True, help_text='Zadajte dátum odoslania objednávky dodávateľovi. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania')),
                ('datum_vytvorenia', models.DateField(blank=True, help_text="Dátum vytvorenia objednávky. Vypĺňa sa automaticky akciou 'Vytvoriť súbor objednávky'", null=True, verbose_name='Dátum vytvorenia')),
                ('subor_objednavky', models.FileField(blank=True, help_text="Súbor s objednávkou a krycím listom. Generuje sa akciou 'Vytvoriť súbor objednávky'", null=True, upload_to=uctovnictvo.models.objednavka_upload_location, verbose_name='Súbor objednávky')),
                ('subor_prilohy', models.FileField(blank=True, help_text='Súbor s prílohou k objednávke, napr. ponuka od dodávateľa', null=True, upload_to=uctovnictvo.models.objednavka_upload_location, verbose_name='Súbor prílohy')),
                ('termin_dodania', models.CharField(blank=True, help_text='Určite termín dodania (dátum alebo slovné určenie)', max_length=30, null=True, verbose_name='Termín dodania')),
                ('zmluva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objednavkakzmluve_zmluva', to='uctovnictvo.zmluva', verbose_name='Zmluva')),
            ],
            options={
                'verbose_name': 'Objednávka k zmluve',
                'verbose_name_plural': 'Faktúry - Objednávky k zmluve',
            },
        ),
        migrations.CreateModel(
            name='HistoricalObjednavkaKZmluve',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo')),
                ('predmet', models.CharField(blank=True, help_text="Zadajte stručný popis, napr. 'Kávovar Saeco' alebo 'Servisná podpora RS Beliana'", max_length=100, null=True, verbose_name='Predmet')),
                ('poznamka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('objednane_polozky', models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 6 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 23 / 30193300-1</strong> <br />Cena za jednotlivé položky a celková suma sa dopočíta.</li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Text žiadanky / Objednané položky')),
                ('predpokladana_cena', models.DecimalField(blank=True, decimal_places=2, help_text='Zadajte predpokladanú cenu bez DPH.', max_digits=8, null=True, verbose_name='Predpokladaná cena')),
                ('datum_odoslania', models.DateField(blank=True, help_text='Zadajte dátum odoslania objednávky dodávateľovi. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania')),
                ('datum_vytvorenia', models.DateField(blank=True, help_text="Dátum vytvorenia objednávky. Vypĺňa sa automaticky akciou 'Vytvoriť súbor objednávky'", null=True, verbose_name='Dátum vytvorenia')),
                ('subor_objednavky', models.TextField(blank=True, help_text="Súbor s objednávkou a krycím listom. Generuje sa akciou 'Vytvoriť súbor objednávky'", max_length=100, null=True, verbose_name='Súbor objednávky')),
                ('subor_prilohy', models.TextField(blank=True, help_text='Súbor s prílohou k objednávke, napr. ponuka od dodávateľa', max_length=100, null=True, verbose_name='Súbor prílohy')),
                ('termin_dodania', models.CharField(blank=True, help_text='Určite termín dodania (dátum alebo slovné určenie)', max_length=30, null=True, verbose_name='Termín dodania')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zmluva', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.zmluva', verbose_name='Zmluva')),
            ],
            options={
                'verbose_name': 'historical Objednávka k zmluve',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
