# Generated by Django 3.2.4 on 2025-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0226_auto_20250515_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objednavkakzmluve',
            name='zmluva',
        ),
        migrations.AlterField(
            model_name='dohoda',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldobps',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldopc',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicaldovp',
            name='dohoda_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania dohody na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Dohodárovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicalobjednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 6 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 23 / 30193300-1</strong> <br />Cena za jednotlivé položky a celková suma sa dopočíta.</li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Text žiadanky / Objednané položky'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='objednane_polozky',
            field=models.TextField(blank=True, help_text='<p>Na vytvorenie žiadanky (krok 1) vložte text žiadanky (voľný text). Na vytvorenie objednávky (krok 2) po riadkoch zadajte objednávané položky:</p>                <ol>                <li>možnosť: so 6 poľami oddelenými bodkočiarkou alebo lomkou / v poradí: <b>názov položky</b> / <b>merná jednotka</b> - ks, kg, l, m, m2, m3 / <b>množstvo</b> / <b>cena za jednotku bez DPH / DPH / CPV kód</b>, napr. <strong>Euroobal A4 / bal / 10 / 7,50 / 23 / 30193300-1</strong> <br />Cena za jednotlivé položky a celková suma sa dopočíta.</li>                <li>možnosť: ako jednoduchý text s jednou bodkočiarkou alebo lomkou, za ktorou nasleduje CPV kód, napr. <strong>Objednávame tovar podľa  priloženého zoznamu; 45321000-3</strong>.<br />Súbor takejto ponuky alebo zoznamu vložte do poľa <em>Súbor prílohy</em> a <strong>predpokladanú cenu bez DPH</strong> vložte do poľa <em>Predpokladaná cena</em>.</li>                </ol>', max_length=5000, null=True, verbose_name='Text žiadanky / Objednané položky'),
        ),
        migrations.DeleteModel(
            name='HistoricalObjednavkaKZmluve',
        ),
        migrations.DeleteModel(
            name='ObjednavkaKZmluve',
        ),
    ]
