# Generated by Django 3.2.4 on 2025-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0227_auto_20250519_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldohodar',
            name='typ_doch',
            field=models.CharField(blank=True, choices=[('starobny', 'starobný'), ('invalidny', 'invalidný (len dohodári)'), ('invalidny30', 'invalidný 30 % (len zamestnanci)'), ('invalidny70', 'invalidný 70 % (len zamestnanci)'), ('invalidny_vysl', 'invalidný výsluhový'), ('vysluhovy', 'výsluhový po dovŕšení dôchodkového veku'), ('predcasny', 'predčasný')], max_length=100, null=True, verbose_name='Typ dôchodku'),
        ),
        migrations.AlterField(
            model_name='historicalzamestnanec',
            name='typ_doch',
            field=models.CharField(blank=True, choices=[('starobny', 'starobný'), ('invalidny', 'invalidný (len dohodári)'), ('invalidny30', 'invalidný 30 % (len zamestnanci)'), ('invalidny70', 'invalidný 70 % (len zamestnanci)'), ('invalidny_vysl', 'invalidný výsluhový'), ('vysluhovy', 'výsluhový po dovŕšení dôchodkového veku'), ('predcasny', 'predčasný')], max_length=100, null=True, verbose_name='Typ dôchodku'),
        ),
        migrations.AlterField(
            model_name='zamestnanecdohodar',
            name='typ_doch',
            field=models.CharField(blank=True, choices=[('starobny', 'starobný'), ('invalidny', 'invalidný (len dohodári)'), ('invalidny30', 'invalidný 30 % (len zamestnanci)'), ('invalidny70', 'invalidný 70 % (len zamestnanci)'), ('invalidny_vysl', 'invalidný výsluhový'), ('vysluhovy', 'výsluhový po dovŕšení dôchodkového veku'), ('predcasny', 'predčasný')], max_length=100, null=True, verbose_name='Typ dôchodku'),
        ),
    ]
