# Generated by Django 3.2.4 on 2025-06-09 13:15

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0228_auto_20250521_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzmluva',
            name='subor_kl',
            field=models.TextField(blank=True, help_text="Súbor s krycím listom. Generuje sa akciou 'Vytvoriť krycí list'.", max_length=100, null=True, verbose_name='Krycí list'),
        ),
        migrations.AddField(
            model_name='zmluva',
            name='subor_kl',
            field=models.FileField(blank=True, help_text="Súbor s krycím listom. Generuje sa akciou 'Vytvoriť krycí list'.", null=True, upload_to=uctovnictvo.models.zmluvy_upload_location, verbose_name='Krycí list'),
        ),
    ]
