# Generated by Django 3.2.4 on 2025-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0229_auto_20250609_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzmluva',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania zmluvy zmluvnej strane. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AddField(
            model_name='zmluva',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania zmluvy zmluvnej strane. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
    ]
