# Generated by Django 3.2.4 on 2025-06-10 10:19

from django.db import migrations, models
import uctovnictvo.models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0230_auto_20250610_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnajomnazmluva',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania zmluvy nájomníkovi. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AddField(
            model_name='historicalnajomnazmluva',
            name='subor_kl',
            field=models.TextField(blank=True, help_text="Súbor s krycím listom. Generuje sa akciou 'Vytvoriť krycí list'.", max_length=100, null=True, verbose_name='Krycí list'),
        ),
        migrations.AddField(
            model_name='najomnazmluva',
            name='datum_odoslania',
            field=models.DateField(blank=True, help_text='Zadajte dátum odoslania zmluvy nájomníkovi. Po zadaní dátumu sa vytvorí záznam v Denníku prijatej a odoslanej pošty', null=True, verbose_name='Dátum odoslania'),
        ),
        migrations.AddField(
            model_name='najomnazmluva',
            name='subor_kl',
            field=models.FileField(blank=True, help_text="Súbor s krycím listom. Generuje sa akciou 'Vytvoriť krycí list'.", null=True, upload_to=uctovnictvo.models.zmluvy_upload_location, verbose_name='Krycí list'),
        ),
    ]
