# Generated by Django 3.2.4 on 2025-06-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0231_auto_20250610_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnajomnazmluva',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Nájomná zmluva'},
        ),
        migrations.AlterModelOptions(
            name='najomnazmluva',
            options={'verbose_name': 'Nájomná zmluva', 'verbose_name_plural': 'Prenájom - Zmluvy'},
        ),
    ]
