# Generated by Django 3.2.4 on 2025-09-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0233_auto_20250827_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprijatafaktura',
            name='objednavka_zmluva2',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vyplnit len ak treba', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uctovnictvo.objednavkazmluva', verbose_name='Druhá objednávka / zmluva'),
        ),
        migrations.AddField(
            model_name='prijatafaktura',
            name='objednavka_zmluva2',
            field=models.ForeignKey(blank=True, help_text='Vyplnit len ak treba', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prijatafaktura_faktury2', to='uctovnictvo.objednavkazmluva', verbose_name='Druhá objednávka / zmluva'),
        ),
    ]
