# Generated by Django 3.2.4 on 2025-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0234_auto_20250919_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprijatafaktura',
            name='objednavka_zmluva2',
        ),
        migrations.RemoveField(
            model_name='prijatafaktura',
            name='objednavka_zmluva2',
        ),
        migrations.AlterField(
            model_name='historicalnepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(blank=True, choices=[('materská', 'MD/RD'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Platené zdr. voľno podľa KZ'), ('pkz', 'Pracovné voľno podľa KZ vyššieho stupňa'), ('pv', 'Pracovné voľno (PV, P, S, KZVS, POH)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('riaditelskevolno', 'Riaditelské voľno'), ('pracadoma', 'Práca na doma'), ('skolenie', 'Školenie'), ('zrusena', 'Zrušená')], help_text="Ak sa tento záznam nedostal do Softipu a je to chyba, zvoľte 'Zrušená' v poli poznámka uveďte dôvod.", max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
        migrations.AlterField(
            model_name='nepritomnost',
            name='nepritomnost_typ',
            field=models.CharField(blank=True, choices=[('materská', 'MD/RD'), ('ocr', 'OČR'), ('pn', 'PN'), ('dovolenka', 'Dovolenka'), ('dovolenka2', 'Poldeň dovolenky'), ('lekar', 'Návšteva u lekára (L)'), ('lekardoprovod', 'Doprovod k lekárovi (L/D)'), ('pzv', 'Platené zdr. voľno podľa KZ'), ('pkz', 'Pracovné voľno podľa KZ vyššieho stupňa'), ('pv', 'Pracovné voľno (PV, P, S, KZVS, POH)'), ('neplatene', 'Neplatené voľno'), ('sluzobna', 'Služobná cesta'), ('riaditelskevolno', 'Riaditelské voľno'), ('pracadoma', 'Práca na doma'), ('skolenie', 'Školenie'), ('zrusena', 'Zrušená')], help_text="Ak sa tento záznam nedostal do Softipu a je to chyba, zvoľte 'Zrušená' v poli poznámka uveďte dôvod.", max_length=20, null=True, verbose_name='Typ neprítomnosti'),
        ),
    ]
