# Generated by Django 3.2.4 on 2026-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0236_auto_20260219_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprijatafaktura',
            name='sumacm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="V prípade uvedenia sumy v cudzej mene vložte do poľa 'Suma' nulu. Pole 'Suma vypňte až bude známa skutočne uhradená suma v EUR<br />Vložte sumu s DPH (zápornú, ak ide o platbu).", max_digits=8, null=True, verbose_name='Suma v cudzej mene (s DPH)'),
        ),
        migrations.AlterField(
            model_name='prijatafaktura',
            name='sumacm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="V prípade uvedenia sumy v cudzej mene vložte do poľa 'Suma' nulu. Pole 'Suma vypňte až bude známa skutočne uhradená suma v EUR<br />Vložte sumu s DPH (zápornú, ak ide o platbu).", max_digits=8, null=True, verbose_name='Suma v cudzej mene (s DPH)'),
        ),
    ]
