"""
Django settings for beliana project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os, dotenv
from datetime import date
from pathlib import Path
import mimetypes


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add .env variables anywhere before SECRET_KEY and other local stupp
dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# UPDATE secret key
SECRET_KEY = os.environ['SECRET_KEY'] # Instead of your actual secret key

DEBUG = os.environ['DEBUG']
DEPLOY_STATE = os.environ['DEPLOY_STATE']

ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS']

#Type of automatically added primary key, if none is specified
#Since Django 3.2 the default has been changed to 'django.db.models.BigAutoField'
#Specify the type here to get rid of the warning i
#    Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'. 
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

INSTALLED_APPS = [
    'dennik.apps.DennikConfig',
    'zmluvy.apps.ZmluvyConfig',
    'uctovnictvo.apps.UctovnictvoConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simple_history',
    'rangefilter',
    'django_db_logger',
    'import_export',
    'admin_totals',
    'django_crontab',
    'admin_export_action',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'beliana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'beliana.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'sk-sk'

TIME_ZONE = 'Europe/Bratislava'

USE_I18N = True

USE_L10N = True

USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

#https://automationpanda.com/2018/04/21/django-admin-translations/
#By default, message files will be generated into locale directories for each app with strings marked for translation.
#You may optionally want to set LOCALE_PATHS to change the paths. For example, it may be easiest to put all 
#message files into one directory like this, rather than splitting them out by app:

#LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
    },
    'loggers': {
        'db': {
            'handlers': ['db_log'],
            'level': 'DEBUG'
        }
    }
}

CRONJOBS = [
    ('33 3 * * *', 'zmluvy.cron.notifikacie_FU')
]

#https://pypi.org/project/django-admin-export-action/
#see class PlatbaAutorskaOdmenaAdmin
ADMIN_EXPORT_ACTION = {
    'ENABLE_SITEWIDE': False
}

#Parametre
ODVODY_VYNIMKA = 200    #Vyňatá mesačná suma v prípade, ak dohodár (dôchodca alebo študent) o ňu požiada
DAN_Z_PRIJMU = 19       #Daň z príjmu, 19 %
DPH = 20                #DPH
LITFOND_ODVOD = 2       #Odvod do fondov (napr. Literárny), do konca r. 2022 0, inak 2 %
LITFOND_ODVOD = 0       #Od 1. 7. 2023 odvod zušený. Parameter nechávame, čo keď ho znova zavedú
MIN_VYPLATIT = 10       #minimálna suma v Eur, ktorá sa vypláca v prípade autorov
#UCET_ENU = "SK36 8180 0000 0070 0061 8734 - Beliana"    #nahradený
UCET_ENU = "SK08 8180 0000 0070 0066 7544"
UCET_LITFOND  = "SK47 0200 0000 0012 2545 9853" #Literárny fond 

STRAVNE_HOD = 4         #Minimálny odpracovaný čas za deň, aby zamestnanec dostal stravné

#http://www.fvu.sk/stranka/clanok/6-ochranna-organizacia-autorska
UCET_FVU  = "SK02 0200 0100 1400 0973 5062"     #Fond výtvarných umení
KS_FVU = "0558"
VS_FVU = "922 859"

UCET_FIN_URAD = "SK61 8180 5002 6780 2710 3305"
def PN1(month):         #náhrada mzdy za prvé 3 dni PN-ky
    if month < date(2023,1,1):
        return 55
    else: 
        return 80
def PN2(month):         #náhrada mzdy za dni 3 - 10 PN-ky
    return 80
DDS_PRISPEVOK=2         #Doplnkové dôchodkové sporenie, %
SOCFOND_PRISPEVOK=1.5   #Sociálny fond, %

UVAZOK_TYZDENNE=37.5

#Maximum vymeriavacích základov pre sociálne poistenie zamestnancov
#https://www.socpoist.sk/navigacia/768-tabulky-platenia-poistneho
MAX_VZ ={
        2021:7644,
        2022:7931,
        2023:8477,
        2024:9128
        }
#Ak má zamestnanec vyplatený príjem počas vylúčiteľnej doby (PN je vylučiteľná doba), ktorá trvá celý mesiac, zamestnávateľ odvedie iba úrazové a zdravotné poistenie z celého dosiahnutého zdaniteľného príjmu. Pozri https://www.kros.sk/forum/odmena-pocas-cerpania-pn/

#Predvolené zobrazenie dátumu v admin
from django.conf.locale.sk import formats as sk_formats
sk_formats.DATE_FORMAT = "d.m.Y"


# Právo na použitie modulu import_export
# Importovanie je možné pre OsobaAutor
IMPORT_EXPORT_IMPORT_PERMISSION_CODE='add'
IMPORT_EXPORT_EXPORT_PERMISSION_CODE='add'

# Beliana specific settings
DATA_DIR = os.environ['DATA_DIR']
#TEMPLATES_DIR = os.environ['TEMPLATES_DIR']
#ROYALTIES_DIR = os.environ['ROYALTIES_DIR']
CONTRACTS_DIR_NAME = os.environ['CONTRACTS_DIR_NAME']
RLTS_DIR_NAME = os.environ['RLTS_DIR_NAME']
TMPLTS_DIR_NAME = os.environ["TMPLTS_DIR_NAME"]
AUTHORS_CONTRACT_TEMPLATE = os.environ['AUTHORS_CONTRACT_TEMPLATE']
TAX_AGMT_DIR_NAME = os.environ["TAX_AGMT_DIR_NAME"]


if "UCTOVNICKA_CSC" in os.environ:
    UCTOVNICKA_CSC = os.environ["UCTOVNICKA_CSC"]
else:
    UCTOVNICKA_CSC = "Účtovníčka CSČ"

# potrebné kvôli generovaniu zmlúv
MEDIA_ROOT = os.environ['MEDIA_ROOT']
#URL MEDIA_ROOT bude 127.0.0.1:8000/subory/...
MEDIA_URL = '/subory/'
CONTRACTS_DIR = os.path.join(MEDIA_ROOT,CONTRACTS_DIR_NAME)
RLTS_DIR = os.path.join(MEDIA_ROOT,RLTS_DIR_NAME)

# App Uctovnictvo
# pripojí sa za MEDIA_ROOT
BEZ_PRIKAZU_DIR="BezPrikazu"
PLATOBNE_PRIKAZY_DIR="PlatobnePrikazy"
PLATOVE_VYMERY_DIR="PlatoveVymery"
PRILOHA_DIR="Prilohy"
DOHODY_DIR="Dohody"
ZAMESTNANCI_DIR="Zamestnanci"
ODMENY_DIR="Odmeny"
OBJEDNAVKY_DIR="Objednavky"
PRIJATEFAKTURY_DIR="PrijateFaktury"
VYSTAVENEFAKTURY_DIR="VystaveneFaktury"
NAJOMNEFAKTURY_DIR="NajomneFaktury"
STRAVNE_DIR="Stravne"
POKLADNA_DIR="Pokladna"
REKREACIA_DIR="PrispevokNaRekreaciu"
NEPRITOMNOST_DIR="Nepritomnost"

#App denniky
FORM_DIR_NAME="HromadneDokumenty"
DENNIK_DIR_NAME="DennikSubory"
PLATOVA_REKAPITULACIA_DIR_NAME="PlatovaRekapitulacia"

# Mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# https://www.sitepoint.com/django-send-email/
# ak netreba autentifikáciu (napr. v siete akadémie):
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_PORT = os.environ['EMAIL_PORT']
#inak pridať
EMAIL_USE_SSL = os.environ['EMAIL_USE_SSL']
EMAIL_USE_TLS = os.environ['EMAIL_USE_TLS']
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']

# Základné údaje o serveri. Používané pri odosielaní notifikačných mailov
SITE_URL = "http://samba.enu.sav.sk:8000/"
SITE_HOST = "samba"

#Vedenie 
HEAD_NAME=os.environ['HEAD_NAME']
HEAD_ROLE=os.environ['HEAD_ROLE']
#kontaktná osoba v učtárni
UCTAREN_NAME=os.environ['UCTAREN_NAME']

mimetypes.add_type("application/vnd.oasis.opendocument.text", ".fodt", True)
