# Generated by Django 3.1.6 on 2021-02-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_uid', models.IntegerField()),
                ('rs_login', models.CharField(max_length=100)),
                ('titul_pred_menom', models.CharField(max_length=100, verbose_name='Titul pred menom')),
                ('meno', models.CharField(max_length=200, verbose_name='Meno')),
                ('priezvisko', models.CharField(max_length=200, verbose_name='Priezvisko')),
                ('titul_za_menom', models.CharField(max_length=100, verbose_name='Titul za menom')),
                ('posobisko', models.CharField(max_length=200, verbose_name='Pôsobisko')),
            ],
        ),
        migrations.CreateModel(
            name='Zmluva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_zmluvy', models.CharField(max_length=50, verbose_name='číslo zmluvy')),
                ('zmluvna_strana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zmluvy.osoba')),
            ],
        ),
    ]
