# Generated by Django 3.1.6 on 2021-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='email',
            field=models.CharField(default='neurčená', max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osoba',
            name='rs_login',
            field=models.CharField(max_length=100, verbose_name='Login v RS'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='rs_uid',
            field=models.IntegerField(verbose_name='Uid v RS'),
        ),
        migrations.AlterField(
            model_name='zmluva',
            name='cislo_zmluvy',
            field=models.CharField(max_length=50, verbose_name='Číslo zmluvy'),
        ),
    ]
