# Generated by Django 3.2.6 on 2021-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='obdobie',
            field=models.CharField(default='2021-10-29', help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, verbose_name='Identifikátor vyplácania'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='obdobie',
            field=models.CharField(default='2021-10-29', help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, verbose_name='Identifikátor vyplácania'),
        ),
    ]
