# Generated by Django 3.1.6 on 2021-02-10 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0002_auto_20210210_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='datum_pridania',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dátum pridania'),
            preserve_default=False,
        ),
    ]
