# Generated by Django 3.1.6 on 2021-02-10 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0003_osoba_datum_pridania'),
    ]

    operations = [
        migrations.AddField(
            model_name='zmluva',
            name='datum_pridania',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dátum pridania'),
            preserve_default=False,
        ),
    ]
