# Generated by Django 3.1.6 on 2021-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0005_auto_20210210_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='datum_aktualizacie',
            field=models.DateTimeField(auto_now=True, verbose_name='Dátum aktualizácie'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='datum_pridania',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dátum pridania'),
        ),
        migrations.AlterField(
            model_name='zmluva',
            name='datum_aktualizacie',
            field=models.DateTimeField(auto_now=True, verbose_name='Dátum aktualizácie'),
        ),
        migrations.AlterField(
            model_name='zmluva',
            name='datum_pridania',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dátum pridania'),
        ),
    ]
