# Generated by Django 3.2.6 on 2021-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0006_auto_20211110_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. Pokiaľ platba autora neprešla, pred vytvorení finálneho prehľadu ho zo zoznamu odstráňte", max_length=2500, null=True, verbose_name='Vyplacaní autori'),
        ),
        migrations.AddField(
            model_name='platbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. Pokiaľ platba autora neprešla, pred vytvorení finálneho prehľadu ho zo zoznamu odstráňte", max_length=2500, null=True, verbose_name='Vyplacaní autori'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='obdobie',
            field=models.CharField(default='2021-11-13', help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, verbose_name='Identifikátor vyplácania'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='obdobie',
            field=models.CharField(default='2021-11-13', help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, verbose_name='Identifikátor vyplácania'),
        ),
    ]
