# Generated by Django 3.2.6 on 2021-11-14 11:39

from django.db import migrations, models
import zmluvy.models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0008_auto_20211114_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov (oznámený účtovníčkou)', null=True, verbose_name='Vyplatené THS-kou'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatit_ths',
            field=models.TextField(blank=True, help_text="Súbor je generovaný akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br .>Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Definitívnu verziu súboru (len hárku  <em>Na vyplatenie</em>) treba poslať mailom účtovníčke na vyplatenie.</strong>", max_length=100, null=True, verbose_name='Podklady na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov (oznámený účtovníčkou)', null=True, verbose_name='Vyplatené THS-kou'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatit_ths',
            field=models.FileField(blank=True, help_text="Súbor je generovaný akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br .>Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Definitívnu verziu súboru (len hárku  <em>Na vyplatenie</em>) treba poslať mailom účtovníčke na vyplatenie.</strong>", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Podklady na vyplatenie'),
        ),
    ]
