# Generated by Django 3.2.6 on 2021-11-18 09:45

from django.db import migrations, models
import zmluvy.models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0010_auto_20211116_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_oznamenia',
            field=models.DateField(blank=True, help_text='Dátum oznámenia nezdanených autorov na finančnú správu (termín: do 15. dňa nasledujýceho mesiaca).', null=True, verbose_name='Oznámené FS)'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov (oznámený účtárňou THS)', null=True, verbose_name='Vyplatené THS-kou'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_zalozenia',
            field=models.DateField(blank=True, help_text='Dátum založenia hárku <em>Po autoroch</em> do šanonov.', null=True, verbose_name='Založené do šanonov'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Krycí list</em> do účtárne THS (internou poštou)</em>', null=True, verbose_name="'Krycí list' odoslaný"),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='na_vyplatenie_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Na vyplatenie</em> do účtárne THS (mailom)</em>', null=True, verbose_name="'Na vyplatenie' odoslané"),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='obdobie',
            field=models.CharField(default='2021-11-18', help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, verbose_name='Identifikátor vyplácania'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie do účtárne THS', null=True, verbose_name='Podklady odoslané'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatene',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br .><strong>Hárok <em>Na vyplatenie</em> treba poslať mailom do účtárne THS na vyplatenie</strong><br .><strong>Hárok <em>Krycí list</em> treba poslať internou poštou na THS</strong><br .> <strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť so šanonov</strong>.", max_length=100, null=True, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatit_ths',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br .>Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Definitívnu verziu súboru (len hárku  <em>Na vyplatenie</em>) treba poslať mailom do účtárne THS na vyplatenie.</strong>", max_length=100, null=True, verbose_name='Podklady na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_oznamenia',
            field=models.DateField(blank=True, help_text='Dátum oznámenia nezdanených autorov na finančnú správu (termín: do 15. dňa nasledujýceho mesiaca).', null=True, verbose_name='Oznámené FS)'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov (oznámený účtárňou THS)', null=True, verbose_name='Vyplatené THS-kou'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_zalozenia',
            field=models.DateField(blank=True, help_text='Dátum založenia hárku <em>Po autoroch</em> do šanonov.', null=True, verbose_name='Založené do šanonov'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Krycí list</em> do účtárne THS (internou poštou)</em>', null=True, verbose_name="'Krycí list' odoslaný"),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='na_vyplatenie_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Na vyplatenie</em> do účtárne THS (mailom)</em>', null=True, verbose_name="'Na vyplatenie' odoslané"),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='obdobie',
            field=models.CharField(default='2021-11-18', help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, verbose_name='Identifikátor vyplácania'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie do účtárne THS', null=True, verbose_name='Podklady odoslané'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatene',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br .><strong>Hárok <em>Na vyplatenie</em> treba poslať mailom do účtárne THS na vyplatenie</strong><br .><strong>Hárok <em>Krycí list</em> treba poslať internou poštou na THS</strong><br .> <strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť so šanonov</strong>.", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatit_ths',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br .>Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Definitívnu verziu súboru (len hárku  <em>Na vyplatenie</em>) treba poslať mailom do účtárne THS na vyplatenie.</strong>", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Podklady na vyplatenie'),
        ),
    ]
