# Generated by Django 3.2.6 on 2021-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0017_auto_20211127_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='obdobie',
            field=models.CharField(help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, null=True, verbose_name='Identifikátor vyplácania'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='obdobie',
            field=models.CharField(help_text='Ako identifikátor vyplácania sa použije dátum jeho vytvorenia', max_length=20, null=True, verbose_name='Identifikátor vyplácania'),
        ),
    ]
