# Generated by Django 3.2.6 on 2021-12-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0018_auto_20211129_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platbaautorskasumar',
            options={'permissions': [('pas_notif_fs', 'Prijímať notifikácie o termínoch FS')], 'verbose_name': 'Vyplácanie aut. honorárov', 'verbose_name_plural': 'Vyplácanie aut. honorárov'},
        ),
    ]
