# Generated by Django 3.2.6 on 2021-12-06 10:50

from django.db import migrations, models
import zmluvy.models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0019_alter_platbaautorskasumar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br /><strong>Pokiaľ platba autora neprešla, pred vytvorením finálneho prehľadu platieb ho zo zoznamu odstráňte</strong>.", max_length=2500, null=True, verbose_name='Vyplácaní autori'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatene',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárok <em>Na vyplatenie</em> treba poslať mailom do účtárne THS na vyplatenie</strong><br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> treba vytlačiť a poslať internou poštou THS-ke</strong><br /><strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť so šanonov</strong>.", max_length=100, null=True, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatit_ths',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Definitívnu verziu súboru (len hárku  <em>Na vyplatenie</em>) treba poslať mailom do účtárne THS na vyplatenie.</strong>", max_length=100, null=True, verbose_name='Podklady na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br /><strong>Pokiaľ platba autora neprešla, pred vytvorením finálneho prehľadu platieb ho zo zoznamu odstráňte</strong>.", max_length=2500, null=True, verbose_name='Vyplácaní autori'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatene',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárok <em>Na vyplatenie</em> treba poslať mailom do účtárne THS na vyplatenie</strong><br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> treba vytlačiť a poslať internou poštou THS-ke</strong><br /><strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť so šanonov</strong>.", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatit_ths',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských odmien pre THS'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Definitívnu verziu súboru (len hárku  <em>Na vyplatenie</em>) treba poslať mailom do účtárne THS na vyplatenie.</strong>", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Podklady na vyplatenie'),
        ),
    ]
