# Generated by Django 3.2.6 on 2021-12-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import zmluvy.models
import zmluvy.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zmluvy', '0020_auto_20211206_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsobaGrafik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankovy_kontakt', models.CharField(blank=True, help_text='Zadajte IBAN účtu autora.', max_length=200, null=True, verbose_name='Bankový kontakt')),
                ('adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – ulica a číslo domu')),
                ('adresa_mesto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – PSČ a mesto')),
                ('adresa_stat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresa – štát')),
                ('koresp_adresa_institucia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Korešpondenčná adresa – institucia')),
                ('koresp_adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Korešpondenčná adresa – ulica a číslo domu')),
                ('koresp_adresa_mesto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Korešpondenčná adresa – PSČ a mesto')),
                ('koresp_adresa_stat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Korešpondenčná adresa – štát')),
                ('datum_aktualizacie', models.DateField(auto_now=True, verbose_name='Dátum aktualizácie')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('titul_pred_menom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titul pred menom')),
                ('meno', models.CharField(max_length=200, verbose_name='Meno')),
                ('priezvisko', models.CharField(max_length=200, verbose_name='Priezvisko')),
                ('titul_za_menom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titul za menom')),
                ('rodne_cislo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rodné číslo')),
                ('zdanit', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Zvoľte 'Nie', ak autor podpísal dohodu o nezdaňovaní. V tom prípade treba vyplniť aj polia 'Dohoda podpísaná' a 'Dohoda o nezdaňovaní'.", max_length=3, null=True, verbose_name='Zdaniť')),
                ('nevyplacat', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Zvoľte 'Áno', ak sa honorár nemá vyplácať (napr. ak autor zomrel a nie je jasné, komu honorár poslať). V poznámke uveďte konkrétny dôvod.", max_length=3, null=True, verbose_name='Nevyplácať')),
                ('datum_dohoda_podpis', models.DateField(blank=True, help_text='Zadajte dátum podpisu dohody o nezdaňovaní.', null=True, verbose_name='Dohoda podpísaná')),
                ('datum_dohoda_oznamenie', models.DateField(blank=True, help_text='Zadajte dátum oznámenia existencie dohody o nezdaňovaní Finančnej správe. Oznámenie sa posiela v termíne do konca januára roku, ktorý nasleduje po roku, keď po prvýkrát nebol honorár zdanený.', null=True, verbose_name='Dohoda oznámená')),
                ('rezident', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Uveďte, či je autor daňovík s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='Poznámka')),
                ('dohodasubor', models.FileField(blank=True, help_text='Vložte pdf súbor so zoskenovanou dohodou o nezdaňovaní.', null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.tax_agmt_path, verbose_name='Dohoda o nezdaňovaní')),
            ],
            options={
                'verbose_name': 'Grafik',
                'verbose_name_plural': 'Grafici',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOsobaGrafik',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bankovy_kontakt', models.CharField(blank=True, help_text='Zadajte IBAN účtu autora.', max_length=200, null=True, verbose_name='Bankový kontakt')),
                ('adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – ulica a číslo domu')),
                ('adresa_mesto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa – PSČ a mesto')),
                ('adresa_stat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresa – štát')),
                ('koresp_adresa_institucia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Korešpondenčná adresa – institucia')),
                ('koresp_adresa_ulica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Korešpondenčná adresa – ulica a číslo domu')),
                ('koresp_adresa_mesto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Korešpondenčná adresa – PSČ a mesto')),
                ('koresp_adresa_stat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Korešpondenčná adresa – štát')),
                ('datum_aktualizacie', models.DateField(blank=True, editable=False, verbose_name='Dátum aktualizácie')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('titul_pred_menom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titul pred menom')),
                ('meno', models.CharField(max_length=200, verbose_name='Meno')),
                ('priezvisko', models.CharField(max_length=200, verbose_name='Priezvisko')),
                ('titul_za_menom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titul za menom')),
                ('rodne_cislo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rodné číslo')),
                ('zdanit', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Zvoľte 'Nie', ak autor podpísal dohodu o nezdaňovaní. V tom prípade treba vyplniť aj polia 'Dohoda podpísaná' a 'Dohoda o nezdaňovaní'.", max_length=3, null=True, verbose_name='Zdaniť')),
                ('nevyplacat', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Zvoľte 'Áno', ak sa honorár nemá vyplácať (napr. ak autor zomrel a nie je jasné, komu honorár poslať). V poznámke uveďte konkrétny dôvod.", max_length=3, null=True, verbose_name='Nevyplácať')),
                ('datum_dohoda_podpis', models.DateField(blank=True, help_text='Zadajte dátum podpisu dohody o nezdaňovaní.', null=True, verbose_name='Dohoda podpísaná')),
                ('datum_dohoda_oznamenie', models.DateField(blank=True, help_text='Zadajte dátum oznámenia existencie dohody o nezdaňovaní Finančnej správe. Oznámenie sa posiela v termíne do konca januára roku, ktorý nasleduje po roku, keď po prvýkrát nebol honorár zdanený.', null=True, verbose_name='Dohoda oznámená')),
                ('rezident', models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Uveďte, či je autor daňovík s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='Poznámka')),
                ('dohodasubor', models.TextField(blank=True, help_text='Vložte pdf súbor so zoskenovanou dohodou o nezdaňovaní.', max_length=100, null=True, verbose_name='Dohoda o nezdaňovaní')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Grafik',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
