# Generated by Django 3.2.6 on 2021-12-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0021_historicalosobagrafik_osobagrafik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalosobaautor',
            name='rezident',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
        migrations.AlterField(
            model_name='historicalosobagrafik',
            name='rezident',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
        migrations.AlterField(
            model_name='osobaautor',
            name='rezident',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
        migrations.AlterField(
            model_name='osobagrafik',
            name='rezident',
            field=models.CharField(blank=True, choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
    ]
