# Generated by Django 3.2.6 on 2021-12-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0022_auto_20211209_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalzmluvaautor',
            old_name='cislo_zmluvy',
            new_name='cislo',
        ),
        migrations.RenameField(
            model_name='zmluvaautor',
            old_name='cislo_zmluvy',
            new_name='cislo',
        ),
    ]
