# Generated by Django 3.2.6 on 2021-12-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import zmluvy.models
import zmluvy.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zmluvy', '0023_auto_20211209_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZmluvaGrafik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo zmluvy')),
                ('datum_pridania', models.DateField(auto_now_add=True, verbose_name='Dátum pridania')),
                ('datum_aktualizacie', models.DateTimeField(auto_now=True, verbose_name='Dátum aktualizácie')),
                ('stav_zmluvy', models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('podpisana_enu', 'Podpísaná EnÚ'), ('odoslana_autorovi', 'Odoslaná autorovi'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20)),
                ('url_zmluvy', models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', verbose_name='URL zmluvy')),
                ('zmluva_odoslana', models.DateField(blank=True, help_text='Dátum odoslania zmluvy na podpis (poštou)', null=True, verbose_name='Odoslaná na podpis ')),
                ('zmluva_vratena', models.DateField(blank=True, help_text='Dátum obdržania podpísanej zmluvy (poštou)', null=True, verbose_name='Vrátená podpísaná ')),
                ('datum_zverejnenia_CRZ', models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň).', null=True, verbose_name='Platná od / dátum CRZ')),
                ('vygenerovana_subor', models.FileField(blank=True, help_text="Súbor zmluvy na poslanie autorovi na podpis, vygenerovaný akciou 'Vytvoriť súbory zmluvy'.", null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.contract_path, verbose_name='Vygenerovaný súbor zmluvy')),
                ('vygenerovana_crz_subor', models.FileField(blank=True, help_text="Anonymizovaný súbor zmluvy na vloženie do CRZ, vygenerovaný akciou 'Vytvoriť súbory zmluvy'.", null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.contract_path, verbose_name='Vygenerovaný súbor zmluvy pre CRZ')),
                ('podpisana_subor', models.FileField(blank=True, help_text='Vložte pdf súbor so zoskenovanou podpísanou zmluvou.', null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.contract_path, verbose_name='Podpísaná zmluva')),
                ('zmluvna_strana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zmluvy', to='zmluvy.osobagrafik')),
            ],
            options={
                'verbose_name': 'Výtvarná zmluva',
                'verbose_name_plural': 'Výtvarné zmluvy',
            },
        ),
        migrations.CreateModel(
            name='HistoricalZmluvaGrafik',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, verbose_name='Číslo zmluvy')),
                ('datum_pridania', models.DateField(blank=True, editable=False, verbose_name='Dátum pridania')),
                ('datum_aktualizacie', models.DateTimeField(blank=True, editable=False, verbose_name='Dátum aktualizácie')),
                ('stav_zmluvy', models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('podpisana_enu', 'Podpísaná EnÚ'), ('odoslana_autorovi', 'Odoslaná autorovi'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20)),
                ('url_zmluvy', models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', verbose_name='URL zmluvy')),
                ('zmluva_odoslana', models.DateField(blank=True, help_text='Dátum odoslania zmluvy na podpis (poštou)', null=True, verbose_name='Odoslaná na podpis ')),
                ('zmluva_vratena', models.DateField(blank=True, help_text='Dátum obdržania podpísanej zmluvy (poštou)', null=True, verbose_name='Vrátená podpísaná ')),
                ('datum_zverejnenia_CRZ', models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň).', null=True, verbose_name='Platná od / dátum CRZ')),
                ('vygenerovana_subor', models.TextField(blank=True, help_text="Súbor zmluvy na poslanie autorovi na podpis, vygenerovaný akciou 'Vytvoriť súbory zmluvy'.", max_length=100, null=True, verbose_name='Vygenerovaný súbor zmluvy')),
                ('vygenerovana_crz_subor', models.TextField(blank=True, help_text="Anonymizovaný súbor zmluvy na vloženie do CRZ, vygenerovaný akciou 'Vytvoriť súbory zmluvy'.", max_length=100, null=True, verbose_name='Vygenerovaný súbor zmluvy pre CRZ')),
                ('podpisana_subor', models.TextField(blank=True, help_text='Vložte pdf súbor so zoskenovanou podpísanou zmluvou.', max_length=100, null=True, verbose_name='Podpísaná zmluva')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zmluvna_strana', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='zmluvy.osobagrafik')),
            ],
            options={
                'verbose_name': 'historical Výtvarná zmluva',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
