# Generated by Django 3.2.6 on 2021-12-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0024_historicalzmluvagrafik_zmluvagrafik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalosobaautor',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Občania SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='historicalosobagrafik',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Občania SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text="Dátum vyplatenia honorárov na základe odoslaných podkladov (oznámený účtárňou THS). <br /><strong>Nasledujúci krok: spustiť akciu 'Vytvoriť finálny prehľad...'</strong>", null=True, verbose_name='Vyplatené THS-kou'),
        ),
        migrations.AlterField(
            model_name='osobaautor',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Občania SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='osobagrafik',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Občania SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='platbaautorskaodmena',
            name='odvod_LF',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Odvod aut. fondu'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text="Dátum vyplatenia honorárov na základe odoslaných podkladov (oznámený účtárňou THS). <br /><strong>Nasledujúci krok: spustiť akciu 'Vytvoriť finálny prehľad...'</strong>", null=True, verbose_name='Vyplatené THS-kou'),
        ),
    ]
