# Generated by Django 3.2.6 on 2021-12-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0025_auto_20211214_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='zmluvna_strana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zmluvagrafik', to='zmluvy.osobagrafik'),
        ),
    ]
