# Generated by Django 3.2.6 on 2021-12-17 17:04

from django.db import migrations, models
import django.db.models.deletion
import zmluvy.models
import zmluvy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0026_alter_zmluvagrafik_zmluvna_strana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platbaautorskaodmena',
            name='datum_uhradenia',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum vyplatenia'),
        ),
        migrations.AlterField(
            model_name='platbaautorskaodmena',
            name='honorar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Honorár'),
        ),
        migrations.AlterField(
            model_name='platbaautorskaodmena',
            name='odvedena_dan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Odvedená daň'),
        ),
        migrations.AlterField(
            model_name='platbaautorskaodmena',
            name='odvod_LF',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Odvod aut. fondu'),
        ),
        migrations.AlterField(
            model_name='platbaautorskaodmena',
            name='uhradena_suma',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Uhradená suma'),
        ),
        migrations.CreateModel(
            name='VytvarnaObjednavkaPlatba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_uhradenia', models.DateField(blank=True, null=True, verbose_name='Dátum vyplatenia')),
                ('honorar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Honorár')),
                ('uhradena_suma', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Uhradená suma')),
                ('odvod_LF', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Odvod aut. fondu')),
                ('odvedena_dan', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Odvedená daň')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo objednávky')),
                ('datum_objednavky', models.DateField(help_text='Dátum vystavenia objednávky', null=True, verbose_name='Dátum objednávky')),
                ('objednane_polozky', models.TextField(help_text='Po riadkoch zadajte objednávané položky so štyrmi poľami oddelenými bodkočiarkou v poradí: <b>Popis</b>; <b>Typ</b>; <b>Množstvo</b>; <b>Cena za jednotku</b>.<br />Ako typ uveďte: mapa, fotografia, čb perovka, farebná kresba.', max_length=5000, null=True, verbose_name='Objednané položky')),
                ('subor_objednavky', models.FileField(blank=True, help_text="Súbor objednávky na poslanie autorovi na podpis, vygenerovaný akciou 'Vytvoriť súbor objednávky'.", null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.contract_path, verbose_name='Vygenerovaná objednávka')),
                ('vytvarna_zmluva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vytvarne_platby', to='zmluvy.zmluvagrafik')),
            ],
            options={
                'verbose_name': 'Objednávka a vyplatenie výtvarných diel',
                'verbose_name_plural': 'Objednávky a vyplácanie výtvarných diel',
            },
        ),
    ]
