# Generated by Django 3.2.6 on 2022-01-09 19:40

from django.db import migrations, models
import zmluvy.models
import zmluvy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0027_auto_20211217_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Krycí list</em> do účtárne THS (internou poštou)</em>. Dátum odoslania sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name="'Krycí list' odoslaný"),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='na_vyplatenie_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Na vyplatenie</em> do účtárne THS (mailom)</em>. Dátum odoslania sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name="'Na vyplatenie' odoslané"),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie do účtárne THS. Dátum odoslania sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Podklady odoslané'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='vygenerovana_crz_subor',
            field=models.TextField(blank=True, help_text="Anonymizovaný súbor zmluvy na vloženie do CRZ, vygenerovaný akciou 'Vytvoriť súbory zmluvy'. Pred vložením do CRZ treba aktualizovať dátum podpisu.", max_length=100, null=True, verbose_name='Vygenerovaný súbor zmluvy pre CRZ'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odoslania zmluvy na podpis (poštou).  Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odoslaná na podpis '),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='zmluva_vratena',
            field=models.DateField(blank=True, help_text='Dátum obdržania podpísanej zmluvy (poštou). Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Vrátená podpísaná '),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='vygenerovana_crz_subor',
            field=models.TextField(blank=True, help_text="Anonymizovaný súbor zmluvy na vloženie do CRZ, vygenerovaný akciou 'Vytvoriť súbory zmluvy'. Pred vložením do CRZ treba aktualizovať dátum podpisu.", max_length=100, null=True, verbose_name='Vygenerovaný súbor zmluvy pre CRZ'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odoslania zmluvy na podpis (poštou).  Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odoslaná na podpis '),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='zmluva_vratena',
            field=models.DateField(blank=True, help_text='Dátum obdržania podpísanej zmluvy (poštou). Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Vrátená podpísaná '),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Krycí list</em> do účtárne THS (internou poštou)</em>. Dátum odoslania sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name="'Krycí list' odoslaný"),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='na_vyplatenie_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania hárku <em>Na vyplatenie</em> do účtárne THS (mailom)</em>. Dátum odoslania sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name="'Na vyplatenie' odoslané"),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odoslania podkladov na vyplatenie do účtárne THS. Dátum odoslania sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Podklady odoslané'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='vygenerovana_crz_subor',
            field=models.FileField(blank=True, help_text="Anonymizovaný súbor zmluvy na vloženie do CRZ, vygenerovaný akciou 'Vytvoriť súbory zmluvy'. Pred vložením do CRZ treba aktualizovať dátum podpisu.", null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.contract_path, verbose_name='Vygenerovaný súbor zmluvy pre CRZ'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odoslania zmluvy na podpis (poštou).  Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odoslaná na podpis '),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='zmluva_vratena',
            field=models.DateField(blank=True, help_text='Dátum obdržania podpísanej zmluvy (poštou). Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Vrátená podpísaná '),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='vygenerovana_crz_subor',
            field=models.FileField(blank=True, help_text="Anonymizovaný súbor zmluvy na vloženie do CRZ, vygenerovaný akciou 'Vytvoriť súbory zmluvy'. Pred vložením do CRZ treba aktualizovať dátum podpisu.", null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.contract_path, verbose_name='Vygenerovaný súbor zmluvy pre CRZ'),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odoslania zmluvy na podpis (poštou).  Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odoslaná na podpis '),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='zmluva_vratena',
            field=models.DateField(blank=True, help_text='Dátum obdržania podpísanej zmluvy (poštou). Dátum sa zapíše do <a href="/admin/dennik/dokument/">denníka prijatej a odoslanej pošty</a>.', null=True, verbose_name='Vrátená podpísaná '),
        ),
    ]
