# Generated by Django 3.2.6 on 2022-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0028_auto_20220109_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('podpisana_enu', 'Podpísaná EnÚ'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Autorovi na podpis '),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('podpisana_enu', 'Podpísaná EnÚ'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Autorovi na podpis '),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('podpisana_enu', 'Podpísaná EnÚ'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Autorovi na podpis '),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('podpisana_enu', 'Podpísaná EnÚ'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Autorovi na podpis '),
        ),
    ]
