# Generated by Django 3.2.6 on 2022-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0029_auto_20220120_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='honorar_ah',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Honorár/AH'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='url_zmluvy',
            field=models.URLField(help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='url_zmluvy',
            field=models.URLField(help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='honorar_ah',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Honorár/AH'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='url_zmluvy',
            field=models.URLField(help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslana_poziadavka', 'Odoslaná požiadavka na sekretariát'), ('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='url_zmluvy',
            field=models.URLField(help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
    ]
