# Generated by Django 3.2.6 on 2022-02-19 15:18

from django.db import migrations, models
import zmluvy.models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0031_auto_20220218_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre THS'. <br /><strong>Pokiaľ platba autora neprešla, pred vytvorením finálneho prehľadu platieb ho zo zoznamu odstráňte</strong>.", max_length=2500, null=True, verbose_name='Vyplácaní autori'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_oznamenia',
            field=models.DateField(blank=True, help_text='Dátum oznámenia nezdanených autorov na finančnú správu (termín: do 15. dňa nasledujýceho mesiaca).', null=True, verbose_name='Oznámené FS'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov z poľa <em>Autorské honoráre</em> (oznámený účtárňou THS).', null=True, verbose_name='Vyplatené THS-kou'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov na vyplatenie zrážkovej dane a odvodov do fondov z poľa <em>Finálny prehľad</em> na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Daň na THS'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov na vyplatenie autorských honorárov z poľa <em>Autorské honoráre</em> na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Honoráre na THS'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatene',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi va vyplatenie zrážkovej dane a odvodov do fondov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odosielania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em>Daň na THS</em></strong>.<br /><strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť do šanonov</strong>.", max_length=100, null=True, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatit_ths',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre THS'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie autorských honorárov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odoselania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em> Honoráre na THS</em></strong>", max_length=100, null=True, verbose_name='Autorské honoráre'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre THS'. <br /><strong>Pokiaľ platba autora neprešla, pred vytvorením finálneho prehľadu platieb ho zo zoznamu odstráňte</strong>.", max_length=2500, null=True, verbose_name='Vyplácaní autori'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_oznamenia',
            field=models.DateField(blank=True, help_text='Dátum oznámenia nezdanených autorov na finančnú správu (termín: do 15. dňa nasledujýceho mesiaca).', null=True, verbose_name='Oznámené FS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov z poľa <em>Autorské honoráre</em> (oznámený účtárňou THS).', null=True, verbose_name='Vyplatené THS-kou'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov na vyplatenie zrážkovej dane a odvodov do fondov z poľa <em>Finálny prehľad</em> na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Daň na THS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov na vyplatenie autorských honorárov z poľa <em>Autorské honoráre</em> na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Honoráre na THS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatene',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi va vyplatenie zrážkovej dane a odvodov do fondov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odosielania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em>Daň na THS</em></strong>.<br /><strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť do šanonov</strong>.", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatit_ths',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre THS'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie autorských honorárov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odoselania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em> Honoráre na THS</em></strong>", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Autorské honoráre'),
        ),
    ]
