# Generated by Django 3.2.6 on 2022-02-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0032_auto_20220219_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplatbaautorskasumar',
            name='na_vyplatenie_odoslane',
        ),
        migrations.RemoveField(
            model_name='platbaautorskasumar',
            name='na_vyplatenie_odoslane',
        ),
    ]
