# Generated by Django 3.2.6 on 2022-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0033_auto_20220219_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Finálny prehľad</em> na vyplatenie zrážkovej dane a odvodov do fondov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Daň na THS'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Autorské honoráre</em> na vyplatenie autorských honorárov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Honoráre na THS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Finálny prehľad</em> na vyplatenie zrážkovej dane a odvodov do fondov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Daň na THS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Autorské honoráre</em> na vyplatenie autorských honorárov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Honoráre na THS'),
        ),
    ]
