# Generated by Django 3.2.6 on 2022-02-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0034_auto_20220219_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platbaautorskaodmena',
            old_name='obdobie',
            new_name='cislo',
        ),
    ]
