# Generated by Django 3.2.6 on 2022-02-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0035_rename_obdobie_platbaautorskaodmena_cislo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplatbaautorskasumar',
            old_name='obdobie',
            new_name='cislo',
        ),
        migrations.RenameField(
            model_name='platbaautorskasumar',
            old_name='obdobie',
            new_name='cislo',
        ),
    ]
