# Generated by Django 3.2.6 on 2022-03-04 08:51

from django.db import migrations, models
import zmluvy.models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0036_auto_20220219_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platbaautorskasumarsubor',
            options={'verbose_name': 'Súbor s údajmi o autorských honorároch (exportovaný z RS/WEBRS)', 'verbose_name_plural': 'Súbory aut. honorárov'},
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_oznamenia',
            field=models.DateField(blank=True, help_text='Dátum oznámenia výšky zrazenej dane na finančnú správu (termín: do 15. dňa nasledujúceho mesiaca).', null=True, verbose_name='Oznámené FS'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Finálny prehľad</em> na vyplatenie zrážkovej dane a odvodov do fondov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Daň – pre THS'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Autorské honoráre</em> na vyplatenie autorských honorárov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Honoráre – pre THS'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatene',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie zrážkovej dane a odvodov do fondov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odosielania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em>Daň – pre THS</em></strong>.<br /><strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť do šanonov</strong>.", max_length=100, null=True, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatit_ths',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre THS'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie autorských honorárov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odoselania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em> Honoráre – pre THS</em></strong>", max_length=100, null=True, verbose_name='Autorské honoráre'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_oznamenia',
            field=models.DateField(blank=True, help_text='Dátum oznámenia výšky zrazenej dane na finančnú správu (termín: do 15. dňa nasledujúceho mesiaca).', null=True, verbose_name='Oznámené FS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Finálny prehľad</em> na vyplatenie zrážkovej dane a odvodov do fondov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Daň – pre THS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Autorské honoráre</em> na vyplatenie autorských honorárov na sekretariát na odoslanie do účtárne THS.', null=True, verbose_name='Honoráre – pre THS'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatene',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie zrážkovej dane a odvodov do fondov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odosielania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em>Daň – pre THS</em></strong>.<br /><strong>Hárok <em>Po autoroch</em> treba vytlačiť a po autoroch založiť do šanonov</strong>.", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatit_ths',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre THS'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie autorských honorárov treba dať na sekretariát na odoslanie do účtárne THS</strong>. V prípade odoselania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em> Honoráre – pre THS</em></strong>", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Autorské honoráre'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('odoslany_dotaznik', 'Odoslaný dotazník autorovi'), ('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='<font color="#aa0000">Zvoliť aktuálny stav zmluvy</font> (po každej jeho zmene).', max_length=20),
        ),
    ]
