# Generated by Django 3.2.6 on 2022-05-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0037_auto_20220304_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='cislo',
            field=models.CharField(help_text='Identifikátor vyplácania v tvare AH-RRRR-NNN', max_length=20, null=True, verbose_name='Identifikátor vyplácania'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='cislo',
            field=models.CharField(help_text='Identifikátor vyplácania v tvare AH-RRRR-NNN', max_length=20, null=True, verbose_name='Identifikátor vyplácania'),
        ),
    ]
