# Generated by Django 3.2.6 on 2022-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0038_auto_20220505_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatbaautorskasumar',
            name='dan_zaplatena',
            field=models.DateField(blank=True, help_text='Dátum zaplatenia dane Finančnej správe. Potrebné pri oznamovaní výšky zrazenej dane Finančnej správe.', null=True, verbose_name='Daň zaplatená dňa'),
        ),
        migrations.AddField(
            model_name='platbaautorskasumar',
            name='dan_zaplatena',
            field=models.DateField(blank=True, help_text='Dátum zaplatenia dane Finančnej správe. Potrebné pri oznamovaní výšky zrazenej dane Finančnej správe.', null=True, verbose_name='Daň zaplatená dňa'),
        ),
    ]
