# Generated by Django 3.2.6 on 2022-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0039_auto_20220519_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalosobaautor',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalosobagrafik',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='osobaautor',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='osobagrafik',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
    ]
