# Generated by Django 3.2.6 on 2022-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0040_auto_20220603_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalosobaautor',
            name='rezident',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
        migrations.AlterField(
            model_name='historicalosobaautor',
            name='zdanit',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text="Zvoľte 'Nie', ak autor podpísal dohodu o nezdaňovaní. V tom prípade treba vyplniť aj polia 'Dohoda podpísaná' a 'Dohoda o nezdaňovaní'.", max_length=3, null=True, verbose_name='Zdaniť'),
        ),
        migrations.AlterField(
            model_name='historicalosobagrafik',
            name='rezident',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
        migrations.AlterField(
            model_name='historicalosobagrafik',
            name='zdanit',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text="Zvoľte 'Nie', ak autor podpísal dohodu o nezdaňovaní. V tom prípade treba vyplniť aj polia 'Dohoda podpísaná' a 'Dohoda o nezdaňovaní'.", max_length=3, null=True, verbose_name='Zdaniť'),
        ),
        migrations.AlterField(
            model_name='osobaautor',
            name='rezident',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
        migrations.AlterField(
            model_name='osobaautor',
            name='zdanit',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text="Zvoľte 'Nie', ak autor podpísal dohodu o nezdaňovaní. V tom prípade treba vyplniť aj polia 'Dohoda podpísaná' a 'Dohoda o nezdaňovaní'.", max_length=3, null=True, verbose_name='Zdaniť'),
        ),
        migrations.AlterField(
            model_name='osobagrafik',
            name='rezident',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text='Uveďte, či je autor daňovník s neobmedzenou daňovou povinnosťou v SR (daňový rezident SR). Ak autor nie je daňový rezident SR, tak sa jeho honorár nezdaňuje.', max_length=3, null=True, verbose_name='Rezident SR'),
        ),
        migrations.AlterField(
            model_name='osobagrafik',
            name='zdanit',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], default='ano', help_text="Zvoľte 'Nie', ak autor podpísal dohodu o nezdaňovaní. V tom prípade treba vyplniť aj polia 'Dohoda podpísaná' a 'Dohoda o nezdaňovaní'.", max_length=3, null=True, verbose_name='Zdaniť'),
        ),
    ]
