# Generated by Django 3.2.6 on 2022-11-27 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import zmluvy.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zmluvy', '0041_auto_20220922_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vytvarnaobjednavkaplatba',
            name='uhradena_suma',
        ),
        migrations.AddField(
            model_name='vytvarnaobjednavkaplatba',
            name='dane_na_uhradu',
            field=models.DateField(blank=True, help_text='Zadajte dátum odovzdania vytlačeného platobného príkazu a krycieho listu na sekretariát na ďalšie spracovanie. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>, ktorý vyplní sekretariát.', null=True, verbose_name='Odovzdané na sekretariát dňa'),
        ),
        migrations.AddField(
            model_name='vytvarnaobjednavkaplatba',
            name='datum_oznamenia',
            field=models.DateField(blank=True, help_text='Dátum oznámenia výšky zrazenej dane na finančnú správu (termín: do 15. dňa nasledujúceho mesiaca).<br />Nevyplňuje sa, ak sa autor zdaňuje sám.', null=True, verbose_name='Oznámené FS'),
        ),
        migrations.AddField(
            model_name='vytvarnaobjednavkaplatba',
            name='poznamka',
            field=models.CharField(blank=True, max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='vytvarnaobjednavkaplatba',
            name='subor_prikaz',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vygenerovať platobný príkaz'.<br /><strong>Po podpísaní dať na sekretariát na odoslanie do účtárne THS</strong>. Následne <strong>vyplňte pole <em>Dané na úhradu dňa</em></strong>.", null=True, upload_to=zmluvy.models.contract_path, verbose_name='Platobný príkaz'),
        ),
        migrations.AlterField(
            model_name='historicalosobaautor',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN účtu autora (s medzerami po štvoriciach).', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='historicalosobagrafik',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN účtu autora (s medzerami po štvoriciach).', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='osobaautor',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN účtu autora (s medzerami po štvoriciach).', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='osobagrafik',
            name='bankovy_kontakt',
            field=models.CharField(blank=True, help_text='Zadajte IBAN účtu autora (s medzerami po štvoriciach).', max_length=200, null=True, verbose_name='Bankový kontakt'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='datum_objednavky',
            field=models.DateField(help_text='Dátum odoslania objednávky autorovi (mailom)', null=True, verbose_name='Dátum objednávky'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum uhradenia odmeny a dane Finančnej správe (pokiaľ autor nepodpísal zmluvu o nezdaňovaní).', null=True, verbose_name='Uhradené dňa'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='honorar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Honorár na vyplatenie. Vyplní sa automaticky na základe položiek objednávky spustením akcie 'Vytvoriť súbor objednávky'.<br />Ak autor nedodá všetky objednané položky, pred generovaním príkazu na vyplatenie sumu upravte a do poľa 'Poznámka' uveďte zoznam nedodaných položiek.", max_digits=8, null=True, verbose_name='Honorár na vyplatenie'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='objednane_polozky',
            field=models.TextField(help_text="Po riadkoch zadajte objednávané položky so štyrmi poľami oddelenými bodkočiarkou v poradí: <b>Popis</b>; <b>Typ</b>; <b>Množstvo</b>; <b>Cena za jednotku</b>.<br />Ako typ uveďte: mapa, fotografia, čb perovka, farebná kresba.<br />Po vyplnení položiek vytvorte súbor objednávky akciou 'Vytvoriť súbor objednávky'.<br /><strong>Honorár sa dáva na vyplatenie jednorázovo až po dodaní všetkých objednaných položiek</strong>.", max_length=5000, null=True, verbose_name='Objednané položky'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='odvedena_dan',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", max_digits=8, null=True, verbose_name='Odvedená daň'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='odvod_LF',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", max_digits=8, null=True, verbose_name='Odvod aut. fondu'),
        ),
        migrations.CreateModel(
            name='HistoricalVytvarnaObjednavkaPlatba',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo objednávky')),
                ('objednane_polozky', models.TextField(help_text="Po riadkoch zadajte objednávané položky so štyrmi poľami oddelenými bodkočiarkou v poradí: <b>Popis</b>; <b>Typ</b>; <b>Množstvo</b>; <b>Cena za jednotku</b>.<br />Ako typ uveďte: mapa, fotografia, čb perovka, farebná kresba.<br />Po vyplnení položiek vytvorte súbor objednávky akciou 'Vytvoriť súbor objednávky'.<br /><strong>Honorár sa dáva na vyplatenie jednorázovo až po dodaní všetkých objednaných položiek</strong>.", max_length=5000, null=True, verbose_name='Objednané položky')),
                ('subor_objednavky', models.TextField(blank=True, help_text="Súbor objednávky na poslanie autorovi na podpis, vygenerovaný akciou 'Vytvoriť súbor objednávky'.", max_length=100, null=True, verbose_name='Vygenerovaná objednávka')),
                ('datum_objednavky', models.DateField(help_text='Dátum odoslania objednávky autorovi (mailom)', null=True, verbose_name='Dátum objednávky')),
                ('honorar', models.DecimalField(blank=True, decimal_places=2, help_text="Honorár na vyplatenie. Vyplní sa automaticky na základe položiek objednávky spustením akcie 'Vytvoriť súbor objednávky'.<br />Ak autor nedodá všetky objednané položky, pred generovaním príkazu na vyplatenie sumu upravte a do poľa 'Poznámka' uveďte zoznam nedodaných položiek.", max_digits=8, null=True, verbose_name='Honorár na vyplatenie')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='Poznámka')),
                ('subor_prikaz', models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vygenerovať platobný príkaz'.<br /><strong>Po podpísaní dať na sekretariát na odoslanie do účtárne THS</strong>. Následne <strong>vyplňte pole <em>Dané na úhradu dňa</em></strong>.", max_length=100, null=True, verbose_name='Platobný príkaz')),
                ('dane_na_uhradu', models.DateField(blank=True, help_text='Zadajte dátum odovzdania vytlačeného platobného príkazu a krycieho listu na sekretariát na ďalšie spracovanie. <br />Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>, ktorý vyplní sekretariát.', null=True, verbose_name='Odovzdané na sekretariát dňa')),
                ('datum_uhradenia', models.DateField(blank=True, help_text='Dátum uhradenia odmeny a dane Finančnej správe (pokiaľ autor nepodpísal zmluvu o nezdaňovaní).', null=True, verbose_name='Uhradené dňa')),
                ('datum_oznamenia', models.DateField(blank=True, help_text='Dátum oznámenia výšky zrazenej dane na finančnú správu (termín: do 15. dňa nasledujúceho mesiaca).<br />Nevyplňuje sa, ak sa autor zdaňuje sám.', null=True, verbose_name='Oznámené FS')),
                ('odvod_LF', models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", max_digits=8, null=True, verbose_name='Odvod aut. fondu')),
                ('odvedena_dan', models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre THS'", max_digits=8, null=True, verbose_name='Odvedená daň')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vytvarna_zmluva', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='zmluvy.zmluvagrafik')),
            ],
            options={
                'verbose_name': 'historical Objednávka a vyplatenie výtvarných diel',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
