# Generated by Django 3.2.6 on 2022-12-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0042_auto_20221127_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='honorar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Honorár. Vyplní sa automaticky na základe položiek objednávky spustením akcie 'Vytvoriť súbor objednávky'.<br />Ak autor nedodá všetky objednané položky, pred generovaním príkazu na vyplatenie sumu upravte a do poľa 'Poznámka' uveďte zoznam nedodaných položiek.", max_digits=8, null=True, verbose_name='Honorár'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='honorar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Honorár. Vyplní sa automaticky na základe položiek objednávky spustením akcie 'Vytvoriť súbor objednávky'.<br />Ak autor nedodá všetky objednané položky, pred generovaním príkazu na vyplatenie sumu upravte a do poľa 'Poznámka' uveďte zoznam nedodaných položiek.", max_digits=8, null=True, verbose_name='Honorár'),
        ),
    ]
