# Generated by Django 3.2.6 on 2023-01-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0043_auto_20221206_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='datum_dodania',
            field=models.DateField(help_text='Dátum dodania objednaných položiek', null=True, verbose_name='Dátum dodania'),
        ),
        migrations.AddField(
            model_name='vytvarnaobjednavkaplatba',
            name='datum_dodania',
            field=models.DateField(help_text='Dátum dodania objednaných položiek', null=True, verbose_name='Dátum dodania'),
        ),
    ]
