# Generated by Django 3.2.6 on 2023-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0045_auto_20230307_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20),
        ),
    ]
