# Generated by Django 3.2.6 on 2023-03-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0046_auto_20230307_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='poznamka',
            field=models.CharField(blank=True, help_text='Nepovinná poznámka', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='poznamka',
            field=models.CharField(blank=True, help_text='Nepovinná poznámka', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='poznamka',
            field=models.CharField(blank=True, help_text='Nepovinná poznámka', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='poznamka',
            field=models.CharField(blank=True, help_text='Nepovinná poznámka', max_length=200, verbose_name='Poznámka'),
        ),
    ]
