# Generated by Django 3.2.4 on 2023-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0047_auto_20230307_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na podpis vedeniu a na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odovzdaná dňa '),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na podpis vedeniu a na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odovzdaná dňa '),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na podpis vedeniu a na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odovzdaná dňa '),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='zmluva_odoslana',
            field=models.DateField(blank=True, help_text='Dátum odovzdania zmluvy na sekretariát na podpis vedeniu a na odoslanie na podpis (poštou). Vytvorí sa záznam v <a href="/admin/dennik/dokument/">denníku prijatej a odoslanej pošty</a>.', null=True, verbose_name='Odovzdaná dňa '),
        ),
    ]
