# Generated by Django 3.2.4 on 2023-07-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0049_auto_20230519_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalzmluvaautor',
            name='url_zmluvy',
            field=models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalzmluvagrafik',
            name='url_zmluvy',
            field=models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmluvaautor',
            name='url_zmluvy',
            field=models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='datum_zverejnenia_CRZ',
            field=models.DateField(blank=True, help_text='Zadajte dátum účinnosti zmluvy (dátum zverejnenia v CRZ + 1 deň). <br />Ak autor podpísal dohodu o nezdaňovaní, vyplňte súvisiace polia v údajoch autora.', null=True, verbose_name='Platná od / dátum CRZ'),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='stav_zmluvy',
            field=models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('odoslana_autorovi', 'Daná autorovi na podpis'), ('vratena_od_autora', 'Vrátená od autora'), ('zverejnena_v_crz', 'Platná / Zverejnená v CRZ'), ('neplatna', 'Neplatná / Nebola verejnená v CRZ')], help_text='Hodnotu poľa <strong>netreba vypĺňať</strong>, aktualizuje sa automaticky. Superpoužívateľ môže v prípade potreby nastaviť stav <strong>Neplatná / Nebola verejnená v CRZ</strong>. ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmluvagrafik',
            name='url_zmluvy',
            field=models.URLField(blank=True, help_text='Zadajte URL pdf súboru zmluvy zo stránky CRZ.', null=True, verbose_name='URL zmluvy'),
        ),
    ]
