# Generated by Django 3.2.4 on 2024-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0050_auto_20230726_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='dodane_dna',
            field=models.DateField(help_text='Skutočný dátum dodania objednaných položiek', null=True, verbose_name='Dodané dňa'),
        ),
        migrations.AddField(
            model_name='vytvarnaobjednavkaplatba',
            name='dodane_dna',
            field=models.DateField(help_text='Skutočný dátum dodania objednaných položiek', null=True, verbose_name='Dodané dňa'),
        ),
        migrations.AlterField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='datum_dodania',
            field=models.DateField(help_text='Dohodnutý dátum dodania objednaných položiek', null=True, verbose_name='Dátum dodania'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='datum_dodania',
            field=models.DateField(help_text='Dohodnutý dátum dodania objednaných položiek', null=True, verbose_name='Dátum dodania'),
        ),
    ]
