# Generated by Django 3.2.4 on 2024-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0052_auto_20240223_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='dodane_dna',
        ),
        migrations.RemoveField(
            model_name='vytvarnaobjednavkaplatba',
            name='dodane_dna',
        ),
        migrations.AlterField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='datum_dodania',
            field=models.DateField(help_text='Dátum dodania objednaných položiek', null=True, verbose_name='Dátum dodania'),
        ),
        migrations.AlterField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='datum_objednavky',
            field=models.DateField(help_text='Dátum odoslania objednávky autorovi (mailom)', null=True, verbose_name='Dátum objednávky'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='datum_dodania',
            field=models.DateField(help_text='Dátum dodania objednaných položiek', null=True, verbose_name='Dátum dodania'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='datum_objednavky',
            field=models.DateField(help_text='Dátum odoslania objednávky autorovi (mailom)', null=True, verbose_name='Dátum objednávky'),
        ),
    ]
