# Generated by Django 3.2.4 on 2024-03-05 21:35

from django.db import migrations, models
import zmluvy.models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0053_auto_20240305_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre učtáreň'. <br /><strong>Pokiaľ platba autora neprešla, pred vytvorením finálneho prehľadu platieb ho zo zoznamu odstráňte</strong>.", max_length=2500, null=True, verbose_name='Vyplácaní autori'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov z poľa <em>Autorské honoráre</em> (oznámený učtárňou).', null=True, verbose_name='Vyplatené učtárňou'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Finálny prehľad</em> na vyplatenie zrážkovej dane a odvodov do fondov na sekretariát na odoslanie do učtárne.', null=True, verbose_name='Daň – pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Autorské honoráre</em> na vyplatenie autorských honorárov na sekretariát na odoslanie do učtárne.', null=True, verbose_name='Honoráre – pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatene',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie zrážkovej dane a odvodov do fondov treba dať na sekretariát na odoslanie do učtárne</strong>. V prípade odosielania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em>Daň – pre učtáreň</em></strong>.", max_length=100, null=True, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='historicalplatbaautorskasumar',
            name='vyplatit_ths',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre učtáreň'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie autorských honorárov treba dať na sekretariát na odoslanie do učtárne</strong>. V prípade odoselania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em> Honoráre – pre učtáreň</em></strong>", max_length=100, null=True, verbose_name='Autorské honoráre'),
        ),
        migrations.AlterField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='odvedena_dan',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre učtáreň'", max_digits=8, null=True, verbose_name='Odvedená daň'),
        ),
        migrations.AlterField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='odvod_LF',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre učtáreň'", max_digits=8, null=True, verbose_name='Odvod aut. fondu'),
        ),
        migrations.AlterField(
            model_name='historicalvytvarnaobjednavkaplatba',
            name='subor_prikaz',
            field=models.TextField(blank=True, help_text="Súbor generovaný akciou 'Vygenerovať platobný príkaz'.<br /><strong>Po podpísaní dať na sekretariát na odoslanie do učtárne</strong>. Následne <strong>vyplňte pole <em>Dané na úhradu dňa</em></strong>.", max_length=100, null=True, verbose_name='Platobný príkaz'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='autori_na_vyplatenie',
            field=models.TextField(blank=True, help_text="Zoznam vyplácaných autorov. Vypĺňa sa automaticky akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre učtáreň'. <br /><strong>Pokiaľ platba autora neprešla, pred vytvorením finálneho prehľadu platieb ho zo zoznamu odstráňte</strong>.", max_length=2500, null=True, verbose_name='Vyplácaní autori'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='datum_uhradenia',
            field=models.DateField(blank=True, help_text='Dátum vyplatenia honorárov na základe odoslaných podkladov z poľa <em>Autorské honoráre</em> (oznámený učtárňou).', null=True, verbose_name='Vyplatené učtárňou'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='kryci_list_odoslany',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Finálny prehľad</em> na vyplatenie zrážkovej dane a odvodov do fondov na sekretariát na odoslanie do učtárne.', null=True, verbose_name='Daň – pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='podklady_odoslane',
            field=models.DateField(blank=True, help_text='Dátum odovzdania podkladov z poľa <em>Autorské honoráre</em> na vyplatenie autorských honorárov na sekretariát na odoslanie do učtárne.', null=True, verbose_name='Honoráre – pre učtáreň'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatene',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť finálny prehľad o vyplácaní a zaznamenať platby do databázy'.<br /><strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie zrážkovej dane a odvodov do fondov treba dať na sekretariát na odoslanie do učtárne</strong>. V prípade odosielania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em>Daň – pre učtáreň</em></strong>.", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Finálny prehľad'),
        ),
        migrations.AlterField(
            model_name='platbaautorskasumar',
            name='vyplatit_ths',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vytvoriť podklady na vyplatenie autorských honorárov pre učtáreň'. <br />Súbor obsahuje údaje pre vyplácanie autorských honorárov (hárok <em>Na vyplatenie</em>) a zoznam chýb, ktoré boli pre generovaní zistené (hárok <em>Chyby</em>).<br /> <strong>Hárky <em>Na vyplatenie</em> a <em>Krycí list</em> s údajmi na vyplatenie autorských honorárov treba dať na sekretariát na odoslanie do učtárne</strong>. V prípade odoselania e-mailom treba odoslať PDF súbor. Následne <strong>vyplňte pole <em> Honoráre – pre učtáreň</em></strong>", null=True, upload_to=zmluvy.models.platba_autorska_sumar_upload_location, verbose_name='Autorské honoráre'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='odvedena_dan',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre učtáreň'", max_digits=8, null=True, verbose_name='Odvedená daň'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='odvod_LF',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Automaticky doplnené akciou 'Vytvoriť platobný príkaz a krycí list pre učtáreň'", max_digits=8, null=True, verbose_name='Odvod aut. fondu'),
        ),
        migrations.AlterField(
            model_name='vytvarnaobjednavkaplatba',
            name='subor_prikaz',
            field=models.FileField(blank=True, help_text="Súbor generovaný akciou 'Vygenerovať platobný príkaz'.<br /><strong>Po podpísaní dať na sekretariát na odoslanie do učtárne</strong>. Následne <strong>vyplňte pole <em>Dané na úhradu dňa</em></strong>.", null=True, upload_to=zmluvy.models.contract_path, verbose_name='Platobný príkaz'),
        ),
    ]
