# Generated by Django 3.2.4 on 2024-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0054_auto_20240305_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalosobaautor',
            name='var_symbol',
            field=models.CharField(blank=True, help_text='Variabilný symbol platieb. Vytvára sa automaticky', max_length=20, null=True, verbose_name='Variabilný symbol'),
        ),
        migrations.AddField(
            model_name='historicalosobagrafik',
            name='var_symbol',
            field=models.CharField(blank=True, help_text='Variabilný symbol platieb. Vytvára sa automaticky', max_length=20, null=True, verbose_name='Variabilný symbol'),
        ),
        migrations.AddField(
            model_name='osobaautor',
            name='var_symbol',
            field=models.CharField(blank=True, help_text='Variabilný symbol platieb. Vytvára sa automaticky', max_length=20, null=True, verbose_name='Variabilný symbol'),
        ),
        migrations.AddField(
            model_name='osobagrafik',
            name='var_symbol',
            field=models.CharField(blank=True, help_text='Variabilný symbol platieb. Vytvára sa automaticky', max_length=20, null=True, verbose_name='Variabilný symbol'),
        ),
    ]
