# Generated by Django 3.2.4 on 2025-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmluvy', '0056_auto_20250126_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalosobaautor',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Rezidenti SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='historicalosobagrafik',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Rezidenti SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='osobaautor',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Rezidenti SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='osobagrafik',
            name='rodne_cislo',
            field=models.CharField(blank=True, help_text='Rezidenti SR: rodné číslo, inak dátum narodenia ', max_length=20, null=True, verbose_name='Rodné číslo'),
        ),
    ]
