# Generated by Django 3.2.4 on 2026-02-17 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import zmluvy.models
import zmluvy.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zmluvy', '0057_auto_20250126_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PravoNaPouzitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo záznamu')),
                ('ilustracia_nazov', models.CharField(max_length=100, verbose_name='Názov ilustrácie')),
                ('ilustracia_autor', models.CharField(max_length=100, verbose_name='Autor ilustrácie')),
                ('zobrazit_v_knihe', models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Autor súhlasil s použitím v knihe', max_length=3, null=True, verbose_name='Zobraziť v knihe')),
                ('zobrazit_na_webe', models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Autor súhlasil s použitím na webe', max_length=3, null=True, verbose_name='Zobraziť na_webe')),
                ('ilustrácie_text', models.TextField(help_text='Uveďte údaje súvisiace so získaním práv k ilustrácii, detaily licenčných podmienok ap.', max_length=3000, null=True, verbose_name='Doplňujúci text')),
                ('subor_prava', models.FileField(blank=True, help_text='Súbor faktúry, dohody, mailovej komunikácie ...', null=True, storage=zmluvy.storage.OverwriteStorage(), upload_to=zmluvy.models.prava_ilustracie_path, verbose_name='Súbor s údajmi')),
            ],
            options={
                'verbose_name': 'Právo na použitie',
                'verbose_name_plural': 'Právo na použitie',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPravoNaPouzitie',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, null=True, verbose_name='Číslo záznamu')),
                ('ilustracia_nazov', models.CharField(max_length=100, verbose_name='Názov ilustrácie')),
                ('ilustracia_autor', models.CharField(max_length=100, verbose_name='Autor ilustrácie')),
                ('zobrazit_v_knihe', models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Autor súhlasil s použitím v knihe', max_length=3, null=True, verbose_name='Zobraziť v knihe')),
                ('zobrazit_na_webe', models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text='Autor súhlasil s použitím na webe', max_length=3, null=True, verbose_name='Zobraziť na_webe')),
                ('ilustrácie_text', models.TextField(help_text='Uveďte údaje súvisiace so získaním práv k ilustrácii, detaily licenčných podmienok ap.', max_length=3000, null=True, verbose_name='Doplňujúci text')),
                ('subor_prava', models.TextField(blank=True, help_text='Súbor faktúry, dohody, mailovej komunikácie ...', max_length=100, null=True, verbose_name='Súbor s údajmi')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Právo na použitie',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
